"""baseline schema from 001_init

Revision ID: 8e99211b3730
Revises:
Create Date: 2026-06-12 07:46:32.118516
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e99211b3730"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_app",
        sa.Column("canonical_key", sa.Text(), nullable=False),
        sa.Column("app_name", sa.Text(), nullable=True),
        sa.Column("apple_id", sa.BigInteger(), nullable=True),
        sa.Column("android_package", sa.Text(), nullable=True),
        sa.Column("ios_bundle_id", sa.Text(), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("pod", sa.Text(), nullable=True),
        sa.Column("pod_owner", sa.Text(), nullable=True),
        sa.Column("hou", sa.Text(), nullable=True),
        sa.Column("app_category", sa.Text(), nullable=True),
        sa.Column("ownership_type", sa.Text(), nullable=True),
        sa.Column("is_mapped", sa.Boolean(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("canonical_key", name=op.f("pk_dim_app")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'running'"), nullable=False),
        sa.Column("rows_loaded", sa.BigInteger(), nullable=True),
        sa.Column("rows_previous", sa.BigInteger(), nullable=True),
        sa.Column("bq_built_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running','success','schema_mismatch','failed')",
            name=op.f("ck_sync_runs_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firebase_uid", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_users_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("firebase_uid", name=op.f("uq_users_firebase_uid")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "idx_audit_action_time",
        "audit_log",
        ["action", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_audit_user_time",
        "audit_log",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "role_capabilities",
        sa.Column("role_id", sa.SmallInteger(), nullable=False),
        sa.Column("capability", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "capability IN ('export','share_report','admin_panel')",
            name=op.f("ck_role_capabilities_capability_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_capabilities_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "capability", name=op.f("pk_role_capabilities")),
    )
    op.create_table(
        "role_metric_permissions",
        sa.Column("role_id", sa.SmallInteger(), nullable=False),
        sa.Column("metric_group", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "metric_group IN ('store_installs','ua_spend','ad_revenue','iap_revenue','attribution','profitability')",
            name=op.f("ck_role_metric_permissions_metric_group_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_metric_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "metric_group", name=op.f("pk_role_metric_permissions")),
    )
    op.create_table(
        "saved_reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("columns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("group_by", sa.Text(), nullable=False),
        sa.Column("sort", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "group_by IN ('app','pod','publisher','platform','hou','date')",
            name=op.f("ck_saved_reports_group_by_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_reports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_reports")),
    )
    op.create_index("idx_reports_user", "saved_reports", ["user_id"], unique=False)
    op.create_table(
        "saved_views",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("page", sa.Text(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_views_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_views")),
    )
    op.create_index("idx_views_user", "saved_views", ["user_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "user_scopes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.Text(), nullable=False),
        sa.Column("scope_value", sa.Text(), nullable=True),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'all' AND scope_value IS NULL) OR (scope_type <> 'all' AND scope_value IS NOT NULL)",
            name=op.f("ck_user_scopes_scope_value_required"),
        ),
        sa.CheckConstraint(
            "scope_type IN ('all','hou','pod','publisher','app')",
            name=op.f("ck_user_scopes_scope_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_user_scopes_granted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_scopes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_scopes")),
        sa.UniqueConstraint(
            "user_id",
            "scope_type",
            "scope_value",
            name="user_scopes_user_id_scope_type_scope_value_key",
        ),
    )
    op.create_index("idx_scopes_user", "user_scopes", ["user_id"], unique=False)
    op.create_table(
        "report_shares",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("shared_by", sa.UUID(), nullable=False),
        sa.Column("shared_with", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','approved','rejected','revoked')",
            name=op.f("ck_report_shares_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_report_shares_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["saved_reports.id"],
            name=op.f("fk_report_shares_report_id_saved_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shared_by"], ["users.id"], name=op.f("fk_report_shares_shared_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["shared_with"], ["users.id"], name=op.f("fk_report_shares_shared_with_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_shares")),
        sa.UniqueConstraint(
            "report_id", "shared_with", name="report_shares_report_id_shared_with_key"
        ),
    )
    op.create_index(
        "idx_shares_pending",
        "report_shares",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###

    # ── Seed data (mirrors sql/postgres/001_init.sql). Autogenerate cannot
    #    capture INSERTs, so these are maintained by hand. The least-privilege
    #    DB roles (api_service/sync_service) and GRANTs from 001_init.sql are a
    #    production deploy concern and are intentionally NOT created here.
    op.execute(
        """
        INSERT INTO roles (name) VALUES
          ('admin'), ('executive'), ('pod_owner'), ('marketing'), ('finance'), ('viewer');
        """
    )
    op.execute(
        """
        INSERT INTO role_metric_permissions (role_id, metric_group)
        SELECT r.id, g.g
        FROM roles r
        JOIN LATERAL (
          SELECT unnest(CASE r.name
            WHEN 'admin'     THEN ARRAY['store_installs','ua_spend','ad_revenue','iap_revenue','attribution','profitability']
            WHEN 'executive' THEN ARRAY['store_installs','ua_spend','ad_revenue','iap_revenue','attribution','profitability']
            WHEN 'pod_owner' THEN ARRAY['store_installs','ua_spend','ad_revenue','iap_revenue','attribution','profitability']
            WHEN 'marketing' THEN ARRAY['store_installs','ua_spend','ad_revenue','iap_revenue','profitability']
            WHEN 'finance'   THEN ARRAY['store_installs','ua_spend','ad_revenue','iap_revenue','profitability']
            WHEN 'viewer'    THEN ARRAY['store_installs']
          END) AS g
        ) g ON true;
        """
    )
    op.execute(
        """
        INSERT INTO role_capabilities (role_id, capability)
        SELECT r.id, c.c
        FROM roles r
        JOIN LATERAL (
          SELECT unnest(CASE r.name
            WHEN 'admin'     THEN ARRAY['export','share_report','admin_panel']
            WHEN 'executive' THEN ARRAY['export','share_report']
            WHEN 'pod_owner' THEN ARRAY['export','share_report']
            WHEN 'marketing' THEN ARRAY['export','share_report']
            WHEN 'finance'   THEN ARRAY['export','share_report']
            ELSE ARRAY[]::text[]
          END) AS c
        ) c ON true;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_shares_pending",
        table_name="report_shares",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("report_shares")
    op.drop_index("idx_scopes_user", table_name="user_scopes")
    op.drop_table("user_scopes")
    op.drop_table("user_roles")
    op.drop_index("idx_views_user", table_name="saved_views")
    op.drop_table("saved_views")
    op.drop_index("idx_reports_user", table_name="saved_reports")
    op.drop_table("saved_reports")
    op.drop_table("role_metric_permissions")
    op.drop_table("role_capabilities")
    op.drop_index("idx_audit_user_time", table_name="audit_log")
    op.drop_index("idx_audit_action_time", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("sync_runs")
    op.drop_table("roles")
    op.drop_table("dim_app")
    # ### end Alembic commands ###
