#!/usr/bin/env python3
"""Make image builds deterministic: install against the lock, ceiling what the lock misses.

THE INCIDENT THIS CLOSES
------------------------
The image installs with `pip install .` against pyproject's `>=` floors, so every build
takes the newest anything. That is how the openai 3.x major walked into production and
broke the assistant - the platform audit flagged unpinned SDK majors (finding #5) before
it happened, and then it happened. backend/requirements.txt is a full pinned lock and
NOTHING installs from it; it exists "for compatibility / reference only".

WHAT CHANGES
------------
Two constraint files ride along on the existing install line(s):

  * requirements.txt   - the generated lock. A constraint does not install anything; it
    pins whatever pip was going to install anyway. pyproject stays the single source of
    truth for WHAT is installed; the lock decides WHICH VERSION.
  * constraints.txt    - GENERATED HERE, for top-level deps that pyproject declares but
    the lock has not caught up with (on this server that is at least the chat SDKs, which
    were added by patch scripts that never re-ran the lock compiler; in this repo it is
    python-multipart). Each gets a ceiling one major above its declared floor - blocking
    exactly the surprise-major class of breakage, while letting patch and minor releases
    through until the lock is regenerated.

If the Dockerfile still has the older TWO-STEP install (pip install . / then sync
requirements separately), it is converged to the single-pass form this repo already
documents - the second pass silently downgraded redis once, and a second resolver pass
can quietly re-decide versions the first one chose.

SAFETY
------
  * ABORTS if any locked version is below its pyproject floor - that means the lock is
    stale in a way constraints would turn into an unsatisfiable build; regenerate first:
        cd backend && uv pip compile pyproject.toml --python-version 3.12 \
          --no-header -o requirements.txt
  * A dep in the lock satisfies everything -> constraints.txt entry not needed.
  * A dep with no floor at all cannot get a derived ceiling - listed in the file as a
    comment so the gap is visible instead of silent.
  * No pytest coverage applies to a Dockerfile; the docker build at deploy IS the test,
    and a genuine conflict now fails the build loudly instead of shipping quietly.
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(".")
DOCKERFILE = ROOT / "backend/Dockerfile"
PYPROJECT = ROOT / "backend/pyproject.toml"
LOCK = ROOT / "backend/requirements.txt"
CONSTRAINTS = ROOT / "backend/constraints.txt"

report: list[str] = []
skipped: list[str] = []


def norm(name: str) -> str:
    return name.lower().replace("_", "-")


def vtuple(version: str) -> tuple[int, ...]:
    return tuple(int(x) for x in re.findall(r"\d+", version)[:3]) or (0,)


def top_level_deps() -> list[tuple[str, str | None]]:
    """(normalized name, floor version or None) for every [project.dependencies] entry."""
    deps = tomllib.load(PYPROJECT.open("rb"))["project"]["dependencies"]
    out: list[tuple[str, str | None]] = []
    for dep in deps:
        m = re.match(r"^\s*([A-Za-z0-9_.-]+)(\[[^\]]*\])?\s*(.*)$", dep)
        if not m:
            continue
        floor = re.search(r">=\s*([0-9][0-9A-Za-z.]*)", m.group(3) or "")
        out.append((norm(m.group(1)), floor.group(1) if floor else None))
    return out


def locked_versions() -> dict[str, str]:
    versions: dict[str, str] = {}
    for line in LOCK.read_text().splitlines():
        m = re.match(r"^([A-Za-z0-9_.-]+)==([0-9][^\s;]*)", line)
        if m:
            versions[norm(m.group(1))] = m.group(2)
    return versions


def write_constraints(deps: list[tuple[str, str | None]], lock: dict[str, str]) -> None:
    ceilinged: list[str] = []
    uncoverable: list[str] = []
    for name, floor in deps:
        if name in lock:
            continue
        if floor is None:
            uncoverable.append(name)
            continue
        ceiling = vtuple(floor)[0] + 1
        ceilinged.append(f"{name}<{ceiling}")
    lines = [
        "# GENERATED by scripts/pin-dependencies.py - do not edit by hand.",
        "#",
        "# Ceilings for top-level deps that pyproject declares but requirements.txt (the",
        "# lock) has not caught up with. One major above each declared floor: blocks the",
        "# surprise-major breakage class (see: the openai 3.x incident) while letting",
        "# patches and minors through. Regenerating the lock empties this file's job:",
        "#   cd backend && uv pip compile pyproject.toml --python-version 3.12 \\",
        "#     --no-header -o requirements.txt",
        "",
        *sorted(ceilinged),
    ]
    if uncoverable:
        lines += [
            "",
            "# No version floor declared in pyproject, so no ceiling can be derived -",
            "# these remain fully unpinned until the lock covers them:",
            *[f"#   {name}" for name in sorted(uncoverable)],
        ]
    CONSTRAINTS.write_text("\n".join(lines) + "\n")
    what = ", ".join(sorted(ceilinged)) if ceilinged else "none needed - the lock covers everything"
    report.append(f"[pins] {CONSTRAINTS}: {what}")


def patch_dockerfile() -> None:
    text = DOCKERFILE.read_text()
    if "-c requirements.txt" in text:
        report.append("[image] Dockerfile already installs against the lock - left alone")
        return

    copy_old = "COPY pyproject.toml README.md ./"
    copy_new = "COPY pyproject.toml README.md requirements.txt constraints.txt ./"
    if copy_new in text:
        pass
    elif text.count(copy_old) == 1:
        text = text.replace(copy_old, copy_new, 1)
    else:
        skipped.append(
            f"[image] expected exactly one `{copy_old}` in the Dockerfile, found "
            f"{text.count(copy_old)}. Nothing written."
        )
        return

    combined = "RUN pip install . -r sync/requirements.txt"
    split_app = re.compile(r"^RUN pip install \.\s*$", re.M)
    split_sync = re.compile(r"^RUN pip install -r sync/requirements\.txt\s*$\n?", re.M)
    constrained = (
        "# ONE resolver pass over BOTH dependency sets, CONSTRAINED by the lock: pyproject\n"
        "# says WHAT is installed, requirements.txt says WHICH VERSION, constraints.txt\n"
        "# ceilings whatever the lock has not caught up with. A build stops resolving\n"
        "# 'newest anything' - which is how an SDK major once walked into production.\n"
        "RUN pip install . -r sync/requirements.txt -c requirements.txt -c constraints.txt"
    )

    if combined in text:
        text = text.replace(combined, constrained.splitlines()[-1], 1)
        report.append("[image] Dockerfile: the combined install now carries both constraint files")
    elif split_app.search(text) and split_sync.search(text):
        text = split_sync.sub("", text)
        text = split_app.sub(constrained, text, count=1)
        report.append(
            "[image] Dockerfile: converged the two-step install to one constrained resolver "
            "pass (the second pass once silently downgraded redis)"
        )
    else:
        skipped.append(
            "[image] found neither the combined nor the two-step pip install - nothing "
            "written. The install line on disk:\n      "
            + "\n      ".join(ln for ln in text.splitlines() if "pip install" in ln)
        )
        return
    DOCKERFILE.write_text(text)


def main() -> int:
    for path in (DOCKERFILE, PYPROJECT, LOCK):
        if not path.exists():
            print(f"ABORTED: missing {path}", file=sys.stderr)
            return 1

    deps = top_level_deps()
    lock = locked_versions()

    stale = [
        (name, floor, lock[name])
        for name, floor in deps
        if floor and name in lock and vtuple(lock[name]) < vtuple(floor)
    ]
    if stale:
        print(
            "ABORTED: the lock is BELOW pyproject's floors for these - constraining on it\n"
            "would make the build unsatisfiable. Regenerate the lock first:\n"
            "  cd backend && uv pip compile pyproject.toml --python-version 3.12 "
            "--no-header -o requirements.txt\n",
            file=sys.stderr,
        )
        for name, floor, locked in stale:
            print(f"  {name}: locked {locked} < floor {floor}", file=sys.stderr)
        return 1

    write_constraints(deps, lock)
    patch_dockerfile()

    print("PATCHED - the docker build at deploy is the verification for an image change.")
    for line in report:
        print(f"  - {line}")
    if skipped:
        print("\nSKIPPED (nothing written for these):")
        for entry in skipped:
            print(f"\n  {entry}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
