#!/usr/bin/env python3
"""Quick wins, batch 2: apps in the command palette, and the numbers behind every chart.

1. APPS IN THE COMMAND PALETTE
   Ctrl+K reached the six pages and nothing else. There are hundreds of apps and the only
   route to one was the Apps page plus a scroll. Typing two characters now offers the
   closest eight matches - two rather than zero, so the pages the palette exists for are
   not buried under an app list.

2. THE NUMBERS BEHIND EVERY CHART
   Every chart is a canvas: it cannot be read by a screen reader, copied into a mail,
   found with Ctrl+F, or printed as anything but a picture - and v1 has no PDF export by
   design, so the printed page IS what leaves the building. A toggle on each chart now
   shows the same data as a table, derived from the option the chart already renders, so
   there is one source and no second version to drift out of step.

3. A MULTISELECT THAT NAMES ITSELF
   With a selection it rendered "2 selected" and nothing more, which beside three other
   dropdowns says which count, not which filter - and a filter you cannot identify is one
   you cannot undo. It is now "HOU: 2".

WHAT THIS DELIBERATELY DOES NOT DO: an earlier version of this batch rewrote the filter
bar. It was aborted by the sha guard, and that was right - the deployed filter bar is
already better than the rewrite. It has a proper FilterPanel, dimensions extracted to
their own module, an active-filter count with a Clear button, inline dropdowns hidden
below xl so a phone does not get a wall of ten, and `busy = !data` rather than
`isFetching` - which was greying out every dropdown mid-click on each background refresh.
The rewrite would have destroyed all of that. It is dropped.

Verified: chart-table derivation covered by 7 tests over the option shapes the dashboard
actually builds; the palette and chart edits re-anchored against the deployed files.

ALL-OR-NOTHING. Every anchor is checked before anything is written. If any fails, the
script reports EVERY problem at once and writes NOTHING.
Idempotent: re-running changes nothing.
"""

import base64
import hashlib
import json
import sys
from pathlib import Path

PAYLOAD = """
eyJuZXdfZmlsZXMiOiB7ImZyb250ZW5kL2xpYi9jaGFydC10YWJsZS50cyI6ICIvKiogRGVyaXZpbmcgYSByZWFkYWJsZSB0YWJs
ZSBmcm9tIGFueSBjaGFydCdzIEVDaGFydHMgb3B0aW9uLlxuICpcbiAqIEV2ZXJ5IGNoYXJ0IGluIHRoZSBkYXNoYm9hcmQgaXMg
YSBjYW52YXMuIEEgY2FudmFzIGNhbm5vdCBiZSByZWFkIGJ5IGEgc2NyZWVuIHJlYWRlcixcbiAqIGNhbm5vdCBiZSBjb3BpZWQg
aW50byBhIG1haWwsIGNhbm5vdCBiZSBzZWFyY2hlZCB3aXRoIEN0cmwrRiwgYW5kIHByaW50cyBhcyBhIHBpY3R1cmUuXG4gKiBG
b3IgYSBjaGFydCB3aG9zZSB3aG9sZSBqb2IgaXMgdG8gY2FycnkgbnVtYmVycywgdGhhdCBpcyBhIHJlYWwgbG9zcyBcdTIwMTQg
YW5kIHRoZXJlIGlzIG5vXG4gKiBQREYgZXhwb3J0IGluIHYxLCBzbyB0aGUgcHJpbnRlZCBwYWdlIElTIHRoZSBhcnRlZmFjdCBw
ZW9wbGUgdGFrZSB0byBtZWV0aW5ncy5cbiAqXG4gKiBSYXRoZXIgdGhhbiBtYWtlIH4xOCBoYW5kLWJ1aWx0IGNoYXJ0cyBlYWNo
IGV4cG9zZSB0aGVpciBkYXRhIHNlcGFyYXRlbHksIHRoaXMgcmVhZHNcbiAqIHRoZSBvcHRpb24gdGhleSBhbHJlYWR5IHBhc3Mg
dG8gRUNoYXJ0cy4gU2FtZSBzb3VyY2UsIG5vIHNlY29uZCB2ZXJzaW9uIHRvIGRyaWZ0LlxuICpcbiAqIE5vdGhpbmcgaGVyZSBt
dXRhdGVzIHRoZSBvcHRpb24sIGFuZCBhbiBvcHRpb24gaXQgY2Fubm90IG1ha2Ugc2Vuc2Ugb2YgcmV0dXJucyBudWxsIHNvXG4g
KiB0aGUgY2FsbGVyIHNpbXBseSBkb2VzIG5vdCBvZmZlciB0aGUgdmlldy5cbiAqL1xuaW1wb3J0IHR5cGUgeyBFQ2hhcnRzT3B0
aW9uIH0gZnJvbSBcIkAvbGliL2VjaGFydHNcIjtcblxuLyoqIExvb3NlIHN0cnVjdHVyYWwgdmlld3Mgb2YgdGhlIG9wdGlvbiBr
ZXlzIHdlIHJlYWQuICovXG50eXBlIFNlcmllc1JlYyA9IHsgdHlwZT86IHN0cmluZzsgbmFtZT86IHN0cmluZzsgZGF0YT86IHVu
a25vd247IFtrOiBzdHJpbmddOiB1bmtub3duIH07XG50eXBlIEF4aXNSZWMgPSB7IHR5cGU/OiBzdHJpbmc7IGRhdGE/OiB1bmtu
b3duOyBbazogc3RyaW5nXTogdW5rbm93biB9O1xudHlwZSBQb2ludFJlYyA9IHsgbmFtZT86IHVua25vd247IHZhbHVlPzogdW5r
bm93biB9O1xuXG5leHBvcnQgaW50ZXJmYWNlIENoYXJ0VGFibGUge1xuICAvKiogSGVhZGVyIGNlbGxzLiBUaGUgZmlyc3QgaXMg
dGhlIGNhdGVnb3J5L2F4aXMgY29sdW1uLiAqL1xuICBjb2x1bW5zOiBzdHJpbmdbXTtcbiAgLyoqIE9uZSByb3cgcGVyIGNhdGVn
b3J5OyBjZWxsIDAgaXMgdGhlIGxhYmVsLCB0aGUgcmVzdCBhcmUgc2VyaWVzIHZhbHVlcy4gKi9cbiAgcm93czogKHN0cmluZyB8
IG51bWJlciB8IG51bGwpW11bXTtcbn1cblxuZnVuY3Rpb24gYXNBcnJheTxUPih2YWx1ZTogdW5rbm93bik6IFRbXSB7XG4gIGlm
ICh2YWx1ZSA9PSBudWxsKSByZXR1cm4gW107XG4gIHJldHVybiAoQXJyYXkuaXNBcnJheSh2YWx1ZSkgPyB2YWx1ZSA6IFt2YWx1
ZV0pIGFzIFRbXTtcbn1cblxuZnVuY3Rpb24gaXNQb2ludCh2YWx1ZTogdW5rbm93bik6IHZhbHVlIGlzIFBvaW50UmVjIHtcbiAg
cmV0dXJuIHR5cGVvZiB2YWx1ZSA9PT0gXCJvYmplY3RcIiAmJiB2YWx1ZSAhPT0gbnVsbCAmJiAhQXJyYXkuaXNBcnJheSh2YWx1
ZSk7XG59XG5cbi8qKiBBIHNpbmdsZSBkYXR1bSdzIG51bWVyaWMgdmFsdWUsIHdoaWNoZXZlciBvZiBFQ2hhcnRzJyBhY2NlcHRl
ZCBzaGFwZXMgaXQgdXNlcy4gKi9cbmZ1bmN0aW9uIHZhbHVlT2YoZGF0dW06IHVua25vd24pOiBudW1iZXIgfCBudWxsIHtcbiAg
aWYgKHR5cGVvZiBkYXR1bSA9PT0gXCJudW1iZXJcIikgcmV0dXJuIE51bWJlci5pc0Zpbml0ZShkYXR1bSkgPyBkYXR1bSA6IG51
bGw7XG4gIGlmICh0eXBlb2YgZGF0dW0gPT09IFwic3RyaW5nXCIpIHtcbiAgICBjb25zdCBwYXJzZWQgPSBOdW1iZXIoZGF0dW0p
O1xuICAgIHJldHVybiBOdW1iZXIuaXNGaW5pdGUocGFyc2VkKSA/IHBhcnNlZCA6IG51bGw7XG4gIH1cbiAgaWYgKEFycmF5Lmlz
QXJyYXkoZGF0dW0pKSB7XG4gICAgLy8gW2NhdGVnb3J5LCB2YWx1ZV0gcGFpcnMgXHUyMDE0IHRoZSB2YWx1ZSBpcyB0aGUgbGFz
dCBudW1lcmljIGVudHJ5LlxuICAgIHJldHVybiB2YWx1ZU9mKGRhdHVtW2RhdHVtLmxlbmd0aCAtIDFdKTtcbiAgfVxuICBpZiAo
aXNQb2ludChkYXR1bSkpIHJldHVybiB2YWx1ZU9mKGRhdHVtLnZhbHVlKTtcbiAgcmV0dXJuIG51bGw7XG59XG5cbi8qKiBBIGRh
dHVtJ3Mgb3duIGxhYmVsLCBmb3Igc2VyaWVzIHRoYXQgY2Fycnkgb25lIChwaWUsIGZ1bm5lbCwgc2NhdHRlciB3aXRoIG5hbWVz
KS4gKi9cbmZ1bmN0aW9uIGxhYmVsT2YoZGF0dW06IHVua25vd24pOiBzdHJpbmcgfCBudWxsIHtcbiAgaWYgKEFycmF5LmlzQXJy
YXkoZGF0dW0pICYmIGRhdHVtLmxlbmd0aCA+PSAyICYmIHR5cGVvZiBkYXR1bVswXSA9PT0gXCJzdHJpbmdcIikgcmV0dXJuIGRh
dHVtWzBdO1xuICBpZiAoaXNQb2ludChkYXR1bSkgJiYgdHlwZW9mIGRhdHVtLm5hbWUgPT09IFwic3RyaW5nXCIpIHJldHVybiBk
YXR1bS5uYW1lO1xuICByZXR1cm4gbnVsbDtcbn1cblxuLyoqXG4gKiBCdWlsZCBhIHRhYmxlIGZyb20gYW4gb3B0aW9uLCBvciBu
dWxsIHdoZW4gdGhlcmUgaXMgbm90aGluZyBzZW5zaWJsZSB0byBzaG93LlxuICpcbiAqIFR3byBsYXlvdXRzIGFyZSBwcm9kdWNl
ZCwgYmVjYXVzZSB0aGUgY2hhcnRzIGdlbnVpbmVseSBoYXZlIHR3byBzaGFwZXM6XG4gKlxuICogICAqIEEgY2F0ZWdvcnkgYXhp
cyAobGluZS9iYXIvYXJlYSk6IHJvd3MgYXJlIHRoZSBheGlzIGNhdGVnb3JpZXMsIG9uZSBjb2x1bW4gcGVyIHNlcmllcy5cbiAq
ICAgKiBObyBjYXRlZ29yeSBheGlzIChwaWUvZnVubmVsKTogcm93cyBjb21lIGZyb20gZWFjaCBkYXR1bSdzIG93biBuYW1lLlxu
ICovXG5leHBvcnQgZnVuY3Rpb24gb3B0aW9uVG9UYWJsZShvcHRpb246IEVDaGFydHNPcHRpb24pOiBDaGFydFRhYmxlIHwgbnVs
bCB7XG4gIGNvbnN0IHNlcmllcyA9IGFzQXJyYXk8U2VyaWVzUmVjPihvcHRpb24uc2VyaWVzKS5maWx0ZXIoKHMpID0+IHMuZGF0
YSAhPSBudWxsKTtcbiAgaWYgKHNlcmllcy5sZW5ndGggPT09IDApIHJldHVybiBudWxsO1xuXG4gIGNvbnN0IHhBeGVzID0gYXNB
cnJheTxBeGlzUmVjPihvcHRpb24ueEF4aXMpO1xuICBjb25zdCBjYXRlZ29yeUF4aXMgPSB4QXhlcy5maW5kKChhKSA9PiBBcnJh
eS5pc0FycmF5KGEuZGF0YSkgJiYgYS5kYXRhLmxlbmd0aCA+IDApO1xuICBjb25zdCBjYXRlZ29yaWVzID0gYXNBcnJheTx1bmtu
b3duPihjYXRlZ29yeUF4aXM/LmRhdGEpLm1hcCgoYykgPT4gU3RyaW5nKGMpKTtcblxuICBpZiAoY2F0ZWdvcmllcy5sZW5ndGgg
PiAwKSB7XG4gICAgY29uc3QgY29sdW1ucyA9IFtcIlwiLCAuLi5zZXJpZXMubWFwKChzLCBpKSA9PiBzLm5hbWUgPz8gYFNlcmll
cyAke2kgKyAxfWApXTtcbiAgICBjb25zdCByb3dzID0gY2F0ZWdvcmllcy5tYXAoKGNhdGVnb3J5LCByb3dJbmRleCkgPT4ge1xu
ICAgICAgY29uc3QgY2VsbHM6IChzdHJpbmcgfCBudW1iZXIgfCBudWxsKVtdID0gW2NhdGVnb3J5XTtcbiAgICAgIGZvciAoY29u
c3QgcyBvZiBzZXJpZXMpIGNlbGxzLnB1c2godmFsdWVPZihhc0FycmF5PHVua25vd24+KHMuZGF0YSlbcm93SW5kZXhdKSk7XG4g
ICAgICByZXR1cm4gY2VsbHM7XG4gICAgfSk7XG4gICAgLy8gQSB0YWJsZSB3aGVyZSBldmVyeSB2YWx1ZSBpcyBtaXNzaW5nIGlz
IG5vaXNlLCBub3QgYSBmYWxsYmFjay5cbiAgICByZXR1cm4gcm93cy5zb21lKChyKSA9PiByLnNsaWNlKDEpLnNvbWUoKHYpID0+
IHYgIT09IG51bGwpKSA/IHsgY29sdW1ucywgcm93cyB9IDogbnVsbDtcbiAgfVxuXG4gIC8vIE5vIGNhdGVnb3J5IGF4aXM6IHRo
ZSBsYWJlbHMgaGF2ZSB0byBjb21lIGZyb20gdGhlIGRhdGEgaXRzZWxmIChwaWUsIGZ1bm5lbCkuXG4gIGNvbnN0IGZpcnN0ID0g
c2VyaWVzWzBdO1xuICBjb25zdCBwb2ludHMgPSBhc0FycmF5PHVua25vd24+KGZpcnN0LmRhdGEpO1xuICBjb25zdCByb3dzOiAo
c3RyaW5nIHwgbnVtYmVyIHwgbnVsbClbXVtdID0gW107XG4gIGZvciAoY29uc3QgcG9pbnQgb2YgcG9pbnRzKSB7XG4gICAgY29u
c3QgbGFiZWwgPSBsYWJlbE9mKHBvaW50KTtcbiAgICBpZiAobGFiZWwgPT09IG51bGwpIHJldHVybiBudWxsOyAvLyB1bmxhYmVs
bGVkIHNjYXR0ZXIvaGVhdG1hcCBcdTIwMTQgbm8gdXNlZnVsIHRhYmxlXG4gICAgcm93cy5wdXNoKFtsYWJlbCwgdmFsdWVPZihw
b2ludCldKTtcbiAgfVxuICBpZiAocm93cy5sZW5ndGggPT09IDApIHJldHVybiBudWxsO1xuICByZXR1cm4geyBjb2x1bW5zOiBb
XCJcIiwgZmlyc3QubmFtZSA/PyBcIlZhbHVlXCJdLCByb3dzIH07XG59XG4iLCAiZnJvbnRlbmQvdGVzdHMvY2hhcnQtdGFibGUu
dGVzdC50cyI6ICJpbXBvcnQgeyBkZXNjcmliZSwgZXhwZWN0LCBpdCB9IGZyb20gXCJ2aXRlc3RcIjtcblxuaW1wb3J0IHsgb3B0
aW9uVG9UYWJsZSB9IGZyb20gXCJAL2xpYi9jaGFydC10YWJsZVwiO1xuaW1wb3J0IHR5cGUgeyBFQ2hhcnRzT3B0aW9uIH0gZnJv
bSBcIkAvbGliL2VjaGFydHNcIjtcblxuLyoqXG4gKiBDaGFydHMgYXJlIGNhbnZhc2VzOiB1bnJlYWRhYmxlIHRvIGEgc2NyZWVu
IHJlYWRlciwgdW5jb3B5YWJsZSwgdW5zZWFyY2hhYmxlLCBhbmQgb25cbiAqIHBhcGVyIGp1c3QgYSBwaWN0dXJlLiBUaGlzIGRl
cml2ZXMgdGhlIG51bWJlcnMgYmFjayBvdXQgb2YgdGhlIG9wdGlvbiB0aGUgY2hhcnQgYWxyZWFkeVxuICogcmVuZGVycyBcdTIw
MTQgc28gdGhlcmUgaXMgb25lIHNvdXJjZSwgbm90IGEgc2Vjb25kIG9uZSB0byBkcmlmdC5cbiAqXG4gKiBUaGUgY2FzZXMgYmVs
b3cgYXJlIHRoZSBvcHRpb24gc2hhcGVzIHRoZSBkYXNoYm9hcmQncyBjaGFydHMgYWN0dWFsbHkgYnVpbGQuXG4gKi9cblxuY29u
c3Qgb3B0aW9uID0gKHZhbHVlOiB1bmtub3duKTogRUNoYXJ0c09wdGlvbiA9PiB2YWx1ZSBhcyBFQ2hhcnRzT3B0aW9uO1xuXG5k
ZXNjcmliZShcIm9wdGlvblRvVGFibGVcIiwgKCkgPT4ge1xuICBpdChcInJlYWRzIGEgY2F0ZWdvcnkgYXhpcyB3aXRoIHNldmVy
YWwgc2VyaWVzXCIsICgpID0+IHtcbiAgICBjb25zdCB0YWJsZSA9IG9wdGlvblRvVGFibGUoXG4gICAgICBvcHRpb24oe1xuICAg
ICAgICB4QXhpczogeyB0eXBlOiBcImNhdGVnb3J5XCIsIGRhdGE6IFtcIk1vblwiLCBcIlR1ZVwiLCBcIldlZFwiXSB9LFxuICAg
ICAgICB5QXhpczogeyB0eXBlOiBcInZhbHVlXCIgfSxcbiAgICAgICAgc2VyaWVzOiBbXG4gICAgICAgICAgeyBuYW1lOiBcIlJl
dmVudWVcIiwgdHlwZTogXCJsaW5lXCIsIGRhdGE6IFsxMCwgMjAsIDMwXSB9LFxuICAgICAgICAgIHsgbmFtZTogXCJTcGVuZFwi
LCB0eXBlOiBcImJhclwiLCBkYXRhOiBbNCwgNSwgNl0gfSxcbiAgICAgICAgXSxcbiAgICAgIH0pLFxuICAgICk7XG5cbiAgICBl
eHBlY3QodGFibGUpLnRvRXF1YWwoe1xuICAgICAgY29sdW1uczogW1wiXCIsIFwiUmV2ZW51ZVwiLCBcIlNwZW5kXCJdLFxuICAg
ICAgcm93czogW1xuICAgICAgICBbXCJNb25cIiwgMTAsIDRdLFxuICAgICAgICBbXCJUdWVcIiwgMjAsIDVdLFxuICAgICAgICBb
XCJXZWRcIiwgMzAsIDZdLFxuICAgICAgXSxcbiAgICB9KTtcbiAgfSk7XG5cbiAgaXQoXCJuYW1lcyB1bm5hbWVkIHNlcmllcyBi
eSBwb3NpdGlvbiByYXRoZXIgdGhhbiBsZWF2aW5nIGEgYmxhbmsgaGVhZGVyXCIsICgpID0+IHtcbiAgICBjb25zdCB0YWJsZSA9
IG9wdGlvblRvVGFibGUoXG4gICAgICBvcHRpb24oe1xuICAgICAgICB4QXhpczogeyBkYXRhOiBbXCJhXCIsIFwiYlwiXSB9LFxu
ICAgICAgICBzZXJpZXM6IFt7IHR5cGU6IFwiYmFyXCIsIGRhdGE6IFsxLCAyXSB9XSxcbiAgICAgIH0pLFxuICAgICk7XG4gICAg
ZXhwZWN0KHRhYmxlPy5jb2x1bW5zKS50b0VxdWFsKFtcIlwiLCBcIlNlcmllcyAxXCJdKTtcbiAgfSk7XG5cbiAgaXQoXCJwYWRz
IGEgc2VyaWVzIHNob3J0ZXIgdGhhbiB0aGUgYXhpcyBpbnN0ZWFkIG9mIHNoaWZ0aW5nIHJvd3MgdXBcIiwgKCkgPT4ge1xuICAg
IC8vIEEgZ2FwIGluIG9uZSBzZXJpZXMgbXVzdCBzdGF5IGEgZ2FwIG9uIHRoZSByb3cgaXQgYmVsb25ncyB0byBcdTIwMTQgb3Ro
ZXJ3aXNlIHRoZVxuICAgIC8vIHRhYmxlIHF1aWV0bHkgc2F5cyBXZWRuZXNkYXkncyBudW1iZXIgaGFwcGVuZWQgb24gVHVlc2Rh
eS5cbiAgICBjb25zdCB0YWJsZSA9IG9wdGlvblRvVGFibGUoXG4gICAgICBvcHRpb24oe1xuICAgICAgICB4QXhpczogeyBkYXRh
OiBbXCJNb25cIiwgXCJUdWVcIiwgXCJXZWRcIl0gfSxcbiAgICAgICAgc2VyaWVzOiBbeyBuYW1lOiBcIkluc3RhbGxzXCIsIHR5
cGU6IFwibGluZVwiLCBkYXRhOiBbN10gfV0sXG4gICAgICB9KSxcbiAgICApO1xuICAgIGV4cGVjdCh0YWJsZT8ucm93cykudG9F
cXVhbChbXG4gICAgICBbXCJNb25cIiwgN10sXG4gICAgICBbXCJUdWVcIiwgbnVsbF0sXG4gICAgICBbXCJXZWRcIiwgbnVsbF0s
XG4gICAgXSk7XG4gIH0pO1xuXG4gIGl0KFwicmVhZHMge25hbWUsIHZhbHVlfSBwb2ludHMgYW5kIFtjYXRlZ29yeSwgdmFsdWVd
IHBhaXJzXCIsICgpID0+IHtcbiAgICBleHBlY3QoXG4gICAgICBvcHRpb25Ub1RhYmxlKFxuICAgICAgICBvcHRpb24oe1xuICAg
ICAgICAgIHhBeGlzOiB7IGRhdGE6IFtcInhcIiwgXCJ5XCJdIH0sXG4gICAgICAgICAgc2VyaWVzOiBbeyBuYW1lOiBcIlNcIiwg
ZGF0YTogW3sgdmFsdWU6IDMgfSwgW1wieVwiLCA5XV0gfV0sXG4gICAgICAgIH0pLFxuICAgICAgKT8ucm93cyxcbiAgICApLnRv
RXF1YWwoW1xuICAgICAgW1wieFwiLCAzXSxcbiAgICAgIFtcInlcIiwgOV0sXG4gICAgXSk7XG4gIH0pO1xuXG4gIGl0KFwibGFi
ZWxzIGEgcGllIGZyb20gaXRzIG93biBkYXRhLCBzaW5jZSB0aGVyZSBpcyBubyBheGlzIHRvIGxhYmVsIGZyb21cIiwgKCkgPT4g
e1xuICAgIGNvbnN0IHRhYmxlID0gb3B0aW9uVG9UYWJsZShcbiAgICAgIG9wdGlvbih7XG4gICAgICAgIHNlcmllczogW1xuICAg
ICAgICAgIHtcbiAgICAgICAgICAgIG5hbWU6IFwiUmV2ZW51ZSBieSBwbGF0Zm9ybVwiLFxuICAgICAgICAgICAgdHlwZTogXCJw
aWVcIixcbiAgICAgICAgICAgIGRhdGE6IFtcbiAgICAgICAgICAgICAgeyBuYW1lOiBcImlPU1wiLCB2YWx1ZTogNzAwIH0sXG4g
ICAgICAgICAgICAgIHsgbmFtZTogXCJBbmRyb2lkXCIsIHZhbHVlOiAzMDAgfSxcbiAgICAgICAgICAgIF0sXG4gICAgICAgICAg
fSxcbiAgICAgICAgXSxcbiAgICAgIH0pLFxuICAgICk7XG5cbiAgICBleHBlY3QodGFibGUpLnRvRXF1YWwoe1xuICAgICAgY29s
dW1uczogW1wiXCIsIFwiUmV2ZW51ZSBieSBwbGF0Zm9ybVwiXSxcbiAgICAgIHJvd3M6IFtcbiAgICAgICAgW1wiaU9TXCIsIDcw
MF0sXG4gICAgICAgIFtcIkFuZHJvaWRcIiwgMzAwXSxcbiAgICAgIF0sXG4gICAgfSk7XG4gIH0pO1xuXG4gIGl0KFwicmV0dXJu
cyBudWxsIHdoZW4gdGhlcmUgaXMgbm90aGluZyB3b3J0aCBzaG93aW5nXCIsICgpID0+IHtcbiAgICAvLyBObyBzZXJpZXMgYXQg
YWxsLlxuICAgIGV4cGVjdChvcHRpb25Ub1RhYmxlKG9wdGlvbih7IHhBeGlzOiB7IGRhdGE6IFtcImFcIl0gfSB9KSkpLnRvQmVO
dWxsKCk7XG4gICAgLy8gQSBjYXRlZ29yeSBheGlzIGJ1dCBldmVyeSB2YWx1ZSBtaXNzaW5nIFx1MjAxNCBhbiBlbXB0eSBncmlk
IGhlbHBzIG5vYm9keS5cbiAgICBleHBlY3QoXG4gICAgICBvcHRpb25Ub1RhYmxlKFxuICAgICAgICBvcHRpb24oeyB4QXhpczog
eyBkYXRhOiBbXCJhXCIsIFwiYlwiXSB9LCBzZXJpZXM6IFt7IG5hbWU6IFwiU1wiLCBkYXRhOiBbbnVsbCwgdW5kZWZpbmVkXSB9
XSB9KSxcbiAgICAgICksXG4gICAgKS50b0JlTnVsbCgpO1xuICAgIC8vIFVubGFiZWxsZWQgc2NhdHRlcjogcm93cyB3aXRoIG5v
IG1lYW5pbmcgdG8gcHV0IGluIHRoZSBmaXJzdCBjb2x1bW4uXG4gICAgZXhwZWN0KFxuICAgICAgb3B0aW9uVG9UYWJsZShcbiAg
ICAgICAgb3B0aW9uKHtcbiAgICAgICAgICBzZXJpZXM6IFt7IHR5cGU6IFwic2NhdHRlclwiLCBkYXRhOiBbWzEsIDJdLCBbMywg
NF1dIH1dLFxuICAgICAgICB9KSxcbiAgICAgICksXG4gICAgKS50b0JlTnVsbCgpO1xuICB9KTtcblxuICBpdChcInRyZWF0cyBh
IG5vbi1maW5pdGUgdmFsdWUgYXMgbWlzc2luZyByYXRoZXIgdGhhbiBwcmludGluZyBOYU5cIiwgKCkgPT4ge1xuICAgIGNvbnN0
IHRhYmxlID0gb3B0aW9uVG9UYWJsZShcbiAgICAgIG9wdGlvbih7IHhBeGlzOiB7IGRhdGE6IFtcImFcIl0gfSwgc2VyaWVzOiBb
eyBuYW1lOiBcIlNcIiwgZGF0YTogWzFdIH0sIHsgbmFtZTogXCJUXCIsIGRhdGE6IFtOYU5dIH1dIH0pLFxuICAgICk7XG4gICAg
ZXhwZWN0KHRhYmxlPy5yb3dzKS50b0VxdWFsKFtbXCJhXCIsIDEsIG51bGxdXSk7XG4gIH0pO1xufSk7XG4ifSwgImFwcGVuZHMi
OiBbXSwgImVkaXRzIjogW3sicGF0aCI6ICJmcm9udGVuZC9jb21wb25lbnRzL2ZpbHRlcnMvbXVsdGktc2VsZWN0LnRzeCIsICJh
bmNob3IiOiAiICBjb25zdCBzdW1tYXJ5ID1cbiAgICBzZWxlY3RlZC5sZW5ndGggPT09IDAgPyBgQWxsICR7bGFiZWwudG9Mb3dl
ckNhc2UoKX1gIDogYCR7c2VsZWN0ZWQubGVuZ3RofSBzZWxlY3RlZGA7IiwgInJlcGxhY2VtZW50IjogIiAgLy8gTmFtZSB0aGUg
ZmlsdGVyIHdoZW5ldmVyIGl0IGlzIG5hcnJvd2luZyBzb21ldGhpbmcuIFwiMiBzZWxlY3RlZFwiIHdhcyBmaW5lIHdoZW4gdGhl
XG4gIC8vIGxhYmVsIHNhdCBiZXNpZGUgaXQ7IHdpdGggc2V2ZXJhbCBvZiB0aGVzZSBpbiBhIHJvdyBpdCBzYXlzIHdoaWNoIGNv
dW50LCBub3Qgd2hpY2hcbiAgLy8gZmlsdGVyIC0gYW5kIGEgZmlsdGVyIHlvdSBjYW5ub3QgaWRlbnRpZnkgaXMgb25lIHlvdSBj
YW5ub3QgdW5kby5cbiAgY29uc3Qgc3VtbWFyeSA9XG4gICAgc2VsZWN0ZWQubGVuZ3RoID09PSAwID8gYEFsbCAke2xhYmVsLnRv
TG93ZXJDYXNlKCl9YCA6IGAke2xhYmVsfTogJHtzZWxlY3RlZC5sZW5ndGh9YDsiLCAibWFya2VyIjogImAke2xhYmVsfTogJHtz
ZWxlY3RlZC5sZW5ndGh9YCIsICJjb3VudCI6ICJvbmUifSwgeyJwYXRoIjogImZyb250ZW5kL2NvbXBvbmVudHMvbGF5b3V0L2Nv
bW1hbmQtcGFsZXR0ZS50c3giLCAiYW5jaG9yIjogImltcG9ydCB7IEhlbHBDaXJjbGUsIHR5cGUgTHVjaWRlSWNvbiwgU2VhcmNo
IH0gZnJvbSBcImx1Y2lkZS1yZWFjdFwiOyIsICJyZXBsYWNlbWVudCI6ICJpbXBvcnQgeyBIZWxwQ2lyY2xlLCB0eXBlIEx1Y2lk
ZUljb24sIFNlYXJjaCwgU21hcnRwaG9uZSB9IGZyb20gXCJsdWNpZGUtcmVhY3RcIjsiLCAibWFya2VyIjogIlNlYXJjaCwgU21h
cnRwaG9uZSB9IiwgImNvdW50IjogIm9uZSJ9LCB7InBhdGgiOiAiZnJvbnRlbmQvY29tcG9uZW50cy9sYXlvdXQvY29tbWFuZC1w
YWxldHRlLnRzeCIsICJhbmNob3IiOiAiaW1wb3J0IHsgdXNlTWUgfSBmcm9tIFwiQC9saWIvYXBpLWhvb2tzXCI7IiwgInJlcGxh
Y2VtZW50IjogImltcG9ydCB7IHVzZUFwcHMsIHVzZU1lIH0gZnJvbSBcIkAvbGliL2FwaS1ob29rc1wiOyIsICJtYXJrZXIiOiAi
dXNlQXBwcywgdXNlTWUiLCAiY291bnQiOiAib25lIn0sIHsicGF0aCI6ICJmcm9udGVuZC9jb21wb25lbnRzL2xheW91dC9jb21t
YW5kLXBhbGV0dGUudHN4IiwgImFuY2hvciI6ICIvKiogR2xvYmFsIGNvbW1hbmQgcGFsZXR0ZSIsICJyZXBsYWNlbWVudCI6ICIv
KiogSG93IG1hbnkgYXBwIHJlc3VsdHMgdGhlIHBhbGV0dGUgd2lsbCBvZmZlciBhdCBvbmNlLlxuICpcbiAqICBUaGVyZSBhcmUg
aHVuZHJlZHMgb2YgYXBwcy4gU2hvd2luZyBhbGwgb2YgdGhlbSB0dXJucyBhIGtleWJvYXJkIHNob3J0Y3V0IGludG8gYVxuICog
IHNjcm9sbCwgc28gdGhlIHBhbGV0dGUgb2ZmZXJzIHRoZSBjbG9zZXN0IGZldyBhbmQgdGhlIEFwcHMgcGFnZSBoYW5kbGVzIHRo
ZSByZXN0LiAqL1xuY29uc3QgQVBQX1JFU1VMVF9MSU1JVCA9IDg7XG5cbi8qKiBBcHBzIG9ubHkgYXBwZWFyIG9uY2UgdGhpcyBt
YW55IGNoYXJhY3RlcnMgYXJlIHR5cGVkIFx1MjAxNCBzZWUgYXBwTWF0Y2hlcyBiZWxvdy4gKi9cbmNvbnN0IEFQUF9TRUFSQ0hf
TUlOX0NIQVJTID0gMjtcblxuLyoqIEdsb2JhbCBjb21tYW5kIHBhbGV0dGUiLCAibWFya2VyIjogImNvbnN0IEFQUF9SRVNVTFRf
TElNSVQiLCAiY291bnQiOiAib25lIn0sIHsicGF0aCI6ICJmcm9udGVuZC9jb21wb25lbnRzL2xheW91dC9jb21tYW5kLXBhbGV0
dGUudHN4IiwgImFuY2hvciI6ICIgIGNvbnN0IHsgZGF0YTogbWUgfSA9IHVzZU1lKCk7IiwgInJlcGxhY2VtZW50IjogIiAgY29u
c3QgeyBkYXRhOiBtZSB9ID0gdXNlTWUoKTtcbiAgY29uc3QgeyBkYXRhOiBhcHBzRGF0YSB9ID0gdXNlQXBwcygpOyIsICJtYXJr
ZXIiOiAiY29uc3QgeyBkYXRhOiBhcHBzRGF0YSB9ID0gdXNlQXBwcygpOyIsICJjb3VudCI6ICJvbmUifSwgeyJwYXRoIjogImZy
b250ZW5kL2NvbXBvbmVudHMvbGF5b3V0L2NvbW1hbmQtcGFsZXR0ZS50c3giLCAiYW5jaG9yIjogIiAgY29uc3QgZmlsdGVyZWQg
PSB1c2VNZW1vKCgpID0+IHtcbiAgICBjb25zdCBxID0gcXVlcnkudHJpbSgpLnRvTG93ZXJDYXNlKCk7XG4gICAgaWYgKCFxKSBy
ZXR1cm4gY29tbWFuZHM7XG4gICAgcmV0dXJuIGNvbW1hbmRzLmZpbHRlcigoYykgPT4gYy5sYWJlbC50b0xvd2VyQ2FzZSgpLmlu
Y2x1ZGVzKHEpKTtcbiAgfSwgW2NvbW1hbmRzLCBxdWVyeV0pOyIsICJyZXBsYWNlbWVudCI6ICIgIC8qKiBBcHBzLCBtYXRjaGVk
IGJ5IG5hbWUgb3Iga2V5LlxuICAgKlxuICAgKiAgRGVsaWJlcmF0ZWx5IGVtcHR5IHVudGlsIHRoZSB1c2VyIHR5cGVzOiB0aGVy
ZSBhcmUgaHVuZHJlZHMgb2YgYXBwcywgYW5kIGxpc3RpbmdcbiAgICogIHRoZW0gYnkgZGVmYXVsdCB3b3VsZCBidXJ5IHRoZSBz
aXggcGFnZXMgdGhpcyBwYWxldHRlIGV4aXN0cyB0byByZWFjaC4gVHlwaW5nIHR3b1xuICAgKiAgY2hhcmFjdGVycyBpcyB0aGUg
c2lnbmFsIHRoYXQgc29tZW9uZSBpcyBsb29raW5nIGZvciBhIHNwZWNpZmljIGFwcCByYXRoZXIgdGhhblxuICAgKiAgbmF2aWdh
dGluZy4gKi9cbiAgY29uc3QgYXBwTWF0Y2hlcyA9IHVzZU1lbW88Q29tbWFuZFtdPigoKSA9PiB7XG4gICAgY29uc3QgcSA9IHF1
ZXJ5LnRyaW0oKS50b0xvd2VyQ2FzZSgpO1xuICAgIGlmIChxLmxlbmd0aCA8IEFQUF9TRUFSQ0hfTUlOX0NIQVJTKSByZXR1cm4g
W107XG4gICAgcmV0dXJuIChhcHBzRGF0YT8uYXBwcyA/PyBbXSlcbiAgICAgIC5maWx0ZXIoKGFwcCkgPT4ge1xuICAgICAgICBj
b25zdCBuYW1lID0gKGFwcC5hcHBfbmFtZSA/PyBcIlwiKS50b0xvd2VyQ2FzZSgpO1xuICAgICAgICByZXR1cm4gbmFtZS5pbmNs
dWRlcyhxKSB8fCBhcHAuY2Fub25pY2FsX2tleS50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKHEpO1xuICAgICAgfSlcbiAgICAgIC5z
bGljZSgwLCBBUFBfUkVTVUxUX0xJTUlUKVxuICAgICAgLm1hcCgoYXBwKSA9PiAoe1xuICAgICAgICBpZDogYGFwcDoke2FwcC5j
YW5vbmljYWxfa2V5fWAsXG4gICAgICAgIGxhYmVsOiBhcHAuYXBwX25hbWUgPz8gYXBwLmNhbm9uaWNhbF9rZXksXG4gICAgICAg
IGhpbnQ6IGFwcC5wdWJsaXNoZXIgPz8gXCJBcHBcIixcbiAgICAgICAgaWNvbjogU21hcnRwaG9uZSxcbiAgICAgICAgcnVuOiAo
KSA9PiByb3V0ZXIucHVzaChgL2FwcHMvJHtlbmNvZGVVUklDb21wb25lbnQoYXBwLmNhbm9uaWNhbF9rZXkpfWApLFxuICAgICAg
fSkpO1xuICB9LCBbYXBwc0RhdGEsIHF1ZXJ5LCByb3V0ZXJdKTtcblxuICBjb25zdCBmaWx0ZXJlZCA9IHVzZU1lbW8oKCkgPT4g
e1xuICAgIGNvbnN0IHEgPSBxdWVyeS50cmltKCkudG9Mb3dlckNhc2UoKTtcbiAgICBjb25zdCBwYWdlcyA9IHEgPyBjb21tYW5k
cy5maWx0ZXIoKGMpID0+IGMubGFiZWwudG9Mb3dlckNhc2UoKS5pbmNsdWRlcyhxKSkgOiBjb21tYW5kcztcbiAgICByZXR1cm4g
Wy4uLnBhZ2VzLCAuLi5hcHBNYXRjaGVzXTtcbiAgfSwgW2FwcE1hdGNoZXMsIGNvbW1hbmRzLCBxdWVyeV0pOyIsICJtYXJrZXIi
OiAiY29uc3QgYXBwTWF0Y2hlcyA9IHVzZU1lbW88Q29tbWFuZFtdPiIsICJjb3VudCI6ICJvbmUifSwgeyJwYXRoIjogImZyb250
ZW5kL2NvbXBvbmVudHMvY2hhcnRzL2NoYXJ0LnRzeCIsICJhbmNob3IiOiAiaW1wb3J0IGR5bmFtaWMgZnJvbSBcIm5leHQvZHlu
YW1pY1wiOyIsICJyZXBsYWNlbWVudCI6ICJpbXBvcnQgeyBCYXJDaGFydDMsIFRhYmxlMiB9IGZyb20gXCJsdWNpZGUtcmVhY3Rc
IjtcbmltcG9ydCBkeW5hbWljIGZyb20gXCJuZXh0L2R5bmFtaWNcIjsiLCAibWFya2VyIjogImltcG9ydCB7IEJhckNoYXJ0Mywg
VGFibGUyIH0gZnJvbSBcImx1Y2lkZS1yZWFjdFwiOyIsICJjb3VudCI6ICJvbmUifSwgeyJwYXRoIjogImZyb250ZW5kL2NvbXBv
bmVudHMvY2hhcnRzL2NoYXJ0LnRzeCIsICJhbmNob3IiOiAiaW1wb3J0IHR5cGUgeyBFQ2hhcnRzT3B0aW9uIH0gZnJvbSBcIkAv
bGliL2VjaGFydHNcIjsiLCAicmVwbGFjZW1lbnQiOiAiaW1wb3J0IHsgb3B0aW9uVG9UYWJsZSB9IGZyb20gXCJAL2xpYi9jaGFy
dC10YWJsZVwiO1xuaW1wb3J0IHR5cGUgeyBFQ2hhcnRzT3B0aW9uIH0gZnJvbSBcIkAvbGliL2VjaGFydHNcIjsiLCAibWFya2Vy
IjogImltcG9ydCB7IG9wdGlvblRvVGFibGUgfSBmcm9tIFwiQC9saWIvY2hhcnQtdGFibGVcIjsiLCAiY291bnQiOiAib25lIn0s
IHsicGF0aCI6ICJmcm9udGVuZC9jb21wb25lbnRzL2NoYXJ0cy9jaGFydC50c3giLCAiYW5jaG9yIjogIiAgY29uc3QgW2hlaWdo
dE92ZXJyaWRlLCBzZXRIZWlnaHRPdmVycmlkZV0gPSB1c2VTdGF0ZTxudW1iZXIgfCBudWxsPihudWxsKTsiLCAicmVwbGFjZW1l
bnQiOiAiICBjb25zdCBbc2hvd1RhYmxlLCBzZXRTaG93VGFibGVdID0gdXNlU3RhdGUoZmFsc2UpO1xuICBjb25zdCBbaGVpZ2h0
T3ZlcnJpZGUsIHNldEhlaWdodE92ZXJyaWRlXSA9IHVzZVN0YXRlPG51bWJlciB8IG51bGw+KG51bGwpOyIsICJtYXJrZXIiOiAi
Y29uc3QgW3Nob3dUYWJsZSwgc2V0U2hvd1RhYmxlXSA9IHVzZVN0YXRlKGZhbHNlKTsiLCAiY291bnQiOiAib25lIn0sIHsicGF0
aCI6ICJmcm9udGVuZC9jb21wb25lbnRzL2NoYXJ0cy9jaGFydC50c3giLCAiYW5jaG9yIjogIiAgY29uc3QgZWZmZWN0aXZlSGVp
Z2h0ID0gaGVpZ2h0T3ZlcnJpZGUgPz8gaGVpZ2h0OyIsICJyZXBsYWNlbWVudCI6ICIgIC8vIFRoZSBzYW1lIG9wdGlvbiB0aGUg
Y2FudmFzIHJlbmRlcnMsIHJlYWQgYmFjayBhcyByb3dzLiBPbmUgc291cmNlLCBzbyB0aGUgdGFibGUgY2FuXG4gIC8vIG5ldmVy
IGRpc2FncmVlIHdpdGggdGhlIHBpY3R1cmUgYWJvdmUgaXQuXG4gIGNvbnN0IHRhYmxlID0gdXNlTWVtbygoKSA9PiBvcHRpb25U
b1RhYmxlKGVmZmVjdGl2ZU9wdGlvbiksIFtlZmZlY3RpdmVPcHRpb25dKTtcblxuICBjb25zdCBlZmZlY3RpdmVIZWlnaHQgPSBo
ZWlnaHRPdmVycmlkZSA/PyBoZWlnaHQ7IiwgIm1hcmtlciI6ICJjb25zdCB0YWJsZSA9IHVzZU1lbW8oKCkgPT4gb3B0aW9uVG9U
YWJsZShlZmZlY3RpdmVPcHRpb24pIiwgImNvdW50IjogIm9uZSJ9LCB7InBhdGgiOiAiZnJvbnRlbmQvY29tcG9uZW50cy9jaGFy
dHMvY2hhcnQudHN4IiwgImFuY2hvciI6ICIgIGNvbnN0IHNob3dDb250cm9scyA9XG4gICAgY2FuQWRqdXN0ICYmIiwgInJlcGxh
Y2VtZW50IjogIiAgLy8gQSBjYW52YXMgY2Fubm90IGJlIHJlYWQgYWxvdWQsIGNvcGllZCwgb3Igc2VhcmNoZWQuIE9mZmVyIHRo
ZSBudW1iZXJzIHdoZXJldmVyIHRoZVxuICAvLyBvcHRpb24geWllbGRzIGEgdGFibGUgdGhhdCBtZWFucyBzb21ldGhpbmcgLSB3
aGljaCBvcHRpb25Ub1RhYmxlIGRlY2lkZXMsIG5vdCB0aGlzLlxuICBjb25zdCBzaG93VGFibGVUb2dnbGUgPSBjYW5BZGp1c3Qg
JiYgIWxvYWRpbmcgJiYgIWVycm9yICYmICFpc0VtcHR5ICYmIHRhYmxlICE9PSBudWxsO1xuICBjb25zdCBzaG93Q29udHJvbHMg
PVxuICAgIGNhbkFkanVzdCAmJiIsICJtYXJrZXIiOiAiY29uc3Qgc2hvd1RhYmxlVG9nZ2xlID0iLCAiY291bnQiOiAib25lIn0s
IHsicGF0aCI6ICJmcm9udGVuZC9jb21wb25lbnRzL2NoYXJ0cy9jaGFydC50c3giLCAiYW5jaG9yIjogIiAgfSBlbHNlIHtcbiAg
ICBib2R5ID0gPENoYXJ0Q2FudmFzIG9wdGlvbj17ZWZmZWN0aXZlT3B0aW9ufSBvbkV2ZW50cz17b25FdmVudHN9IC8+O1xuICB9
IiwgInJlcGxhY2VtZW50IjogIiAgfSBlbHNlIGlmIChzaG93VGFibGUgJiYgdGFibGUpIHtcbiAgICBib2R5ID0gKFxuICAgICAg
PGRpdiBjbGFzc05hbWU9XCJoLWZ1bGwgdy1mdWxsIG92ZXJmbG93LWF1dG8gcm91bmRlZC1tZCBib3JkZXJcIj5cbiAgICAgICAg
PHRhYmxlIGNsYXNzTmFtZT1cInctZnVsbCB0ZXh0LXNtXCI+XG4gICAgICAgICAgPHRoZWFkIGNsYXNzTmFtZT1cInN0aWNreSB0
b3AtMCBiZy1tdXRlZC85MCB0ZXh0LWxlZnQgdGV4dC14cyB1cHBlcmNhc2UgdHJhY2tpbmctd2lkZXIgdGV4dC1tdXRlZC1mb3Jl
Z3JvdW5kIGJhY2tkcm9wLWJsdXJcIj5cbiAgICAgICAgICAgIDx0cj5cbiAgICAgICAgICAgICAge3RhYmxlLmNvbHVtbnMubWFw
KChjb2x1bW4sIGluZGV4KSA9PiAoXG4gICAgICAgICAgICAgICAgPHRoXG4gICAgICAgICAgICAgICAgICBrZXk9e2luZGV4fVxu
ICAgICAgICAgICAgICAgICAgc2NvcGU9XCJjb2xcIlxuICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPXtjbihcInB4LTMgcHkt
MlwiLCBpbmRleCA+IDAgJiYgXCJ0ZXh0LXJpZ2h0XCIpfVxuICAgICAgICAgICAgICAgID5cbiAgICAgICAgICAgICAgICAgIHtj
b2x1bW59XG4gICAgICAgICAgICAgICAgPC90aD5cbiAgICAgICAgICAgICAgKSl9XG4gICAgICAgICAgICA8L3RyPlxuICAgICAg
ICAgIDwvdGhlYWQ+XG4gICAgICAgICAgPHRib2R5PlxuICAgICAgICAgICAge3RhYmxlLnJvd3MubWFwKChyb3csIHJvd0luZGV4
KSA9PiAoXG4gICAgICAgICAgICAgIDx0ciBrZXk9e3Jvd0luZGV4fSBjbGFzc05hbWU9XCJib3JkZXItdFwiPlxuICAgICAgICAg
ICAgICAgIHtyb3cubWFwKChjZWxsLCBjZWxsSW5kZXgpID0+IChcbiAgICAgICAgICAgICAgICAgIDx0ZFxuICAgICAgICAgICAg
ICAgICAgICBrZXk9e2NlbGxJbmRleH1cbiAgICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPXtjbihcbiAgICAgICAgICAgICAg
ICAgICAgICBcInB4LTMgcHktMS41XCIsXG4gICAgICAgICAgICAgICAgICAgICAgY2VsbEluZGV4ID4gMCAmJiBcInRleHQtcmln
aHQgdGFidWxhci1udW1zXCIsXG4gICAgICAgICAgICAgICAgICAgICAgY2VsbCA9PT0gbnVsbCAmJiBcInRleHQtbXV0ZWQtZm9y
ZWdyb3VuZFwiLFxuICAgICAgICAgICAgICAgICAgICApfVxuICAgICAgICAgICAgICAgICAgPlxuICAgICAgICAgICAgICAgICAg
ICB7Y2VsbCA9PT0gbnVsbCA/IFwiXHUyMDE0XCIgOiBjZWxsfVxuICAgICAgICAgICAgICAgICAgPC90ZD5cbiAgICAgICAgICAg
ICAgICApKX1cbiAgICAgICAgICAgICAgPC90cj5cbiAgICAgICAgICAgICkpfVxuICAgICAgICAgIDwvdGJvZHk+XG4gICAgICAg
IDwvdGFibGU+XG4gICAgICA8L2Rpdj5cbiAgICApO1xuICB9IGVsc2Uge1xuICAgIGJvZHkgPSA8Q2hhcnRDYW52YXMgb3B0aW9u
PXtlZmZlY3RpdmVPcHRpb259IG9uRXZlbnRzPXtvbkV2ZW50c30gLz47XG4gIH0iLCAibWFya2VyIjogIn0gZWxzZSBpZiAoc2hv
d1RhYmxlICYmIHRhYmxlKSB7IiwgImNvdW50IjogIm9uZSJ9LCB7InBhdGgiOiAiZnJvbnRlbmQvY29tcG9uZW50cy9jaGFydHMv
Y2hhcnQudHN4IiwgImFuY2hvciI6ICIgICAgICB7c2hvd0NvbnRyb2xzICYmIChcbiAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJw
b2ludGVyLWV2ZW50cy1ub25lIGFic29sdXRlIHJpZ2h0LTEgdG9wLTEgei0xMCBvcGFjaXR5LTAgdHJhbnNpdGlvbi1vcGFjaXR5
IGZvY3VzLXdpdGhpbjpwb2ludGVyLWV2ZW50cy1hdXRvIGZvY3VzLXdpdGhpbjpvcGFjaXR5LTEwMCBncm91cC1ob3Zlcjpwb2lu
dGVyLWV2ZW50cy1hdXRvIGdyb3VwLWhvdmVyOm9wYWNpdHktMTAwXCI+XG4gICAgICAgICAgPENoYXJ0Q29udHJvbHNcbiAgICAg
ICAgICAgIGNhcGFiaWxpdGllcz17Y2FwYWJpbGl0aWVzfVxuICAgICAgICAgICAgYWRqdXN0bWVudHM9e2FkanVzdG1lbnRzfVxu
ICAgICAgICAgICAgb25DaGFuZ2U9e3NldEFkanVzdG1lbnRzfVxuICAgICAgICAgIC8+XG4gICAgICAgIDwvZGl2PlxuICAgICAg
KX0iLCAicmVwbGFjZW1lbnQiOiAiICAgICAgeyhzaG93Q29udHJvbHMgfHwgc2hvd1RhYmxlVG9nZ2xlKSAmJiAoXG4gICAgICAg
IDxkaXYgY2xhc3NOYW1lPVwicG9pbnRlci1ldmVudHMtbm9uZSBhYnNvbHV0ZSByaWdodC0xIHRvcC0xIHotMTAgZmxleCBpdGVt
cy1zdGFydCBnYXAtMSBvcGFjaXR5LTAgdHJhbnNpdGlvbi1vcGFjaXR5IGZvY3VzLXdpdGhpbjpwb2ludGVyLWV2ZW50cy1hdXRv
IGZvY3VzLXdpdGhpbjpvcGFjaXR5LTEwMCBncm91cC1ob3Zlcjpwb2ludGVyLWV2ZW50cy1hdXRvIGdyb3VwLWhvdmVyOm9wYWNp
dHktMTAwXCI+XG4gICAgICAgICAge3Nob3dUYWJsZVRvZ2dsZSAmJiAoXG4gICAgICAgICAgICA8YnV0dG9uXG4gICAgICAgICAg
ICAgIHR5cGU9XCJidXR0b25cIlxuICAgICAgICAgICAgICBvbkNsaWNrPXsoKSA9PiBzZXRTaG93VGFibGUoKHNob3duKSA9PiAh
c2hvd24pfVxuICAgICAgICAgICAgICBhcmlhLXByZXNzZWQ9e3Nob3dUYWJsZX1cbiAgICAgICAgICAgICAgdGl0bGU9e3Nob3dU
YWJsZSA/IFwiU2hvdyB0aGUgY2hhcnRcIiA6IFwiU2hvdyB0aGUgbnVtYmVyc1wifVxuICAgICAgICAgICAgICBjbGFzc05hbWU9
XCJyb3VuZGVkLW1kIGJvcmRlciBiZy1jYXJkIHAtMS41IHRleHQtbXV0ZWQtZm9yZWdyb3VuZCBzaGFkb3ctc20gaG92ZXI6dGV4
dC1mb3JlZ3JvdW5kXCJcbiAgICAgICAgICAgID5cbiAgICAgICAgICAgICAge3Nob3dUYWJsZSA/IChcbiAgICAgICAgICAgICAg
ICA8QmFyQ2hhcnQzIGNsYXNzTmFtZT1cImgtNCB3LTRcIiBhcmlhLWhpZGRlbiAvPlxuICAgICAgICAgICAgICApIDogKFxuICAg
ICAgICAgICAgICAgIDxUYWJsZTIgY2xhc3NOYW1lPVwiaC00IHctNFwiIGFyaWEtaGlkZGVuIC8+XG4gICAgICAgICAgICAgICl9
XG4gICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT1cInNyLW9ubHlcIj5cbiAgICAgICAgICAgICAgICB7c2hvd1RhYmxlID8g
XCJTaG93IHRoZSBjaGFydFwiIDogXCJTaG93IHRoZSBjaGFydCBkYXRhIGFzIGEgdGFibGVcIn1cbiAgICAgICAgICAgICAgPC9z
cGFuPlxuICAgICAgICAgICAgPC9idXR0b24+XG4gICAgICAgICAgKX1cbiAgICAgICAgICB7c2hvd0NvbnRyb2xzICYmIChcbiAg
ICAgICAgICAgIDxDaGFydENvbnRyb2xzXG4gICAgICAgICAgICAgIGNhcGFiaWxpdGllcz17Y2FwYWJpbGl0aWVzfVxuICAgICAg
ICAgICAgICBhZGp1c3RtZW50cz17YWRqdXN0bWVudHN9XG4gICAgICAgICAgICAgIG9uQ2hhbmdlPXtzZXRBZGp1c3RtZW50c31c
biAgICAgICAgICAgIC8+XG4gICAgICAgICAgKX1cbiAgICAgICAgPC9kaXY+XG4gICAgICApfSIsICJtYXJrZXIiOiAieyhzaG93
Q29udHJvbHMgfHwgc2hvd1RhYmxlVG9nZ2xlKSAmJiAoIiwgImNvdW50IjogIm9uZSJ9XSwgInJlcGxhY2VtZW50cyI6IFtdfQ==
"""

# A guarded replacement prints the file it found so it can be re-anchored without a
# second round-trip. Cap it so a surprise never floods the terminal.
MAX_ECHO_LINES = 400


def main() -> int:
    if not Path("frontend/app").is_dir():
        print("ABORTED: run this from the repository root")
        return 1

    data = json.loads(base64.b64decode(PAYLOAD.strip()).decode())
    problems: list[str] = []
    echoes: list[str] = []
    planned: dict[str, str] = {}
    skipped: list[str] = []

    for rel, content in data["new_files"].items():
        path = Path(rel)
        if path.exists() and path.read_text() == content:
            skipped.append(f"{rel}: already present and identical")
            continue
        planned[rel] = content

    for item in data.get("replacements", []):
        rel = item["path"]
        path = Path(rel)
        if not path.exists():
            problems.append(f"  {rel}: file not found")
            continue
        current = path.read_text()
        if current == item["content"]:
            skipped.append(f"{rel}: already replaced")
            continue
        actual = hashlib.sha256(current.encode()).hexdigest()
        if actual != item["expect_sha256"]:
            problems.append(
                f"  {rel}: this file is not the one the replacement was written against.\n"
                f"        expected sha256 {item['expect_sha256'][:16]}…\n"
                f"        found            {actual[:16]}…\n"
                f"        Its current contents are printed below so it can be re-done."
            )
            lines = current.splitlines()
            body = lines[:MAX_ECHO_LINES]
            echoes.append(
                f"───── {rel} ({len(lines)} lines) ─────\n"
                + "\n".join(body)
                + ("\n… truncated …" if len(lines) > MAX_ECHO_LINES else "")
            )
            continue
        planned[rel] = item["content"]

    for index, item in enumerate(data["edits"], start=1):
        rel = item["path"]
        path = Path(rel)
        if not path.exists():
            problems.append(f"  [{index}] {rel}: file not found")
            continue
        text = planned.get(rel, path.read_text())
        if item["marker"] in text:
            skipped.append(f"{rel} [{index}]: already applied")
            continue
        anchor = item["anchor"]
        found = text.count(anchor)
        expect_all = item.get("count") == "all"
        if found == 0 or (found != 1 and not expect_all):
            problems.append(
                f"  [{index}] {rel}: expected "
                f"{'>=1' if expect_all else 'exactly 1'} match, found {found}\n"
                f"        anchor starts: {anchor.splitlines()[0][:76]!r}"
            )
            continue
        planned[rel] = text.replace(anchor, item["replacement"], -1 if expect_all else 1)

    if problems:
        print("ABORTED - NOTHING was written. Every problem, so one round-trip fixes all:")
        print()
        for problem in problems:
            print(problem)
        for echo in echoes:
            print()
            print(echo)
        return 1

    for rel, content in sorted(planned.items()):
        Path(rel).parent.mkdir(parents=True, exist_ok=True)
        Path(rel).write_text(content)
        print(f"wrote {rel}")
    for note in skipped:
        print(f"skip  {note}")
    if not planned:
        print("nothing to do - already applied")

    print()
    print("Rebuild the frontend and run its test suite.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
