#!/usr/bin/env python3
"""Bring the Spotlight WALL back - every app as a tile, shaded by completeness.

The earlier App Spotlight was a wall: every app_master_v2 record as a tile, red where
publisher / HOU / pod / pod owner / partner / share was missing, green where the record
was filled, with search and All / Needs update / Complete filters. The revenue-ordered
shortlist that replaced it answers a different question - and the owner wants both, so
now the page has both:

  * The SHORTLIST on top: "what should I fix this morning" - incomplete apps, worst by
    revenue, today and this week, with the numbers that justify the effort.
  * The BOARD below: "how bad is it overall" - every scoped app, shaded, searchable,
    each required field shown filled or Missing. Complete apps stay ON the board in
    green: done must be visible, not indistinguishable from invisible.

Same scoping as everything else (no scope = empty wall, because being shown an app is
being told it exists), same seven required fields derived from the editable set, and the
tiles route admins to App Master and everyone else to App Changes - the two doors these
records already have. Service + route + types + hook + tests + client.
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

FOOTER = 'Rebuild backend + frontend, then run both test suites.'

PAYLOAD = """
eyJuZXdfZmlsZXMiOiB7ImZyb250ZW5kL2NvbXBvbmVudHMvc3BvdGxpZ2h0L3Nwb3RsaWdodC1jbGllbnQudHN4IjogIlwi
dXNlIGNsaWVudFwiO1xuXG5pbXBvcnQgTGluayBmcm9tIFwibmV4dC9saW5rXCI7XG5pbXBvcnQgeyBBbGVydFRyaWFuZ2xl
LCBDaGVja0NpcmNsZTIgfSBmcm9tIFwibHVjaWRlLXJlYWN0XCI7XG5pbXBvcnQgeyB1c2VNZW1vLCB1c2VTdGF0ZSB9IGZy
b20gXCJyZWFjdFwiO1xuXG5pbXBvcnQgeyBQYWdlSGVhZGVyIH0gZnJvbSBcIkAvY29tcG9uZW50cy9sYXlvdXQvcGFnZS1o
ZWFkZXJcIjtcbmltcG9ydCB7IEJhZGdlIH0gZnJvbSBcIkAvY29tcG9uZW50cy91aS9iYWRnZVwiO1xuaW1wb3J0IHsgQ2Fy
ZCwgQ2FyZENvbnRlbnQsIENhcmRIZWFkZXIsIENhcmRUaXRsZSB9IGZyb20gXCJAL2NvbXBvbmVudHMvdWkvY2FyZFwiO1xu
aW1wb3J0IHsgU2tlbGV0b24gfSBmcm9tIFwiQC9jb21wb25lbnRzL3VpL3NrZWxldG9uXCI7XG5pbXBvcnQgeyB1c2VNZSwg
dXNlU3BvdGxpZ2h0LCB1c2VTcG90bGlnaHRCb2FyZCB9IGZyb20gXCJAL2xpYi9hcGktaG9va3NcIjtcbmltcG9ydCB7IGZv
cm1hdE51bWJlciwgZm9ybWF0VGFibGVVU0QgfSBmcm9tIFwiQC9saWIvZm9ybWF0XCI7XG5pbXBvcnQgeyBjbiB9IGZyb20g
XCJAL2xpYi91dGlsc1wiO1xuaW1wb3J0IHR5cGUgeyBTcG90bGlnaHRBcHAsIFNwb3RsaWdodEJvYXJkQXBwIH0gZnJvbSBc
IkAvbGliL3R5cGVzXCI7XG5cbi8qKiBIdW1hbiBsYWJlbHMgZm9yIHRoZSByZXF1aXJlZCBmaWVsZHMuIFRoZSBBUEkgcmV0
dXJucyBjb2x1bW4gbmFtZXM7IGEgcGVyc29uIGZpbGxpbmdcbiAqICB0aGUgZm9ybSBzaG91bGQgbm90IGhhdmUgdG8gdHJh
bnNsYXRlIGBuZXRfcmV2ZW51ZV9zaGFyZWAgaW4gdGhlaXIgaGVhZC4gKi9cbmNvbnN0IEZJRUxEX0xBQkVMUzogUmVjb3Jk
PHN0cmluZywgc3RyaW5nPiA9IHtcbiAgcHVibGlzaGVyOiBcIlB1Ymxpc2hlclwiLFxuICBob3U6IFwiSE9VXCIsXG4gIHBv
ZDogXCJQb2RcIixcbiAgcG9kX293bmVyOiBcIlBvZCBvd25lclwiLFxuICBwYXJ0bmVyX25hbWU6IFwiUGFydG5lciBuYW1l
XCIsXG4gIG5ldF9yZXZlbnVlX3NoYXJlOiBcIk5ldCByZXZlbnVlIHNoYXJlXCIsXG4gIHR5cGU6IFwiVHlwZVwiLFxufTtc
blxuZnVuY3Rpb24gbGFiZWwoZmllbGQ6IHN0cmluZyk6IHN0cmluZyB7XG4gIHJldHVybiBGSUVMRF9MQUJFTFNbZmllbGRd
ID8/IGZpZWxkO1xufVxuXG4vKiogQ2hpcCBvcmRlciBtaXJyb3JzIHRoZSBmb3JtIHBlb3BsZSBmaWxsLCBvd25lcnNoaXAg
Zmlyc3QuICovXG5jb25zdCBDSElQX09SREVSID0gW1xuICBcInB1Ymxpc2hlclwiLFxuICBcImhvdVwiLFxuICBcInBvZFwi
LFxuICBcInBvZF9vd25lclwiLFxuICBcInBhcnRuZXJfbmFtZVwiLFxuICBcIm5ldF9yZXZlbnVlX3NoYXJlXCIsXG4gIFwi
dHlwZVwiLFxuXTtcblxudHlwZSBCb2FyZEZpbHRlciA9IFwiYWxsXCIgfCBcIm5lZWRzXCIgfCBcImNvbXBsZXRlXCI7XG5c
bi8qKiBUd28gYW5zd2VycyBvbiBvbmUgcGFnZS5cbiAqXG4gKiAgVGhlIFNIT1JUTElTVCBvbiB0b3AgYW5zd2VycyBcIndo
YXQgc2hvdWxkIEkgZml4IHRoaXMgbW9ybmluZ1wiIC0gaW5jb21wbGV0ZSBhcHBzLFxuICogIHdvcnN0LWJ5LXJldmVudWUg
Zmlyc3QsIGZvciB0b2RheSBhbmQgZm9yIHRoZSB3ZWVrLCBlYWNoIHdpdGggdGhlIG51bWJlcnMgdGhhdCBtYWtlXG4gKiAg
aXQgd29ydGggc29tZW9uZSdzIHRpbWUuXG4gKlxuICogIFRoZSBCT0FSRCBiZWxvdyBhbnN3ZXJzIFwiaG93IGJhZCBpcyBp
dCBvdmVyYWxsXCIgLSBFVkVSWSBhcHAgdGhpcyBjYWxsZXIgY2FuIHNlZSxcbiAqICBzaGFkZWQgYnkgY29tcGxldGVuZXNz
LCBzZWFyY2hhYmxlLCB3aXRoIGVhY2ggcmVxdWlyZWQgZmllbGQgc2hvd24gZmlsbGVkIG9yIE1pc3NpbmcuXG4gKiAgQSBm
aWxsZWQtaW4gYXBwIHR1cm5zIGdyZWVuIHJhdGhlciB0aGFuIGRpc2FwcGVhcmluZywgc28gXCJkb25lXCIgc3RheXMgdmlz
aWJsZSBpbnN0ZWFkXG4gKiAgb2YgYmVjb21pbmcgaW5kaXN0aW5ndWlzaGFibGUgZnJvbSBcImludmlzaWJsZVwiLlxuICpc
biAqICBCb3RoIGFyZSBzY29wZWQgc2VydmVyLXNpZGU6IGJlaW5nIHNob3duIGFuIGFwcCBpcyBiZWluZyB0b2xkIGl0IGV4
aXN0cy4gKi9cbmV4cG9ydCBmdW5jdGlvbiBTcG90bGlnaHRDbGllbnQoKSB7XG4gIGNvbnN0IHsgZGF0YSwgaXNMb2FkaW5n
LCBpc0Vycm9yIH0gPSB1c2VTcG90bGlnaHQoKTtcblxuICByZXR1cm4gKFxuICAgIDxkaXYgY2xhc3NOYW1lPVwic3BhY2Ut
eS02XCI+XG4gICAgICA8UGFnZUhlYWRlciB0aXRsZT1cIkFwcCBTcG90bGlnaHRcIiAvPlxuXG4gICAgICB7aXNMb2FkaW5n
ICYmIDxTa2VsZXRvbiBjbGFzc05hbWU9XCJoLTY0IHctZnVsbFwiIC8+fVxuICAgICAge2lzRXJyb3IgJiYgKFxuICAgICAg
ICA8cCBjbGFzc05hbWU9XCJ0ZXh0LXNtIHRleHQtW2NvbG9yOnZhcigtLWNvbG9yLW5lZ2F0aXZlKV1cIj5cbiAgICAgICAg
ICBDb3VsZG4mYXBvczt0IGxvYWQgdGhlIHNwb3RsaWdodC5cbiAgICAgICAgPC9wPlxuICAgICAgKX1cblxuICAgICAge2Rh
dGEgJiYgZGF0YS5pbmNvbXBsZXRlX2NvdW50ID09PSAwICYmIChcbiAgICAgICAgPENhcmQ+XG4gICAgICAgICAgPENhcmRD
b250ZW50IGNsYXNzTmFtZT1cImZsZXggaXRlbXMtY2VudGVyIGdhcC0yIHB5LTYgdGV4dC1zbSB0ZXh0LW11dGVkLWZvcmVn
cm91bmRcIj5cbiAgICAgICAgICAgIDxDaGVja0NpcmNsZTIgY2xhc3NOYW1lPVwiaC00IHctNCB0ZXh0LVtjb2xvcjp2YXIo
LS1jb2xvci1wb3NpdGl2ZSldXCIgLz5cbiAgICAgICAgICAgIEV2ZXJ5IGFwcCB5b3UgY2FuIHNlZSBoYXMgaXRzIHBvZCwg
b3duZXIsIEhPVSwgcGFydG5lciwgc2hhcmUgYW5kIHR5cGUgZmlsbGVkIGluLlxuICAgICAgICAgIDwvQ2FyZENvbnRlbnQ+
XG4gICAgICAgIDwvQ2FyZD5cbiAgICAgICl9XG5cbiAgICAgIHtkYXRhICYmIGRhdGEuaW5jb21wbGV0ZV9jb3VudCA+IDAg
JiYgKFxuICAgICAgICA8PlxuICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPVwiZmxleCBmbGV4LXdyYXAgaXRlbXMtY2VudGVy
IGdhcC0yIHRleHQtc20gdGV4dC1tdXRlZC1mb3JlZ3JvdW5kXCI+XG4gICAgICAgICAgICA8QWxlcnRUcmlhbmdsZSBjbGFz
c05hbWU9XCJoLTQgdy00IHRleHQtW2NvbG9yOnZhcigtLWNvbG9yLW5lZ2F0aXZlKV1cIiAvPlxuICAgICAgICAgICAgPHNw
YW4+XG4gICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT1cImZvbnQtc2VtaWJvbGQgdGV4dC1mb3JlZ3JvdW5kIHRhYnVs
YXItbnVtc1wiPlxuICAgICAgICAgICAgICAgIHtmb3JtYXROdW1iZXIoZGF0YS5pbmNvbXBsZXRlX2NvdW50KX1cbiAgICAg
ICAgICAgICAgPC9zcGFuPntcIiBcIn1cbiAgICAgICAgICAgICAge2RhdGEuaW5jb21wbGV0ZV9jb3VudCA9PT0gMSA/IFwi
YXBwIGlzXCIgOiBcImFwcHMgYXJlXCJ9IG1pc3NpbmcgYXQgbGVhc3Qgb25lIG9me1wiIFwifVxuICAgICAgICAgICAgICB7
ZGF0YS5yZXF1aXJlZF9maWVsZHMubWFwKGxhYmVsKS5qb2luKFwiLCBcIil9LiBVbnRpbCB0aGV5IGFyZSBmaWxsZWQgaW4s
IHdoYXRcbiAgICAgICAgICAgICAgdGhlc2UgYXBwcyBlYXJuIGlzIGF0dHJpYnV0ZWQgdG8gbm9ib2R5LlxuICAgICAgICAg
ICAgPC9zcGFuPlxuICAgICAgICAgIDwvZGl2PlxuXG4gICAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJncmlkIGdhcC00IGxn
OmdyaWQtY29scy0yXCI+XG4gICAgICAgICAgICA8U3BvdGxpZ2h0TGlzdFxuICAgICAgICAgICAgICB0aXRsZT1cIlNwb3Rs
aWdodCBvZiB0aGUgZGF5XCJcbiAgICAgICAgICAgICAgc3VidGl0bGU9e2Ake2RhdGEud2luZG93cy5kYXkuZnJvbX0gXHUy
MDE0IGhpZ2hlc3QgcmV2ZW51ZSB0b2RheWB9XG4gICAgICAgICAgICAgIGFwcHM9e2RhdGEub2ZfdGhlX2RheX1cbiAgICAg
ICAgICAgIC8+XG4gICAgICAgICAgICA8U3BvdGxpZ2h0TGlzdFxuICAgICAgICAgICAgICB0aXRsZT1cIlNwb3RsaWdodCBv
ZiB0aGUgd2Vla1wiXG4gICAgICAgICAgICAgIHN1YnRpdGxlPXtgJHtkYXRhLndpbmRvd3Mud2Vlay5mcm9tfSB0byAke2Rh
dGEud2luZG93cy53ZWVrLnRvfWB9XG4gICAgICAgICAgICAgIGFwcHM9e2RhdGEub2ZfdGhlX3dlZWt9XG4gICAgICAgICAg
ICAvPlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8Lz5cbiAgICAgICl9XG5cbiAgICAgIDxTcG90bGlnaHRCb2FyZCAv
PlxuICAgIDwvZGl2PlxuICApO1xufVxuXG4vKiogVGhlIHdhbGw6IGV2ZXJ5IHNjb3BlZCBhcHAgYXMgYSB0aWxlLCByZWQg
d2hlcmUgdGhlIHJlY29yZCBoYXMgaG9sZXMsIGdyZWVuIHdoZXJlIGl0XG4gKiAgaXMgZmlsbGVkLiBDbGljayBhIHRpbGUg
dG8gZ28gZml4IGl0LiAqL1xuZnVuY3Rpb24gU3BvdGxpZ2h0Qm9hcmQoKSB7XG4gIGNvbnN0IGJvYXJkID0gdXNlU3BvdGxp
Z2h0Qm9hcmQoKTtcbiAgY29uc3QgeyBkYXRhOiBtZSB9ID0gdXNlTWUoKTtcbiAgY29uc3QgW2ZpbHRlciwgc2V0RmlsdGVy
XSA9IHVzZVN0YXRlPEJvYXJkRmlsdGVyPihcImFsbFwiKTtcbiAgY29uc3QgW3F1ZXJ5LCBzZXRRdWVyeV0gPSB1c2VTdGF0
ZShcIlwiKTtcblxuICBjb25zdCBpc0FkbWluID0gbWU/LmNhcGFiaWxpdGllcy5pbmNsdWRlcyhcImFkbWluX3BhbmVsXCIp
ID8/IGZhbHNlO1xuXG4gIGNvbnN0IHNob3duID0gdXNlTWVtbygoKSA9PiB7XG4gICAgLy8gVGhlIGZhbGxiYWNrIGxpdmVz
IElOU0lERSB0aGUgbWVtbzogYD8/IFtdYCBvdXRzaWRlIGl0IG1ha2VzIGEgZnJlc2ggYXJyYXkgZXZlcnlcbiAgICAvLyBy
ZW5kZXIsIHdoaWNoIG1ha2VzIHRoZSBkZXBlbmRlbmN5IGNoYW5nZSBldmVyeSByZW5kZXIsIHdoaWNoIHVuLW1lbW9pemVz
IHRoZSBtZW1vLlxuICAgIGNvbnN0IGFwcHMgPSBib2FyZC5kYXRhPy5hcHBzID8/IFtdO1xuICAgIGNvbnN0IHEgPSBxdWVy
eS50cmltKCkudG9Mb3dlckNhc2UoKTtcbiAgICByZXR1cm4gYXBwcy5maWx0ZXIoKGFwcCkgPT4ge1xuICAgICAgaWYgKGZp
bHRlciA9PT0gXCJuZWVkc1wiICYmIGFwcC5taXNzaW5nLmxlbmd0aCA9PT0gMCkgcmV0dXJuIGZhbHNlO1xuICAgICAgaWYg
KGZpbHRlciA9PT0gXCJjb21wbGV0ZVwiICYmIGFwcC5taXNzaW5nLmxlbmd0aCA+IDApIHJldHVybiBmYWxzZTtcbiAgICAg
IGlmICghcSkgcmV0dXJuIHRydWU7XG4gICAgICByZXR1cm4gKFxuICAgICAgICAoYXBwLmFwcF9uYW1lID8/IFwiXCIpLnRv
TG93ZXJDYXNlKCkuaW5jbHVkZXMocSkgfHxcbiAgICAgICAgYXBwLmNhbm9uaWNhbF9rZXkudG9Mb3dlckNhc2UoKS5pbmNs
dWRlcyhxKVxuICAgICAgKTtcbiAgICB9KTtcbiAgfSwgW2JvYXJkLmRhdGEsIGZpbHRlciwgcXVlcnldKTtcblxuICBpZiAo
Ym9hcmQuaXNMb2FkaW5nKSByZXR1cm4gPFNrZWxldG9uIGNsYXNzTmFtZT1cImgtOTYgdy1mdWxsXCIgLz47XG4gIGlmIChi
b2FyZC5pc0Vycm9yKSB7XG4gICAgcmV0dXJuIChcbiAgICAgIDxwIGNsYXNzTmFtZT1cInRleHQtc20gdGV4dC1bY29sb3I6
dmFyKC0tY29sb3ItbmVnYXRpdmUpXVwiPlxuICAgICAgICBDb3VsZG4mYXBvczt0IGxvYWQgdGhlIGJvYXJkLlxuICAgICAg
PC9wPlxuICAgICk7XG4gIH1cbiAgaWYgKCFib2FyZC5kYXRhIHx8IGJvYXJkLmRhdGEudG90YWwgPT09IDApIHJldHVybiBu
dWxsO1xuXG4gIGNvbnN0IGZpZWxkcyA9IGJvYXJkLmRhdGEucmVxdWlyZWRfZmllbGRzXG4gICAgLnNsaWNlKClcbiAgICAu
c29ydCgoYSwgYikgPT4gQ0hJUF9PUkRFUi5pbmRleE9mKGEpIC0gQ0hJUF9PUkRFUi5pbmRleE9mKGIpKTtcblxuICByZXR1
cm4gKFxuICAgIDxkaXYgY2xhc3NOYW1lPVwic3BhY2UteS00XCI+XG4gICAgICA8ZGl2PlxuICAgICAgICA8aDIgY2xhc3NO
YW1lPVwiZm9udC1kaXNwbGF5IHRleHQtbGcgdHJhY2tpbmctdGlnaHRcIj5FdmVyeSBhcHAsIHNoYWRlZCBieSBjb21wbGV0
ZW5lc3M8L2gyPlxuICAgICAgICA8cCBjbGFzc05hbWU9XCJ0ZXh0LXNtIHRleHQtbXV0ZWQtZm9yZWdyb3VuZFwiPlxuICAg
ICAgICAgIFJlZCB3aGVyZSB7ZmllbGRzLm1hcChsYWJlbCkuam9pbihcIiwgXCIpLnRvTG93ZXJDYXNlKCl9IGlzIG1pc3Np
bmcsIGdyZWVuIHdoZXJlIHRoZVxuICAgICAgICAgIHJlY29yZCBpcyBmaWxsZWQuIENsaWNrIGEgdGlsZSB0byBlZGl0IGl0
LlxuICAgICAgICA8L3A+XG4gICAgICA8L2Rpdj5cblxuICAgICAgPGRpdiBjbGFzc05hbWU9XCJmbGV4IGZsZXgtd3JhcCBp
dGVtcy1jZW50ZXIgZ2FwLTJcIj5cbiAgICAgICAgPHNwYW5cbiAgICAgICAgICBjbGFzc05hbWU9XCJpbmxpbmUtZmxleCBp
dGVtcy1jZW50ZXIgZ2FwLTEuNSByb3VuZGVkLW1kIGJvcmRlciBweC0yLjUgcHktMSB0ZXh0LXhzXCJcbiAgICAgICAgICBz
dHlsZT17e1xuICAgICAgICAgICAgYm9yZGVyQ29sb3I6IFwiY29sb3ItbWl4KGluIHNyZ2IsIHZhcigtLWNvbG9yLW5lZ2F0
aXZlKSAzNSUsIHRyYW5zcGFyZW50KVwiLFxuICAgICAgICAgICAgYmFja2dyb3VuZDogXCJjb2xvci1taXgoaW4gc3JnYiwg
dmFyKC0tY29sb3ItbmVnYXRpdmUpIDYlLCB0cmFuc3BhcmVudClcIixcbiAgICAgICAgICB9fVxuICAgICAgICA+XG4gICAg
ICAgICAgPEFsZXJ0VHJpYW5nbGUgY2xhc3NOYW1lPVwiaC0zLjUgdy0zLjUgdGV4dC1bY29sb3I6dmFyKC0tY29sb3ItbmVn
YXRpdmUpXVwiIC8+XG4gICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPVwiZm9udC1zZW1pYm9sZCB0YWJ1bGFyLW51bXNcIj57
Zm9ybWF0TnVtYmVyKGJvYXJkLmRhdGEuaW5jb21wbGV0ZSl9PC9zcGFuPlxuICAgICAgICAgIG5lZWQgdXBkYXRpbmdcbiAg
ICAgICAgPC9zcGFuPlxuICAgICAgICA8c3BhblxuICAgICAgICAgIGNsYXNzTmFtZT1cImlubGluZS1mbGV4IGl0ZW1zLWNl
bnRlciBnYXAtMS41IHJvdW5kZWQtbWQgYm9yZGVyIHB4LTIuNSBweS0xIHRleHQteHNcIlxuICAgICAgICAgIHN0eWxlPXt7
XG4gICAgICAgICAgICBib3JkZXJDb2xvcjogXCJjb2xvci1taXgoaW4gc3JnYiwgdmFyKC0tY29sb3ItcG9zaXRpdmUpIDM1
JSwgdHJhbnNwYXJlbnQpXCIsXG4gICAgICAgICAgICBiYWNrZ3JvdW5kOiBcImNvbG9yLW1peChpbiBzcmdiLCB2YXIoLS1j
b2xvci1wb3NpdGl2ZSkgNiUsIHRyYW5zcGFyZW50KVwiLFxuICAgICAgICAgIH19XG4gICAgICAgID5cbiAgICAgICAgICA8
Q2hlY2tDaXJjbGUyIGNsYXNzTmFtZT1cImgtMy41IHctMy41IHRleHQtW2NvbG9yOnZhcigtLWNvbG9yLXBvc2l0aXZlKV1c
IiAvPlxuICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT1cImZvbnQtc2VtaWJvbGQgdGFidWxhci1udW1zXCI+e2Zvcm1hdE51
bWJlcihib2FyZC5kYXRhLmNvbXBsZXRlKX08L3NwYW4+XG4gICAgICAgICAgY29tcGxldGVcbiAgICAgICAgPC9zcGFuPlxu
XG4gICAgICAgIDxkaXYgY2xhc3NOYW1lPVwibWwtYXV0byBmbGV4IGZsZXgtd3JhcCBpdGVtcy1jZW50ZXIgZ2FwLTJcIj5c
biAgICAgICAgICA8aW5wdXRcbiAgICAgICAgICAgIHZhbHVlPXtxdWVyeX1cbiAgICAgICAgICAgIG9uQ2hhbmdlPXsoZXZl
bnQpID0+IHNldFF1ZXJ5KGV2ZW50LnRhcmdldC52YWx1ZSl9XG4gICAgICAgICAgICBwbGFjZWhvbGRlcj1cIkZpbmQgYW4g
YXBwXCJcbiAgICAgICAgICAgIGFyaWEtbGFiZWw9XCJGaW5kIGFuIGFwcFwiXG4gICAgICAgICAgICBjbGFzc05hbWU9XCJo
LTggdy1mdWxsIHJvdW5kZWQtbWQgYm9yZGVyIGJnLXRyYW5zcGFyZW50IHB4LTMgdGV4dC1zbSBvdXRsaW5lLW5vbmUgcGxh
Y2Vob2xkZXI6dGV4dC1tdXRlZC1mb3JlZ3JvdW5kIGZvY3VzOmJvcmRlci1bY29sb3I6dmFyKC0tY29sb3ItYWNjZW50KV0g
c206dy01NlwiXG4gICAgICAgICAgLz5cbiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT1cImZsZXggb3ZlcmZsb3ctaGlkZGVu
IHJvdW5kZWQtbWQgYm9yZGVyIHRleHQteHNcIj5cbiAgICAgICAgICAgIHsoXG4gICAgICAgICAgICAgIFtcbiAgICAgICAg
ICAgICAgICBbXCJhbGxcIiwgXCJBbGxcIl0sXG4gICAgICAgICAgICAgICAgW1wibmVlZHNcIiwgXCJOZWVkcyB1cGRhdGVc
Il0sXG4gICAgICAgICAgICAgICAgW1wiY29tcGxldGVcIiwgXCJDb21wbGV0ZVwiXSxcbiAgICAgICAgICAgICAgXSBhcyBb
Qm9hcmRGaWx0ZXIsIHN0cmluZ11bXVxuICAgICAgICAgICAgKS5tYXAoKFt2YWx1ZSwgdGV4dF0pID0+IChcbiAgICAgICAg
ICAgICAgPGJ1dHRvblxuICAgICAgICAgICAgICAgIGtleT17dmFsdWV9XG4gICAgICAgICAgICAgICAgdHlwZT1cImJ1dHRv
blwiXG4gICAgICAgICAgICAgICAgb25DbGljaz17KCkgPT4gc2V0RmlsdGVyKHZhbHVlKX1cbiAgICAgICAgICAgICAgICBj
bGFzc05hbWU9e2NuKFxuICAgICAgICAgICAgICAgICAgXCJweC0yLjUgcHktMS41XCIsXG4gICAgICAgICAgICAgICAgICBm
aWx0ZXIgPT09IHZhbHVlXG4gICAgICAgICAgICAgICAgICAgID8gXCJiZy1bY29sb3I6dmFyKC0tY29sb3ItYWNjZW50KV0g
Zm9udC1tZWRpdW0gdGV4dC1bY29sb3I6dmFyKC0tY29sb3ItYWNjZW50LWZvcmVncm91bmQpXVwiXG4gICAgICAgICAgICAg
ICAgICAgIDogXCJ0ZXh0LW11dGVkLWZvcmVncm91bmQgaG92ZXI6dGV4dC1mb3JlZ3JvdW5kXCIsXG4gICAgICAgICAgICAg
ICAgKX1cbiAgICAgICAgICAgICAgPlxuICAgICAgICAgICAgICAgIHt0ZXh0fVxuICAgICAgICAgICAgICA8L2J1dHRvbj5c
biAgICAgICAgICAgICkpfVxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuXG4gICAg
ICB7c2hvd24ubGVuZ3RoID09PSAwID8gKFxuICAgICAgICA8cCBjbGFzc05hbWU9XCJweS04IHRleHQtY2VudGVyIHRleHQt
c20gdGV4dC1tdXRlZC1mb3JlZ3JvdW5kXCI+XG4gICAgICAgICAgTm8gYXBwIG1hdGNoZXMgdGhpcyBzZWFyY2ggYW5kIGZp
bHRlci5cbiAgICAgICAgPC9wPlxuICAgICAgKSA6IChcbiAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJncmlkIGdhcC0zIG1k
OmdyaWQtY29scy0yIHhsOmdyaWQtY29scy0zXCI+XG4gICAgICAgICAge3Nob3duLm1hcCgoYXBwKSA9PiAoXG4gICAgICAg
ICAgICA8Qm9hcmRUaWxlIGtleT17YXBwLmNhbm9uaWNhbF9rZXl9IGFwcD17YXBwfSBmaWVsZHM9e2ZpZWxkc30gaXNBZG1p
bj17aXNBZG1pbn0gLz5cbiAgICAgICAgICApKX1cbiAgICAgICAgPC9kaXY+XG4gICAgICApfVxuICAgIDwvZGl2PlxuICAp
O1xufVxuXG5mdW5jdGlvbiBCb2FyZFRpbGUoe1xuICBhcHAsXG4gIGZpZWxkcyxcbiAgaXNBZG1pbixcbn06IHtcbiAgYXBw
OiBTcG90bGlnaHRCb2FyZEFwcDtcbiAgZmllbGRzOiBzdHJpbmdbXTtcbiAgaXNBZG1pbjogYm9vbGVhbjtcbn0pIHtcbiAg
Y29uc3QgbWlzc2luZyA9IG5ldyBTZXQoYXBwLm1pc3NpbmcpO1xuICBjb25zdCBpbmNvbXBsZXRlID0gbWlzc2luZy5zaXpl
ID4gMDtcbiAgY29uc3QgdG9uZSA9IGluY29tcGxldGUgPyBcIi0tY29sb3ItbmVnYXRpdmVcIiA6IFwiLS1jb2xvci1wb3Np
dGl2ZVwiO1xuICAvLyBBZG1pbnMgZWRpdCBpbiBBcHAgTWFzdGVyOyBldmVyeW9uZSBlbHNlIHByb3Bvc2VzIHRoZSBjaGFu
Z2UgdGhyb3VnaCBBcHAgQ2hhbmdlcyAtXG4gIC8vIHRoZSBzYW1lIHR3byBkb29ycyB0aGVzZSByZWNvcmRzIGFscmVhZHkg
aGF2ZS5cbiAgY29uc3QgZWRpdEhyZWYgPSBpc0FkbWluXG4gICAgPyBgL2FwcC1tYXN0ZXI/c2VhcmNoPSR7ZW5jb2RlVVJJ
Q29tcG9uZW50KGFwcC5hcHBfbmFtZSA/PyBhcHAuY2Fub25pY2FsX2tleSl9YFxuICAgIDogXCIvYXBwLWNoYW5nZXNcIjtc
blxuICByZXR1cm4gKFxuICAgIDxMaW5rXG4gICAgICBocmVmPXtlZGl0SHJlZn1cbiAgICAgIGNsYXNzTmFtZT1cImJsb2Nr
IHJvdW5kZWQtbGcgYm9yZGVyIHAtNCB0cmFuc2l0aW9uLXNoYWRvdyBob3ZlcjpzaGFkb3ctbWRcIlxuICAgICAgc3R5bGU9
e3tcbiAgICAgICAgYm9yZGVyQ29sb3I6IGBjb2xvci1taXgoaW4gc3JnYiwgdmFyKCR7dG9uZX0pIDM1JSwgdHJhbnNwYXJl
bnQpYCxcbiAgICAgICAgYmFja2dyb3VuZDogYGNvbG9yLW1peChpbiBzcmdiLCB2YXIoJHt0b25lfSkgNSUsIHRyYW5zcGFy
ZW50KWAsXG4gICAgICB9fVxuICAgID5cbiAgICAgIDxkaXYgY2xhc3NOYW1lPVwiZmxleCBpdGVtcy1zdGFydCBqdXN0aWZ5
LWJldHdlZW4gZ2FwLTJcIj5cbiAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJtaW4tdy0wXCI+XG4gICAgICAgICAgPGRpdiBj
bGFzc05hbWU9XCJ0cnVuY2F0ZSBmb250LW1lZGl1bVwiPnthcHAuYXBwX25hbWUgPz8gYXBwLmNhbm9uaWNhbF9rZXl9PC9k
aXY+XG4gICAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJ0cnVuY2F0ZSB0ZXh0LXhzIHRleHQtbXV0ZWQtZm9yZWdyb3VuZFwi
PnthcHAuY2Fub25pY2FsX2tleX08L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIHtpbmNvbXBsZXRlICYmIChcbiAg
ICAgICAgICA8c3BhblxuICAgICAgICAgICAgY2xhc3NOYW1lPVwic2hyaW5rLTAgcm91bmRlZCBweC0xLjUgcHktMC41IHRl
eHQtWzEwcHhdIGZvbnQtc2VtaWJvbGQgdXBwZXJjYXNlIHRyYWNraW5nLXdpZGVyIHRleHQtW2NvbG9yOnZhcigtLWNvbG9y
LW5lZ2F0aXZlKV1cIlxuICAgICAgICAgICAgc3R5bGU9e3sgYmFja2dyb3VuZDogXCJjb2xvci1taXgoaW4gc3JnYiwgdmFy
KC0tY29sb3ItbmVnYXRpdmUpIDEwJSwgdHJhbnNwYXJlbnQpXCIgfX1cbiAgICAgICAgICA+XG4gICAgICAgICAgICB7bWlz
c2luZy5zaXplfSBtaXNzaW5nXG4gICAgICAgICAgPC9zcGFuPlxuICAgICAgICApfVxuICAgICAgPC9kaXY+XG5cbiAgICAg
IDxkaXYgY2xhc3NOYW1lPVwibXQtMyBmbGV4IGZsZXgtd3JhcCBnYXAtMS41XCI+XG4gICAgICAgIHtmaWVsZHMubWFwKChm
aWVsZCkgPT4ge1xuICAgICAgICAgIGNvbnN0IGFic2VudCA9IG1pc3NpbmcuaGFzKGZpZWxkKTtcbiAgICAgICAgICBjb25z
dCB2YWx1ZSA9IGFwcC5maWVsZHNbZmllbGRdO1xuICAgICAgICAgIHJldHVybiAoXG4gICAgICAgICAgICA8c3BhblxuICAg
ICAgICAgICAgICBrZXk9e2ZpZWxkfVxuICAgICAgICAgICAgICBjbGFzc05hbWU9XCJyb3VuZGVkLWZ1bGwgYm9yZGVyIHB4
LTIgcHktMC41IHRleHQtWzExcHhdXCJcbiAgICAgICAgICAgICAgc3R5bGU9e3tcbiAgICAgICAgICAgICAgICBib3JkZXJD
b2xvcjogYGNvbG9yLW1peChpbiBzcmdiLCB2YXIoJHthYnNlbnQgPyBcIi0tY29sb3ItbmVnYXRpdmVcIiA6IFwiLS1jb2xv
ci1wb3NpdGl2ZVwifSkgMzAlLCB0cmFuc3BhcmVudClgLFxuICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6IGBjb2xvci1t
aXgoaW4gc3JnYiwgdmFyKCR7YWJzZW50ID8gXCItLWNvbG9yLW5lZ2F0aXZlXCIgOiBcIi0tY29sb3ItcG9zaXRpdmVcIn0p
IDclLCB0cmFuc3BhcmVudClgLFxuICAgICAgICAgICAgICB9fVxuICAgICAgICAgICAgPlxuICAgICAgICAgICAgICB7bGFi
ZWwoZmllbGQpfToge2Fic2VudCA/IFwiTWlzc2luZ1wiIDogU3RyaW5nKHZhbHVlKX1cbiAgICAgICAgICAgIDwvc3Bhbj5c
biAgICAgICAgICApO1xuICAgICAgICB9KX1cbiAgICAgIDwvZGl2PlxuICAgIDwvTGluaz5cbiAgKTtcbn1cblxuZnVuY3Rp
b24gU3BvdGxpZ2h0TGlzdCh7XG4gIHRpdGxlLFxuICBzdWJ0aXRsZSxcbiAgYXBwcyxcbn06IHtcbiAgdGl0bGU6IHN0cmlu
ZztcbiAgc3VidGl0bGU6IHN0cmluZztcbiAgYXBwczogU3BvdGxpZ2h0QXBwW107XG59KSB7XG4gIHJldHVybiAoXG4gICAg
PENhcmQ+XG4gICAgICA8Q2FyZEhlYWRlcj5cbiAgICAgICAgPENhcmRUaXRsZT57dGl0bGV9PC9DYXJkVGl0bGU+XG4gICAg
ICAgIDxwIGNsYXNzTmFtZT1cInRleHQteHMgdGV4dC1tdXRlZC1mb3JlZ3JvdW5kXCI+e3N1YnRpdGxlfTwvcD5cbiAgICAg
IDwvQ2FyZEhlYWRlcj5cbiAgICAgIDxDYXJkQ29udGVudCBjbGFzc05hbWU9XCJzcGFjZS15LTNcIj5cbiAgICAgICAge2Fw
cHMubGVuZ3RoID09PSAwICYmIChcbiAgICAgICAgICA8cCBjbGFzc05hbWU9XCJ0ZXh0LXNtIHRleHQtbXV0ZWQtZm9yZWdy
b3VuZFwiPk5vdGhpbmcgdG8gc2hvdyBmb3IgdGhpcyB3aW5kb3cuPC9wPlxuICAgICAgICApfVxuICAgICAgICB7YXBwcy5t
YXAoKGFwcCkgPT4gKFxuICAgICAgICAgIDxkaXYga2V5PXthcHAuY2Fub25pY2FsX2tleX0gY2xhc3NOYW1lPVwicm91bmRl
ZC1sZyBib3JkZXIgcC0zXCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT1cImZsZXggZmxleC13cmFwIGl0ZW1zLWJh
c2VsaW5lIGp1c3RpZnktYmV0d2VlbiBnYXAtMlwiPlxuICAgICAgICAgICAgICA8TGlua1xuICAgICAgICAgICAgICAgIGhy
ZWY9e2AvYXBwcy8ke2VuY29kZVVSSUNvbXBvbmVudChhcHAuY2Fub25pY2FsX2tleSl9YH1cbiAgICAgICAgICAgICAgICBj
bGFzc05hbWU9XCJmb250LW1lZGl1bSB0ZXh0LVtjb2xvcjp2YXIoLS1jb2xvci1hY2NlbnQpXSBob3Zlcjp1bmRlcmxpbmVc
IlxuICAgICAgICAgICAgICA+XG4gICAgICAgICAgICAgICAge2FwcC5hcHBfbmFtZSA/PyBhcHAuY2Fub25pY2FsX2tleX1c
biAgICAgICAgICAgICAgPC9MaW5rPlxuICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9XCJ0ZXh0LXhzIHRleHQtbXV0
ZWQtZm9yZWdyb3VuZFwiPnthcHAucGxhdGZvcm0gPz8gXCJcIn08L3NwYW4+XG4gICAgICAgICAgICA8L2Rpdj5cblxuICAg
ICAgICAgICAgey8qIFRoZSBudW1iZXJzIGZpcnN0OiB0aGV5IGFyZSB3aHkgdGhpcyBhcHAgaXMgd29ydGggc29tZW9uZSdz
IG1vcm5pbmcsIGFuZFxuICAgICAgICAgICAgICAgIHRoZXkgYXJlIHdoYXQgdGhlIHBlcnNvbiBkZWNpZGluZyB3aG8gb3du
cyBpdCBuZWVkcyB0byBzZWUuICovfVxuICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJtdC0yIGdyaWQgZ3JpZC1jb2xz
LTMgZ2FwLTIgdGV4dC1zbVwiPlxuICAgICAgICAgICAgICA8RmlndXJlIGxhYmVsPVwiUmV2ZW51ZVwiIHZhbHVlPXtmb3Jt
YXRUYWJsZVVTRChhcHAucmV2ZW51ZV91c2QpfSAvPlxuICAgICAgICAgICAgICA8RmlndXJlIGxhYmVsPVwiSW5zdGFsbHNc
IiB2YWx1ZT17Zm9ybWF0TnVtYmVyKGFwcC5pbnN0YWxscyl9IC8+XG4gICAgICAgICAgICAgIDxGaWd1cmUgbGFiZWw9XCJV
QSBjb3N0XCIgdmFsdWU9e2Zvcm1hdFRhYmxlVVNEKGFwcC51YV9zcGVuZF91c2QpfSAvPlxuICAgICAgICAgICAgPC9kaXY+
XG5cbiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPVwibXQtMiBmbGV4IGZsZXgtd3JhcCBpdGVtcy1jZW50ZXIgZ2FwLTFc
Ij5cbiAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPVwidGV4dC14cyB0ZXh0LW11dGVkLWZvcmVncm91bmRcIj5NaXNz
aW5nOjwvc3Bhbj5cbiAgICAgICAgICAgICAge2FwcC5taXNzaW5nLm1hcCgoZmllbGQpID0+IChcbiAgICAgICAgICAgICAg
ICA8QmFkZ2Uga2V5PXtmaWVsZH0gdmFyaWFudD1cIm91dGxpbmVcIiBjbGFzc05hbWU9XCJmb250LW5vcm1hbFwiPlxuICAg
ICAgICAgICAgICAgICAge2xhYmVsKGZpZWxkKX1cbiAgICAgICAgICAgICAgICA8L0JhZGdlPlxuICAgICAgICAgICAgICAp
KX1cbiAgICAgICAgICAgIDwvZGl2PlxuXG4gICAgICAgICAgICA8TGlua1xuICAgICAgICAgICAgICBocmVmPXtgL2FwcC1t
YXN0ZXI/c2VhcmNoPSR7ZW5jb2RlVVJJQ29tcG9uZW50KGFwcC5hcHBfbmFtZSA/PyBhcHAuY2Fub25pY2FsX2tleSl9YH1c
biAgICAgICAgICAgICAgY2xhc3NOYW1lPVwibXQtMiBpbmxpbmUtYmxvY2sgdGV4dC14cyB0ZXh0LVtjb2xvcjp2YXIoLS1j
b2xvci1hY2NlbnQpXSBob3Zlcjp1bmRlcmxpbmVcIlxuICAgICAgICAgICAgPlxuICAgICAgICAgICAgICBGaWxsIHRoZXNl
IGluIFx1MjE5MlxuICAgICAgICAgICAgPC9MaW5rPlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICApKX1cbiAgICAgIDwv
Q2FyZENvbnRlbnQ+XG4gICAgPC9DYXJkPlxuICApO1xufVxuXG5mdW5jdGlvbiBGaWd1cmUoeyBsYWJlbDogbmFtZSwgdmFs
dWUgfTogeyBsYWJlbDogc3RyaW5nOyB2YWx1ZTogc3RyaW5nIH0pIHtcbiAgcmV0dXJuIChcbiAgICA8ZGl2PlxuICAgICAg
PGRpdiBjbGFzc05hbWU9XCJ0ZXh0LVsxMXB4XSB1cHBlcmNhc2UgdHJhY2tpbmctd2lkZXIgdGV4dC1tdXRlZC1mb3JlZ3Jv
dW5kXCI+e25hbWV9PC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzTmFtZT1cInRhYnVsYXItbnVtc1wiPnt2YWx1ZX08L2Rpdj5c
biAgICA8L2Rpdj5cbiAgKTtcbn1cbiJ9LCAiZWRpdHMiOiBbeyJwYXRoIjogImJhY2tlbmQvYXBwL3NlcnZpY2VzL3Nwb3Rs
aWdodF9zZXJ2aWNlLnB5IiwgImFuY2hvciI6ICIgICAgICAgIFwid2luZG93c1wiOiB7XG4gICAgICAgICAgICBcImRheVwi
OiB7XCJmcm9tXCI6IGRheV9zdGFydC5pc29mb3JtYXQoKSwgXCJ0b1wiOiB0b2RheS5pc29mb3JtYXQoKX0sXG4gICAgICAg
ICAgICBcIndlZWtcIjoge1wiZnJvbVwiOiB3ZWVrX3N0YXJ0Lmlzb2Zvcm1hdCgpLCBcInRvXCI6IHRvZGF5Lmlzb2Zvcm1h
dCgpfSxcbiAgICAgICAgfSxcbiAgICB9IiwgInJlcGxhY2VtZW50IjogIiAgICAgICAgXCJ3aW5kb3dzXCI6IHtcbiAgICAg
ICAgICAgIFwiZGF5XCI6IHtcImZyb21cIjogZGF5X3N0YXJ0Lmlzb2Zvcm1hdCgpLCBcInRvXCI6IHRvZGF5Lmlzb2Zvcm1h
dCgpfSxcbiAgICAgICAgICAgIFwid2Vla1wiOiB7XCJmcm9tXCI6IHdlZWtfc3RhcnQuaXNvZm9ybWF0KCksIFwidG9cIjog
dG9kYXkuaXNvZm9ybWF0KCl9LFxuICAgICAgICB9LFxuICAgIH1cblxuXG5hc3luYyBkZWYgYm9hcmQoc2Vzc2lvbjogQXN5
bmNTZXNzaW9uLCBjb250ZXh0OiBVc2VyQ29udGV4dCkgLT4gZGljdFtzdHIsIEFueV06XG4gICAgXCJcIlwiRXZlcnkgc2Nv
cGVkIGFwcCB3aXRoIGl0cyBjdXJhdGVkIGZpZWxkcyBhbmQgd2hhdCBpcyBtaXNzaW5nIC0gdGhlIHdhbGwgdmlldy5cblxu
ICAgIFRoZSBzaG9ydGxpc3QgYW5zd2VycyBcIndoYXQgc2hvdWxkIEkgZml4IHRoaXMgbW9ybmluZ1wiOyB0aGlzIGFuc3dl
cnMgXCJob3cgYmFkIGlzIGl0XG4gICAgb3ZlcmFsbFwiLCBhbmQgaXQgbGlzdHMgQ09NUExFVEUgYXBwcyB0b28gLSBhIGZp
bGxlZC1pbiByZWNvcmQgdHVybnMgZ3JlZW4gcmF0aGVyIHRoYW5cbiAgICBkaXNhcHBlYXJpbmcsIHNvIFwiZG9uZVwiIHN0
YXlzIHZpc2libGUgaW5zdGVhZCBvZiBpbmRpc3Rpbmd1aXNoYWJsZSBmcm9tIFwiaW52aXNpYmxlXCIuXG5cbiAgICBPcmRl
cmVkIGJ5IG5hbWUsIG5vdCByZXZlbnVlOiBhIHdhbGwgaXMgZm9yIGZpbmRpbmcgYSBzcGVjaWZpYyBhcHAsIGFuZCBhbHBo
YWJldGljYWxcbiAgICBpcyB0aGUgb25lIG9yZGVyIGEgcGVyc29uIGNhbiBwcmVkaWN0LlxuICAgIFwiXCJcIlxuICAgIG1h
c3RlciA9IEFQUF9NQVNURVJfVEFCTEUuY1xuICAgIHNjb3BlID0gYnVpbGRfc2NvcGVfZmlsdGVyKGNvbnRleHQuc2NvcGVz
LCBjb2x1bW5zPV9tYXN0ZXJfc2NvcGVfY29sdW1ucygpKVxuICAgIHN0YXRlbWVudCA9IChcbiAgICAgICAgc2VsZWN0KFxu
ICAgICAgICAgICAgbWFzdGVyLmNhbm9uaWNhbF9rZXksXG4gICAgICAgICAgICBtYXN0ZXIuYXBwX25hbWUsXG4gICAgICAg
ICAgICBtYXN0ZXIucGxhdGZvcm0sXG4gICAgICAgICAgICAqW21hc3RlcltuYW1lXS5sYWJlbChuYW1lKSBmb3IgbmFtZSBp
biBSRVFVSVJFRF9GSUVMRFNdLFxuICAgICAgICApXG4gICAgICAgIC53aGVyZShzY29wZSlcbiAgICAgICAgLm9yZGVyX2J5
KFxuICAgICAgICAgICAgZnVuYy5sb3dlcihmdW5jLmNvYWxlc2NlKG1hc3Rlci5hcHBfbmFtZSwgbWFzdGVyLmNhbm9uaWNh
bF9rZXkpKSxcbiAgICAgICAgICAgIG1hc3Rlci5jYW5vbmljYWxfa2V5LFxuICAgICAgICApXG4gICAgKVxuICAgIHJvd3Mg
PSAoYXdhaXQgc2Vzc2lvbi5leGVjdXRlKHN0YXRlbWVudCkpLm1hcHBpbmdzKCkuYWxsKClcblxuICAgIGFwcHMgPSBbXVxu
ICAgIGZvciByb3cgaW4gcm93czpcbiAgICAgICAgbWlzc2luZyA9IFtcbiAgICAgICAgICAgIG5hbWVcbiAgICAgICAgICAg
IGZvciBuYW1lIGluIFJFUVVJUkVEX0ZJRUxEU1xuICAgICAgICAgICAgaWYgcm93LmdldChuYW1lKSBpcyBOb25lIG9yIHN0
cihyb3cuZ2V0KG5hbWUpKS5zdHJpcCgpID09IFwiXCJcbiAgICAgICAgXVxuICAgICAgICBhcHBzLmFwcGVuZChcbiAgICAg
ICAgICAgIHtcbiAgICAgICAgICAgICAgICBcImNhbm9uaWNhbF9rZXlcIjogcm93W1wiY2Fub25pY2FsX2tleVwiXSxcbiAg
ICAgICAgICAgICAgICBcImFwcF9uYW1lXCI6IHJvd1tcImFwcF9uYW1lXCJdLFxuICAgICAgICAgICAgICAgIFwicGxhdGZv
cm1cIjogcm93W1wicGxhdGZvcm1cIl0sXG4gICAgICAgICAgICAgICAgXCJmaWVsZHNcIjoge25hbWU6IHJvdy5nZXQobmFt
ZSkgZm9yIG5hbWUgaW4gUkVRVUlSRURfRklFTERTfSxcbiAgICAgICAgICAgICAgICBcIm1pc3NpbmdcIjogbWlzc2luZyxc
biAgICAgICAgICAgIH1cbiAgICAgICAgKVxuXG4gICAgaW5jb21wbGV0ZSA9IHN1bSgxIGZvciBhcHAgaW4gYXBwcyBpZiBh
cHBbXCJtaXNzaW5nXCJdKVxuICAgIHJldHVybiB7XG4gICAgICAgIFwicmVxdWlyZWRfZmllbGRzXCI6IGxpc3QoUkVRVUlS
RURfRklFTERTKSxcbiAgICAgICAgXCJ0b3RhbFwiOiBsZW4oYXBwcyksXG4gICAgICAgIFwiaW5jb21wbGV0ZVwiOiBpbmNv
bXBsZXRlLFxuICAgICAgICBcImNvbXBsZXRlXCI6IGxlbihhcHBzKSAtIGluY29tcGxldGUsXG4gICAgICAgIFwiYXBwc1wi
OiBhcHBzLFxuICAgIH0iLCAibWFya2VyIjogImFzeW5jIGRlZiBib2FyZChzZXNzaW9uOiBBc3luY1Nlc3Npb24sIGNvbnRl
eHQ6IFVzZXJDb250ZXh0KSJ9LCB7InBhdGgiOiAiYmFja2VuZC9hcHAvYXBpL3YxL3Nwb3RsaWdodC5weSIsICJhbmNob3Ii
OiAiICAgIHJldHVybiBhd2FpdCBzcG90bGlnaHRfc2VydmljZS5idWlsZChcbiAgICAgICAgZGIsIGNvbnRleHQsIFF1ZXJ5
QnVpbGRlcihjb250ZXh0KSwgZGF0ZS50b2RheSgpLCBsaW1pdD1saW1pdFxuICAgICkiLCAicmVwbGFjZW1lbnQiOiAiICAg
IHJldHVybiBhd2FpdCBzcG90bGlnaHRfc2VydmljZS5idWlsZChcbiAgICAgICAgZGIsIGNvbnRleHQsIFF1ZXJ5QnVpbGRl
cihjb250ZXh0KSwgZGF0ZS50b2RheSgpLCBsaW1pdD1saW1pdFxuICAgIClcblxuXG5Acm91dGVyLmdldChcIi9ib2FyZFwi
KVxuYXN5bmMgZGVmIHNwb3RsaWdodF9ib2FyZChjb250ZXh0OiBDdXJyZW50VXNlciwgZGI6IERiU2Vzc2lvbikgLT4gZGlj
dFtzdHIsIEFueV06XG4gICAgXCJcIlwiRXZlcnkgc2NvcGVkIGFwcCwgc2hhZGVkIGJ5IGNvbXBsZXRlbmVzcyAtIHRoZSB3
YWxsIGJlaGluZCB0aGUgc2hvcnRsaXN0LlxuXG4gICAgU2NvcGVkIGV4YWN0bHkgbGlrZSB0aGUgc2hvcnRsaXN0LCBmb3Ig
dGhlIHNhbWUgcmVhc29uOiB3aXRoIG5vIHJvdyBzY29wZSB0aGlzXG4gICAgcmV0dXJucyBOT1RISU5HLCBiZWNhdXNlIGJl
aW5nIHNob3duIGFuIGFwcCBpcyBiZWluZyB0b2xkIGl0IGV4aXN0cy5cbiAgICBcIlwiXCJcbiAgICByZXR1cm4gYXdhaXQg
c3BvdGxpZ2h0X3NlcnZpY2UuYm9hcmQoZGIsIGNvbnRleHQpIiwgIm1hcmtlciI6ICJAcm91dGVyLmdldChcIi9ib2FyZFwi
KSJ9LCB7InBhdGgiOiAiZnJvbnRlbmQvbGliL3R5cGVzLnRzIiwgImFuY2hvciI6ICJleHBvcnQgaW50ZXJmYWNlIFNwb3Rs
aWdodCB7XG4gIHJlcXVpcmVkX2ZpZWxkczogc3RyaW5nW107XG4gIGluY29tcGxldGVfY291bnQ6IG51bWJlcjtcbiAgb2Zf
dGhlX2RheTogU3BvdGxpZ2h0QXBwW107XG4gIG9mX3RoZV93ZWVrOiBTcG90bGlnaHRBcHBbXTtcbiAgd2luZG93czoge1xu
ICAgIGRheTogeyBmcm9tOiBzdHJpbmc7IHRvOiBzdHJpbmcgfTtcbiAgICB3ZWVrOiB7IGZyb206IHN0cmluZzsgdG86IHN0
cmluZyB9O1xuICB9O1xufSIsICJyZXBsYWNlbWVudCI6ICJleHBvcnQgaW50ZXJmYWNlIFNwb3RsaWdodCB7XG4gIHJlcXVp
cmVkX2ZpZWxkczogc3RyaW5nW107XG4gIGluY29tcGxldGVfY291bnQ6IG51bWJlcjtcbiAgb2ZfdGhlX2RheTogU3BvdGxp
Z2h0QXBwW107XG4gIG9mX3RoZV93ZWVrOiBTcG90bGlnaHRBcHBbXTtcbiAgd2luZG93czoge1xuICAgIGRheTogeyBmcm9t
OiBzdHJpbmc7IHRvOiBzdHJpbmcgfTtcbiAgICB3ZWVrOiB7IGZyb206IHN0cmluZzsgdG86IHN0cmluZyB9O1xuICB9O1xu
fVxuXG4vKiogT25lIHRpbGUgb24gdGhlIFNwb3RsaWdodCBib2FyZDogdGhlIGFwcCwgaXRzIGN1cmF0ZWQgZmllbGRzLCBh
bmQgd2hhdCBpcyBtaXNzaW5nLiAqL1xuZXhwb3J0IGludGVyZmFjZSBTcG90bGlnaHRCb2FyZEFwcCB7XG4gIGNhbm9uaWNh
bF9rZXk6IHN0cmluZztcbiAgYXBwX25hbWU6IHN0cmluZyB8IG51bGw7XG4gIHBsYXRmb3JtOiBzdHJpbmcgfCBudWxsO1xu
ICBmaWVsZHM6IFJlY29yZDxzdHJpbmcsIHN0cmluZyB8IG51bWJlciB8IG51bGw+O1xuICBtaXNzaW5nOiBzdHJpbmdbXTtc
bn1cblxuZXhwb3J0IGludGVyZmFjZSBTcG90bGlnaHRCb2FyZCB7XG4gIHJlcXVpcmVkX2ZpZWxkczogc3RyaW5nW107XG4g
IHRvdGFsOiBudW1iZXI7XG4gIGluY29tcGxldGU6IG51bWJlcjtcbiAgY29tcGxldGU6IG51bWJlcjtcbiAgYXBwczogU3Bv
dGxpZ2h0Qm9hcmRBcHBbXTtcbn0iLCAibWFya2VyIjogImV4cG9ydCBpbnRlcmZhY2UgU3BvdGxpZ2h0Qm9hcmRBcHAgeyJ9
LCB7InBhdGgiOiAiZnJvbnRlbmQvbGliL2FwaS1ob29rcy50cyIsICJhbmNob3IiOiAiICBCcmllZmluZyxcbiAgU3BvdGxp
Z2h0LCIsICJyZXBsYWNlbWVudCI6ICIgIEJyaWVmaW5nLFxuICBTcG90bGlnaHQsXG4gIFNwb3RsaWdodEJvYXJkLCIsICJt
YXJrZXIiOiAiICBTcG90bGlnaHRCb2FyZCwifSwgeyJwYXRoIjogImZyb250ZW5kL2xpYi9hcGktaG9va3MudHMiLCAiYW5j
aG9yIjogImV4cG9ydCBmdW5jdGlvbiB1c2VTcG90bGlnaHQoKSB7XG4gIGNvbnN0IHsgdXNlciB9ID0gdXNlQXV0aCgpO1xu
ICByZXR1cm4gdXNlUXVlcnkoe1xuICAgIHF1ZXJ5S2V5OiBbXCJzcG90bGlnaHRcIl0sXG4gICAgcXVlcnlGbjogKCkgPT4g
YXBpRmV0Y2g8U3BvdGxpZ2h0PihcIi9hcGkvdjEvc3BvdGxpZ2h0XCIpLFxuICAgIGVuYWJsZWQ6IEJvb2xlYW4odXNlciks
XG4gICAgLy8gU2hvcnQ6IHRoZSBwYW5lbCdzIHdob2xlIGpvYiBpcyB0byBlbXB0eSBhcyBwZW9wbGUgZmlsbCBmaWVsZHMg
aW4sIGFuZCBzaG93aW5nIGFcbiAgICAvLyBzdGFsZSBjb3B5IG9mIGl0c2VsZiBpcyB0aGUgb25lIGZhaWx1cmUgdGhhdCBt
YWtlcyBpdCB1bnRydXN0d29ydGh5LlxuICAgIHN0YWxlVGltZTogMzAgKiAxMDAwLFxuICB9KTtcbn0iLCAicmVwbGFjZW1l
bnQiOiAiZXhwb3J0IGZ1bmN0aW9uIHVzZVNwb3RsaWdodCgpIHtcbiAgY29uc3QgeyB1c2VyIH0gPSB1c2VBdXRoKCk7XG4g
IHJldHVybiB1c2VRdWVyeSh7XG4gICAgcXVlcnlLZXk6IFtcInNwb3RsaWdodFwiXSxcbiAgICBxdWVyeUZuOiAoKSA9PiBh
cGlGZXRjaDxTcG90bGlnaHQ+KFwiL2FwaS92MS9zcG90bGlnaHRcIiksXG4gICAgZW5hYmxlZDogQm9vbGVhbih1c2VyKSxc
biAgICAvLyBTaG9ydDogdGhlIHBhbmVsJ3Mgd2hvbGUgam9iIGlzIHRvIGVtcHR5IGFzIHBlb3BsZSBmaWxsIGZpZWxkcyBp
biwgYW5kIHNob3dpbmcgYVxuICAgIC8vIHN0YWxlIGNvcHkgb2YgaXRzZWxmIGlzIHRoZSBvbmUgZmFpbHVyZSB0aGF0IG1h
a2VzIGl0IHVudHJ1c3R3b3J0aHkuXG4gICAgc3RhbGVUaW1lOiAzMCAqIDEwMDAsXG4gIH0pO1xufVxuXG4vKiogVGhlIHdh
bGwgYmVoaW5kIHRoZSBzaG9ydGxpc3Q6IEVWRVJZIHNjb3BlZCBhcHAsIHNoYWRlZCBieSBjb21wbGV0ZW5lc3MuICovXG5l
eHBvcnQgZnVuY3Rpb24gdXNlU3BvdGxpZ2h0Qm9hcmQoKSB7XG4gIGNvbnN0IHsgdXNlciB9ID0gdXNlQXV0aCgpO1xuICBy
ZXR1cm4gdXNlUXVlcnkoe1xuICAgIHF1ZXJ5S2V5OiBbXCJzcG90bGlnaHQtYm9hcmRcIl0sXG4gICAgcXVlcnlGbjogKCkg
PT4gYXBpRmV0Y2g8U3BvdGxpZ2h0Qm9hcmQ+KFwiL2FwaS92MS9zcG90bGlnaHQvYm9hcmRcIiksXG4gICAgZW5hYmxlZDog
Qm9vbGVhbih1c2VyKSxcbiAgICBzdGFsZVRpbWU6IDMwICogMTAwMCxcbiAgfSk7XG59IiwgIm1hcmtlciI6ICJleHBvcnQg
ZnVuY3Rpb24gdXNlU3BvdGxpZ2h0Qm9hcmQoKSB7In0sIHsicGF0aCI6ICJiYWNrZW5kL3Rlc3RzL3Rlc3Rfc3BvdGxpZ2h0
LnB5IiwgImFuY2hvciI6ICIgICAgYXNzZXJ0IHJlc3VsdFtcImluY29tcGxldGVfY291bnRcIl0gPT0gMTJcbiAgICBhc3Nl
cnQgbGVuKHJlc3VsdFtcIm9mX3RoZV9kYXlcIl0pID09IHNwb3RsaWdodF9zZXJ2aWNlLlRPUF9OXG4gICAgYXNzZXJ0IHJl
c3VsdFtcIm9mX3RoZV9kYXlcIl1bMF1bXCJjYW5vbmljYWxfa2V5XCJdID09IFwiYXBwLTExXCIiLCAicmVwbGFjZW1lbnQi
OiAiICAgIGFzc2VydCByZXN1bHRbXCJpbmNvbXBsZXRlX2NvdW50XCJdID09IDEyXG4gICAgYXNzZXJ0IGxlbihyZXN1bHRb
XCJvZl90aGVfZGF5XCJdKSA9PSBzcG90bGlnaHRfc2VydmljZS5UT1BfTlxuICAgIGFzc2VydCByZXN1bHRbXCJvZl90aGVf
ZGF5XCJdWzBdW1wiY2Fub25pY2FsX2tleVwiXSA9PSBcImFwcC0xMVwiXG5cblxuYXN5bmMgZGVmIHRlc3RfdGhlX2JvYXJk
X2xpc3RzX2NvbXBsZXRlX2FwcHNfdG9vKGFwcF9tYXN0ZXJfc2Vzc2lvbjogQW55KSAtPiBOb25lOlxuICAgICMgVGhlIHdh
bGwgaXMgdGhlIHJlY29yZCwgbm90IHRoZSBhbGFybTogYSBmaWxsZWQtaW4gYXBwIHR1cm5zIGdyZWVuIHJhdGhlciB0aGFu
XG4gICAgIyBkaXNhcHBlYXJpbmcsIHNvIFwiZG9uZVwiIHN0YXlzIHZpc2libGUgaW5zdGVhZCBvZiBpbmRpc3Rpbmd1aXNo
YWJsZSBmcm9tIFwiaW52aXNpYmxlXCIuXG4gICAgYXdhaXQgX2FwcChhcHBfbWFzdGVyX3Nlc3Npb24sIFwiZG9uZVwiKVxu
ICAgIGF3YWl0IF9hcHAoYXBwX21hc3Rlcl9zZXNzaW9uLCBcImdhcFwiLCBwb2Rfb3duZXI9Tm9uZSlcbiAgICBhd2FpdCBh
cHBfbWFzdGVyX3Nlc3Npb24uY29tbWl0KClcblxuICAgIHJlc3VsdCA9IGF3YWl0IHNwb3RsaWdodF9zZXJ2aWNlLmJvYXJk
KGFwcF9tYXN0ZXJfc2Vzc2lvbiwgX2NvbnRleHQoWyhcImFsbFwiLCBOb25lKV0pKVxuXG4gICAgYXNzZXJ0IHJlc3VsdFtc
InRvdGFsXCJdID09IDJcbiAgICBhc3NlcnQgcmVzdWx0W1wiaW5jb21wbGV0ZVwiXSA9PSAxIGFuZCByZXN1bHRbXCJjb21w
bGV0ZVwiXSA9PSAxXG4gICAgYnlfa2V5ID0ge2FwcFtcImNhbm9uaWNhbF9rZXlcIl06IGFwcCBmb3IgYXBwIGluIHJlc3Vs
dFtcImFwcHNcIl19XG4gICAgYXNzZXJ0IGJ5X2tleVtcImRvbmVcIl1bXCJtaXNzaW5nXCJdID09IFtdXG4gICAgYXNzZXJ0
IGJ5X2tleVtcImdhcFwiXVtcIm1pc3NpbmdcIl0gPT0gW1wicG9kX293bmVyXCJdXG4gICAgYXNzZXJ0IGJ5X2tleVtcImdh
cFwiXVtcImZpZWxkc1wiXVtcInB1Ymxpc2hlclwiXSA9PSBcIlB1YkFcIlxuXG5cbmFzeW5jIGRlZiB0ZXN0X3RoZV9ib2Fy
ZF9pc19zY29wZWRfbGlrZV90aGVfc2hvcnRsaXN0KGFwcF9tYXN0ZXJfc2Vzc2lvbjogQW55KSAtPiBOb25lOlxuICAgIGF3
YWl0IF9hcHAoYXBwX21hc3Rlcl9zZXNzaW9uLCBcIm1pbmVcIiwgcG9kX293bmVyPU5vbmUpXG4gICAgYXdhaXQgX2FwcChh
cHBfbWFzdGVyX3Nlc3Npb24sIFwidGhlaXJzXCIsIGhvdT1cIkgyXCIsIHBvZD0yLCBwb2Rfb3duZXI9Tm9uZSlcbiAgICBh
d2FpdCBhcHBfbWFzdGVyX3Nlc3Npb24uY29tbWl0KClcblxuICAgIHJlc3VsdCA9IGF3YWl0IHNwb3RsaWdodF9zZXJ2aWNl
LmJvYXJkKGFwcF9tYXN0ZXJfc2Vzc2lvbiwgX2NvbnRleHQoWyhcImhvdVwiLCBcIkgxXCIpXSkpXG4gICAgYXNzZXJ0IFth
cHBbXCJjYW5vbmljYWxfa2V5XCJdIGZvciBhcHAgaW4gcmVzdWx0W1wiYXBwc1wiXV0gPT0gW1wibWluZVwiXVxuXG4gICAg
bm90aGluZyA9IGF3YWl0IHNwb3RsaWdodF9zZXJ2aWNlLmJvYXJkKGFwcF9tYXN0ZXJfc2Vzc2lvbiwgX2NvbnRleHQoW10p
KVxuICAgIGFzc2VydCBub3RoaW5nW1widG90YWxcIl0gPT0gMCBhbmQgbm90aGluZ1tcImFwcHNcIl0gPT0gW10iLCAibWFy
a2VyIjogImFzeW5jIGRlZiB0ZXN0X3RoZV9ib2FyZF9saXN0c19jb21wbGV0ZV9hcHBzX3RvbyJ9XX0=
"""



def resolve(text, anchor, replacement, marker):
    """Match against a file whose punctuation may have been normalised (em-dash -> hyphen).
    When the flattened form is the one that matches, flatten the replacement and marker
    too, or the patch reintroduces the very character the file was cleaned of."""
    if anchor in text:
        return anchor, replacement, marker
    flat = anchor.replace("\u2014", "-")
    if flat != anchor and flat in text:
        return flat, replacement.replace("\u2014", "-"), marker.replace("\u2014", "-")
    return anchor, replacement, marker


def locate(lines, anchor):
    """Line index where the longest present run of the anchor's own lines begins."""
    wanted = anchor.splitlines()
    joined = "\n".join(lines)
    for take in range(len(wanted), 0, -1):
        for start in (0, len(wanted) - take):
            probe = "\n".join(wanted[start:start + take])
            if not probe.strip():
                continue
            index = joined.find(probe)
            if index != -1:
                return joined.count("\n", 0, index) - start
    for offset, line in sorted(enumerate(wanted), key=lambda p: len(p[1].strip()), reverse=True):
        if len(line.strip()) < 12:
            break
        index = joined.find(line)
        if index != -1:
            return joined.count("\n", 0, index) - offset
    return None


def main():
    if not Path("frontend/app").is_dir() or not Path("backend/app").is_dir():
        print("ABORTED: run this from the repository root")
        return 1
    data = json.loads(base64.b64decode(PAYLOAD.strip()).decode())
    problems, failures, planned, skipped = [], [], {}, []

    for rel, content in data.get("new_files", {}).items():
        path = Path(rel)
        if path.exists() and path.read_text() == content:
            skipped.append(f"{rel}: already present and identical")
            continue
        planned[rel] = content

    for index, item in enumerate(data["edits"], start=1):
        rel = item["path"]
        path = Path(rel)
        if not path.exists():
            problems.append(f"  [{index}] {rel}: file not found")
            continue
        text = planned.get(rel, path.read_text())
        anchor, replacement, marker = resolve(text, item["anchor"], item["replacement"], item["marker"])
        if marker in text:
            skipped.append(f"{rel} [{index}]: already applied")
            continue
        found = text.count(anchor)
        if found != 1:
            head = anchor.splitlines()[0][:76]
            problems.append(f"  [{index}] {rel}: expected exactly 1 match, found {found}\n"
                            f"        anchor starts: {head!r}")
            failures.append((rel, anchor))
            continue
        planned[rel] = text.replace(anchor, replacement, 1)

    if problems:
        print("ABORTED - NOTHING was written. Every problem, so one round-trip fixes all:")
        print()
        for problem in problems:
            print(problem)
        shown = {}
        for rel, anchor in failures:
            lines = Path(rel).read_text().splitlines()
            hit = locate(lines, anchor)
            if hit is None:
                lo, hi = 0, min(len(lines), 120)
                note = "nothing from this anchor is on disk - head of file"
            else:
                lo, hi = max(0, hit - 30), min(len(lines), hit + 30)
                note = f"nearest partial match at line {hit + 1}"
            if any(lo >= a and hi <= b for a, b in shown.get(rel, [])):
                continue
            shown.setdefault(rel, []).append((lo, hi))
            print()
            print(f"----- {rel} lines {lo + 1}-{hi} of {len(lines)} ({note}) -----")
            for number, line in enumerate(lines[lo:hi], start=lo + 1):
                print(f"{number:6d}\t{line}")
        print()
        print("The regions above are what is actually on disk; I re-anchor from them.")
        return 1

    for rel, content in sorted(planned.items()):
        Path(rel).parent.mkdir(parents=True, exist_ok=True)
        Path(rel).write_text(content)
        print(f"wrote {rel}")
    for note in skipped:
        print(f"skip  {note}")
    if not planned:
        print("nothing to do - already applied")
    print()
    print(FOOTER)
    return 0


if __name__ == "__main__":
    sys.exit(main())
