#!/usr/bin/env python3
"""Bring the Spotlight WALL back - every app as a tile, shaded by completeness.

The earlier App Spotlight was a wall: every app_master_v2 record as a tile, red where
publisher / HOU / pod / pod owner / partner / share was missing, green where the record
was filled, with search and All / Needs update / Complete filters. The revenue-ordered
shortlist that replaced it answers a different question - and the owner wants both, so
now the page has both:

  * The SHORTLIST on top: "what should I fix this morning" - incomplete apps, worst by
    revenue, today and this week, with the numbers that justify the effort.
  * The BOARD below: "how bad is it overall" - every scoped app, shaded, searchable,
    each required field shown filled or Missing. Complete apps stay ON the board in
    green: done must be visible, not indistinguishable from invisible.

Same scoping as everything else (no scope = empty wall, because being shown an app is
being told it exists), same seven required fields derived from the editable set, and the
tiles route admins to App Master and everyone else to App Changes - the two doors these
records already have. Service + route + types + hook + tests + client.
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

FOOTER = 'Rebuild backend + frontend, then run both test suites.'

PAYLOAD = """
eyJuZXdfZmlsZXMiOiB7ImZyb250ZW5kL2NvbXBvbmVudHMvc3BvdGxpZ2h0L3Nwb3RsaWdodC1jbGllbnQudHN4IjogIlwi
dXNlIGNsaWVudFwiO1xuXG5pbXBvcnQgTGluayBmcm9tIFwibmV4dC9saW5rXCI7XG5pbXBvcnQgeyBBbGVydFRyaWFuZ2xl
LCBDaGVja0NpcmNsZTIgfSBmcm9tIFwibHVjaWRlLXJlYWN0XCI7XG5pbXBvcnQgeyB1c2VNZW1vLCB1c2VTdGF0ZSB9IGZy
b20gXCJyZWFjdFwiO1xuXG5pbXBvcnQgeyBQYWdlSGVhZGVyIH0gZnJvbSBcIkAvY29tcG9uZW50cy9sYXlvdXQvcGFnZS1o
ZWFkZXJcIjtcbmltcG9ydCB7IEJhZGdlIH0gZnJvbSBcIkAvY29tcG9uZW50cy91aS9iYWRnZVwiO1xuaW1wb3J0IHsgQ2Fy
ZCwgQ2FyZENvbnRlbnQsIENhcmRIZWFkZXIsIENhcmRUaXRsZSB9IGZyb20gXCJAL2NvbXBvbmVudHMvdWkvY2FyZFwiO1xu
aW1wb3J0IHsgU2tlbGV0b24gfSBmcm9tIFwiQC9jb21wb25lbnRzL3VpL3NrZWxldG9uXCI7XG5pbXBvcnQgeyB1c2VNZSwg
dXNlU3BvdGxpZ2h0LCB1c2VTcG90bGlnaHRCb2FyZCB9IGZyb20gXCJAL2xpYi9hcGktaG9va3NcIjtcbmltcG9ydCB7IGZv
cm1hdE51bWJlciwgZm9ybWF0VGFibGVVU0QgfSBmcm9tIFwiQC9saWIvZm9ybWF0XCI7XG5pbXBvcnQgeyBjbiB9IGZyb20g
XCJAL2xpYi91dGlsc1wiO1xuaW1wb3J0IHR5cGUgeyBTcG90bGlnaHRBcHAsIFNwb3RsaWdodEJvYXJkQXBwIH0gZnJvbSBc
IkAvbGliL3R5cGVzXCI7XG5cbi8qKiBIdW1hbiBsYWJlbHMgZm9yIHRoZSByZXF1aXJlZCBmaWVsZHMuIFRoZSBBUEkgcmV0
dXJucyBjb2x1bW4gbmFtZXM7IGEgcGVyc29uIGZpbGxpbmdcbiAqICB0aGUgZm9ybSBzaG91bGQgbm90IGhhdmUgdG8gdHJh
bnNsYXRlIGBuZXRfcmV2ZW51ZV9zaGFyZWAgaW4gdGhlaXIgaGVhZC4gKi9cbmNvbnN0IEZJRUxEX0xBQkVMUzogUmVjb3Jk
PHN0cmluZywgc3RyaW5nPiA9IHtcbiAgcHVibGlzaGVyOiBcIlB1Ymxpc2hlclwiLFxuICBob3U6IFwiSE9VXCIsXG4gIHBv
ZDogXCJQb2RcIixcbiAgcG9kX293bmVyOiBcIlBvZCBvd25lclwiLFxuICBwYXJ0bmVyX25hbWU6IFwiUGFydG5lciBuYW1l
XCIsXG4gIG5ldF9yZXZlbnVlX3NoYXJlOiBcIk5ldCByZXZlbnVlIHNoYXJlXCIsXG4gIHR5cGU6IFwiVHlwZVwiLFxufTtc
blxuZnVuY3Rpb24gbGFiZWwoZmllbGQ6IHN0cmluZyk6IHN0cmluZyB7XG4gIHJldHVybiBGSUVMRF9MQUJFTFNbZmllbGRd
ID8/IGZpZWxkO1xufVxuXG4vKiogQ2hpcCBvcmRlciBtaXJyb3JzIHRoZSBmb3JtIHBlb3BsZSBmaWxsLCBvd25lcnNoaXAg
Zmlyc3QuICovXG5jb25zdCBDSElQX09SREVSID0gW1xuICBcInB1Ymxpc2hlclwiLFxuICBcImhvdVwiLFxuICBcInBvZFwi
LFxuICBcInBvZF9vd25lclwiLFxuICBcInBhcnRuZXJfbmFtZVwiLFxuICBcIm5ldF9yZXZlbnVlX3NoYXJlXCIsXG4gIFwi
dHlwZVwiLFxuXTtcblxudHlwZSBCb2FyZEZpbHRlciA9IFwiYWxsXCIgfCBcIm5lZWRzXCIgfCBcImNvbXBsZXRlXCI7XG5c
bi8qKiBUd28gYW5zd2VycyBvbiBvbmUgcGFnZS5cbiAqXG4gKiAgVGhlIFNIT1JUTElTVCBvbiB0b3AgYW5zd2VycyBcIndo
YXQgc2hvdWxkIEkgZml4IHRoaXMgbW9ybmluZ1wiIC0gaW5jb21wbGV0ZSBhcHBzLFxuICogIHdvcnN0LWJ5LXJldmVudWUg
Zmlyc3QsIGZvciB0b2RheSBhbmQgZm9yIHRoZSB3ZWVrLCBlYWNoIHdpdGggdGhlIG51bWJlcnMgdGhhdCBtYWtlXG4gKiAg
aXQgd29ydGggc29tZW9uZSdzIHRpbWUuXG4gKlxuICogIFRoZSBCT0FSRCBiZWxvdyBhbnN3ZXJzIFwiaG93IGJhZCBpcyBp
dCBvdmVyYWxsXCIgLSBFVkVSWSBhcHAgdGhpcyBjYWxsZXIgY2FuIHNlZSxcbiAqICBzaGFkZWQgYnkgY29tcGxldGVuZXNz
LCBzZWFyY2hhYmxlLCB3aXRoIGVhY2ggcmVxdWlyZWQgZmllbGQgc2hvd24gZmlsbGVkIG9yIE1pc3NpbmcuXG4gKiAgQSBm
aWxsZWQtaW4gYXBwIHR1cm5zIGdyZWVuIHJhdGhlciB0aGFuIGRpc2FwcGVhcmluZywgc28gXCJkb25lXCIgc3RheXMgdmlz
aWJsZSBpbnN0ZWFkXG4gKiAgb2YgYmVjb21pbmcgaW5kaXN0aW5ndWlzaGFibGUgZnJvbSBcImludmlzaWJsZVwiLlxuICpc
biAqICBCb3RoIGFyZSBzY29wZWQgc2VydmVyLXNpZGU6IGJlaW5nIHNob3duIGFuIGFwcCBpcyBiZWluZyB0b2xkIGl0IGV4
aXN0cy4gKi9cbmV4cG9ydCBmdW5jdGlvbiBTcG90bGlnaHRDbGllbnQoKSB7XG4gIGNvbnN0IHsgZGF0YSwgaXNMb2FkaW5n
LCBpc0Vycm9yIH0gPSB1c2VTcG90bGlnaHQoKTtcblxuICByZXR1cm4gKFxuICAgIDxkaXYgY2xhc3NOYW1lPVwic3BhY2Ut
eS02XCI+XG4gICAgICA8UGFnZUhlYWRlciB0aXRsZT1cIkFwcCBTcG90bGlnaHRcIiAvPlxuXG4gICAgICB7aXNMb2FkaW5n
ICYmIDxTa2VsZXRvbiBjbGFzc05hbWU9XCJoLTY0IHctZnVsbFwiIC8+fVxuICAgICAge2lzRXJyb3IgJiYgKFxuICAgICAg
ICA8cCBjbGFzc05hbWU9XCJ0ZXh0LXNtIHRleHQtW2NvbG9yOnZhcigtLWNvbG9yLW5lZ2F0aXZlKV1cIj5cbiAgICAgICAg
ICBDb3VsZG4mYXBvczt0IGxvYWQgdGhlIHNwb3RsaWdodC5cbiAgICAgICAgPC9wPlxuICAgICAgKX1cblxuICAgICAge2Rh
dGEgJiYgZGF0YS5pbmNvbXBsZXRlX2NvdW50ID09PSAwICYmIChcbiAgICAgICAgPENhcmQ+XG4gICAgICAgICAgPENhcmRD
b250ZW50IGNsYXNzTmFtZT1cImZsZXggaXRlbXMtY2VudGVyIGdhcC0yIHB5LTYgdGV4dC1zbSB0ZXh0LW11dGVkLWZvcmVn
cm91bmRcIj5cbiAgICAgICAgICAgIDxDaGVja0NpcmNsZTIgY2xhc3NOYW1lPVwiaC00IHctNCB0ZXh0LVtjb2xvcjp2YXIo
LS1jb2xvci1wb3NpdGl2ZSldXCIgLz5cbiAgICAgICAgICAgIEV2ZXJ5IGFwcCB5b3UgY2FuIHNlZSBoYXMgaXRzIHBvZCwg
b3duZXIsIEhPVSwgcGFydG5lciwgc2hhcmUgYW5kIHR5cGUgZmlsbGVkIGluLlxuICAgICAgICAgIDwvQ2FyZENvbnRlbnQ+
XG4gICAgICAgIDwvQ2FyZD5cbiAgICAgICl9XG5cbiAgICAgIHtkYXRhICYmIGRhdGEuaW5jb21wbGV0ZV9jb3VudCA+IDAg
JiYgKFxuICAgICAgICA8PlxuICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPVwiZmxleCBmbGV4LXdyYXAgaXRlbXMtY2VudGVy
IGdhcC0yIHRleHQtc20gdGV4dC1tdXRlZC1mb3JlZ3JvdW5kXCI+XG4gICAgICAgICAgICA8QWxlcnRUcmlhbmdsZSBjbGFz
c05hbWU9XCJoLTQgdy00IHRleHQtW2NvbG9yOnZhcigtLWNvbG9yLW5lZ2F0aXZlKV1cIiAvPlxuICAgICAgICAgICAgPHNw
YW4+XG4gICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT1cImZvbnQtc2VtaWJvbGQgdGV4dC1mb3JlZ3JvdW5kIHRhYnVs
YXItbnVtc1wiPlxuICAgICAgICAgICAgICAgIHtmb3JtYXROdW1iZXIoZGF0YS5pbmNvbXBsZXRlX2NvdW50KX1cbiAgICAg
ICAgICAgICAgPC9zcGFuPntcIiBcIn1cbiAgICAgICAgICAgICAge2RhdGEuaW5jb21wbGV0ZV9jb3VudCA9PT0gMSA/IFwi
YXBwIGlzXCIgOiBcImFwcHMgYXJlXCJ9IG1pc3NpbmcgYXQgbGVhc3Qgb25lIG9me1wiIFwifVxuICAgICAgICAgICAgICB7
ZGF0YS5yZXF1aXJlZF9maWVsZHMubWFwKGxhYmVsKS5qb2luKFwiLCBcIil9LiBVbnRpbCB0aGV5IGFyZSBmaWxsZWQgaW4s
IHdoYXRcbiAgICAgICAgICAgICAgdGhlc2UgYXBwcyBlYXJuIGlzIGF0dHJpYnV0ZWQgdG8gbm9ib2R5LlxuICAgICAgICAg
ICAgPC9zcGFuPlxuICAgICAgICAgIDwvZGl2PlxuXG4gICAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJncmlkIGdhcC00IGxn
OmdyaWQtY29scy0yXCI+XG4gICAgICAgICAgICA8U3BvdGxpZ2h0TGlzdFxuICAgICAgICAgICAgICB0aXRsZT1cIlNwb3Rs
aWdodCBvZiB0aGUgZGF5XCJcbiAgICAgICAgICAgICAgc3VidGl0bGU9e2Ake2RhdGEud2luZG93cy5kYXkuZnJvbX0gXHUy
MDE0IGhpZ2hlc3QgcmV2ZW51ZSB0b2RheWB9XG4gICAgICAgICAgICAgIGFwcHM9e2RhdGEub2ZfdGhlX2RheX1cbiAgICAg
ICAgICAgIC8+XG4gICAgICAgICAgICA8U3BvdGxpZ2h0TGlzdFxuICAgICAgICAgICAgICB0aXRsZT1cIlNwb3RsaWdodCBv
ZiB0aGUgd2Vla1wiXG4gICAgICAgICAgICAgIHN1YnRpdGxlPXtgJHtkYXRhLndpbmRvd3Mud2Vlay5mcm9tfSB0byAke2Rh
dGEud2luZG93cy53ZWVrLnRvfWB9XG4gICAgICAgICAgICAgIGFwcHM9e2RhdGEub2ZfdGhlX3dlZWt9XG4gICAgICAgICAg
ICAvPlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8Lz5cbiAgICAgICl9XG5cbiAgICAgIDxTcG90bGlnaHRCb2FyZCAv
PlxuICAgIDwvZGl2PlxuICApO1xufVxuXG4vKiogVGhlIHdhbGw6IGV2ZXJ5IHNjb3BlZCBhcHAgYXMgYSB0aWxlLCByZWQg
d2hlcmUgdGhlIHJlY29yZCBoYXMgaG9sZXMsIGdyZWVuIHdoZXJlIGl0XG4gKiAgaXMgZmlsbGVkLiBDbGljayBhIHRpbGUg
dG8gZ28gZml4IGl0LiAqL1xuZnVuY3Rpb24gU3BvdGxpZ2h0Qm9hcmQoKSB7XG4gIGNvbnN0IGJvYXJkID0gdXNlU3BvdGxp
Z2h0Qm9hcmQoKTtcbiAgY29uc3QgeyBkYXRhOiBtZSB9ID0gdXNlTWUoKTtcbiAgY29uc3QgW2ZpbHRlciwgc2V0RmlsdGVy
XSA9IHVzZVN0YXRlPEJvYXJkRmlsdGVyPihcImFsbFwiKTtcbiAgY29uc3QgW3F1ZXJ5LCBzZXRRdWVyeV0gPSB1c2VTdGF0
ZShcIlwiKTtcblxuICBjb25zdCBpc0FkbWluID0gbWU/LmNhcGFiaWxpdGllcy5pbmNsdWRlcyhcImFkbWluX3BhbmVsXCIp
ID8/IGZhbHNlO1xuICBjb25zdCBhcHBzID0gYm9hcmQuZGF0YT8uYXBwcyA/PyBbXTtcblxuICBjb25zdCBzaG93biA9IHVz
ZU1lbW8oKCkgPT4ge1xuICAgIGNvbnN0IHEgPSBxdWVyeS50cmltKCkudG9Mb3dlckNhc2UoKTtcbiAgICByZXR1cm4gYXBw
cy5maWx0ZXIoKGFwcCkgPT4ge1xuICAgICAgaWYgKGZpbHRlciA9PT0gXCJuZWVkc1wiICYmIGFwcC5taXNzaW5nLmxlbmd0
aCA9PT0gMCkgcmV0dXJuIGZhbHNlO1xuICAgICAgaWYgKGZpbHRlciA9PT0gXCJjb21wbGV0ZVwiICYmIGFwcC5taXNzaW5n
Lmxlbmd0aCA+IDApIHJldHVybiBmYWxzZTtcbiAgICAgIGlmICghcSkgcmV0dXJuIHRydWU7XG4gICAgICByZXR1cm4gKFxu
ICAgICAgICAoYXBwLmFwcF9uYW1lID8/IFwiXCIpLnRvTG93ZXJDYXNlKCkuaW5jbHVkZXMocSkgfHxcbiAgICAgICAgYXBw
LmNhbm9uaWNhbF9rZXkudG9Mb3dlckNhc2UoKS5pbmNsdWRlcyhxKVxuICAgICAgKTtcbiAgICB9KTtcbiAgfSwgW2FwcHMs
IGZpbHRlciwgcXVlcnldKTtcblxuICBpZiAoYm9hcmQuaXNMb2FkaW5nKSByZXR1cm4gPFNrZWxldG9uIGNsYXNzTmFtZT1c
ImgtOTYgdy1mdWxsXCIgLz47XG4gIGlmIChib2FyZC5pc0Vycm9yKSB7XG4gICAgcmV0dXJuIChcbiAgICAgIDxwIGNsYXNz
TmFtZT1cInRleHQtc20gdGV4dC1bY29sb3I6dmFyKC0tY29sb3ItbmVnYXRpdmUpXVwiPlxuICAgICAgICBDb3VsZG4mYXBv
czt0IGxvYWQgdGhlIGJvYXJkLlxuICAgICAgPC9wPlxuICAgICk7XG4gIH1cbiAgaWYgKCFib2FyZC5kYXRhIHx8IGJvYXJk
LmRhdGEudG90YWwgPT09IDApIHJldHVybiBudWxsO1xuXG4gIGNvbnN0IGZpZWxkcyA9IGJvYXJkLmRhdGEucmVxdWlyZWRf
ZmllbGRzXG4gICAgLnNsaWNlKClcbiAgICAuc29ydCgoYSwgYikgPT4gQ0hJUF9PUkRFUi5pbmRleE9mKGEpIC0gQ0hJUF9P
UkRFUi5pbmRleE9mKGIpKTtcblxuICByZXR1cm4gKFxuICAgIDxkaXYgY2xhc3NOYW1lPVwic3BhY2UteS00XCI+XG4gICAg
ICA8ZGl2PlxuICAgICAgICA8aDIgY2xhc3NOYW1lPVwiZm9udC1kaXNwbGF5IHRleHQtbGcgdHJhY2tpbmctdGlnaHRcIj5F
dmVyeSBhcHAsIHNoYWRlZCBieSBjb21wbGV0ZW5lc3M8L2gyPlxuICAgICAgICA8cCBjbGFzc05hbWU9XCJ0ZXh0LXNtIHRl
eHQtbXV0ZWQtZm9yZWdyb3VuZFwiPlxuICAgICAgICAgIFJlZCB3aGVyZSB7ZmllbGRzLm1hcChsYWJlbCkuam9pbihcIiwg
XCIpLnRvTG93ZXJDYXNlKCl9IGlzIG1pc3NpbmcsIGdyZWVuIHdoZXJlIHRoZVxuICAgICAgICAgIHJlY29yZCBpcyBmaWxs
ZWQuIENsaWNrIGEgdGlsZSB0byBlZGl0IGl0LlxuICAgICAgICA8L3A+XG4gICAgICA8L2Rpdj5cblxuICAgICAgPGRpdiBj
bGFzc05hbWU9XCJmbGV4IGZsZXgtd3JhcCBpdGVtcy1jZW50ZXIgZ2FwLTJcIj5cbiAgICAgICAgPHNwYW5cbiAgICAgICAg
ICBjbGFzc05hbWU9XCJpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTEuNSByb3VuZGVkLW1kIGJvcmRlciBweC0yLjUg
cHktMSB0ZXh0LXhzXCJcbiAgICAgICAgICBzdHlsZT17e1xuICAgICAgICAgICAgYm9yZGVyQ29sb3I6IFwiY29sb3ItbWl4
KGluIHNyZ2IsIHZhcigtLWNvbG9yLW5lZ2F0aXZlKSAzNSUsIHRyYW5zcGFyZW50KVwiLFxuICAgICAgICAgICAgYmFja2dy
b3VuZDogXCJjb2xvci1taXgoaW4gc3JnYiwgdmFyKC0tY29sb3ItbmVnYXRpdmUpIDYlLCB0cmFuc3BhcmVudClcIixcbiAg
ICAgICAgICB9fVxuICAgICAgICA+XG4gICAgICAgICAgPEFsZXJ0VHJpYW5nbGUgY2xhc3NOYW1lPVwiaC0zLjUgdy0zLjUg
dGV4dC1bY29sb3I6dmFyKC0tY29sb3ItbmVnYXRpdmUpXVwiIC8+XG4gICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPVwiZm9u
dC1zZW1pYm9sZCB0YWJ1bGFyLW51bXNcIj57Zm9ybWF0TnVtYmVyKGJvYXJkLmRhdGEuaW5jb21wbGV0ZSl9PC9zcGFuPlxu
ICAgICAgICAgIG5lZWQgdXBkYXRpbmdcbiAgICAgICAgPC9zcGFuPlxuICAgICAgICA8c3BhblxuICAgICAgICAgIGNsYXNz
TmFtZT1cImlubGluZS1mbGV4IGl0ZW1zLWNlbnRlciBnYXAtMS41IHJvdW5kZWQtbWQgYm9yZGVyIHB4LTIuNSBweS0xIHRl
eHQteHNcIlxuICAgICAgICAgIHN0eWxlPXt7XG4gICAgICAgICAgICBib3JkZXJDb2xvcjogXCJjb2xvci1taXgoaW4gc3Jn
YiwgdmFyKC0tY29sb3ItcG9zaXRpdmUpIDM1JSwgdHJhbnNwYXJlbnQpXCIsXG4gICAgICAgICAgICBiYWNrZ3JvdW5kOiBc
ImNvbG9yLW1peChpbiBzcmdiLCB2YXIoLS1jb2xvci1wb3NpdGl2ZSkgNiUsIHRyYW5zcGFyZW50KVwiLFxuICAgICAgICAg
IH19XG4gICAgICAgID5cbiAgICAgICAgICA8Q2hlY2tDaXJjbGUyIGNsYXNzTmFtZT1cImgtMy41IHctMy41IHRleHQtW2Nv
bG9yOnZhcigtLWNvbG9yLXBvc2l0aXZlKV1cIiAvPlxuICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT1cImZvbnQtc2VtaWJv
bGQgdGFidWxhci1udW1zXCI+e2Zvcm1hdE51bWJlcihib2FyZC5kYXRhLmNvbXBsZXRlKX08L3NwYW4+XG4gICAgICAgICAg
Y29tcGxldGVcbiAgICAgICAgPC9zcGFuPlxuXG4gICAgICAgIDxkaXYgY2xhc3NOYW1lPVwibWwtYXV0byBmbGV4IGZsZXgt
d3JhcCBpdGVtcy1jZW50ZXIgZ2FwLTJcIj5cbiAgICAgICAgICA8aW5wdXRcbiAgICAgICAgICAgIHZhbHVlPXtxdWVyeX1c
biAgICAgICAgICAgIG9uQ2hhbmdlPXsoZXZlbnQpID0+IHNldFF1ZXJ5KGV2ZW50LnRhcmdldC52YWx1ZSl9XG4gICAgICAg
ICAgICBwbGFjZWhvbGRlcj1cIkZpbmQgYW4gYXBwXCJcbiAgICAgICAgICAgIGFyaWEtbGFiZWw9XCJGaW5kIGFuIGFwcFwi
XG4gICAgICAgICAgICBjbGFzc05hbWU9XCJoLTggdy1mdWxsIHJvdW5kZWQtbWQgYm9yZGVyIGJnLXRyYW5zcGFyZW50IHB4
LTMgdGV4dC1zbSBvdXRsaW5lLW5vbmUgcGxhY2Vob2xkZXI6dGV4dC1tdXRlZC1mb3JlZ3JvdW5kIGZvY3VzOmJvcmRlci1b
Y29sb3I6dmFyKC0tY29sb3ItYWNjZW50KV0gc206dy01NlwiXG4gICAgICAgICAgLz5cbiAgICAgICAgICA8ZGl2IGNsYXNz
TmFtZT1cImZsZXggb3ZlcmZsb3ctaGlkZGVuIHJvdW5kZWQtbWQgYm9yZGVyIHRleHQteHNcIj5cbiAgICAgICAgICAgIHso
XG4gICAgICAgICAgICAgIFtcbiAgICAgICAgICAgICAgICBbXCJhbGxcIiwgXCJBbGxcIl0sXG4gICAgICAgICAgICAgICAg
W1wibmVlZHNcIiwgXCJOZWVkcyB1cGRhdGVcIl0sXG4gICAgICAgICAgICAgICAgW1wiY29tcGxldGVcIiwgXCJDb21wbGV0
ZVwiXSxcbiAgICAgICAgICAgICAgXSBhcyBbQm9hcmRGaWx0ZXIsIHN0cmluZ11bXVxuICAgICAgICAgICAgKS5tYXAoKFt2
YWx1ZSwgdGV4dF0pID0+IChcbiAgICAgICAgICAgICAgPGJ1dHRvblxuICAgICAgICAgICAgICAgIGtleT17dmFsdWV9XG4g
ICAgICAgICAgICAgICAgdHlwZT1cImJ1dHRvblwiXG4gICAgICAgICAgICAgICAgb25DbGljaz17KCkgPT4gc2V0RmlsdGVy
KHZhbHVlKX1cbiAgICAgICAgICAgICAgICBjbGFzc05hbWU9e2NuKFxuICAgICAgICAgICAgICAgICAgXCJweC0yLjUgcHkt
MS41XCIsXG4gICAgICAgICAgICAgICAgICBmaWx0ZXIgPT09IHZhbHVlXG4gICAgICAgICAgICAgICAgICAgID8gXCJiZy1b
Y29sb3I6dmFyKC0tY29sb3ItYWNjZW50KV0gZm9udC1tZWRpdW0gdGV4dC1bY29sb3I6dmFyKC0tY29sb3ItYWNjZW50LWZv
cmVncm91bmQpXVwiXG4gICAgICAgICAgICAgICAgICAgIDogXCJ0ZXh0LW11dGVkLWZvcmVncm91bmQgaG92ZXI6dGV4dC1m
b3JlZ3JvdW5kXCIsXG4gICAgICAgICAgICAgICAgKX1cbiAgICAgICAgICAgICAgPlxuICAgICAgICAgICAgICAgIHt0ZXh0
fVxuICAgICAgICAgICAgICA8L2J1dHRvbj5cbiAgICAgICAgICAgICkpfVxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8
L2Rpdj5cbiAgICAgIDwvZGl2PlxuXG4gICAgICB7c2hvd24ubGVuZ3RoID09PSAwID8gKFxuICAgICAgICA8cCBjbGFzc05h
bWU9XCJweS04IHRleHQtY2VudGVyIHRleHQtc20gdGV4dC1tdXRlZC1mb3JlZ3JvdW5kXCI+XG4gICAgICAgICAgTm8gYXBw
IG1hdGNoZXMgdGhpcyBzZWFyY2ggYW5kIGZpbHRlci5cbiAgICAgICAgPC9wPlxuICAgICAgKSA6IChcbiAgICAgICAgPGRp
diBjbGFzc05hbWU9XCJncmlkIGdhcC0zIG1kOmdyaWQtY29scy0yIHhsOmdyaWQtY29scy0zXCI+XG4gICAgICAgICAge3No
b3duLm1hcCgoYXBwKSA9PiAoXG4gICAgICAgICAgICA8Qm9hcmRUaWxlIGtleT17YXBwLmNhbm9uaWNhbF9rZXl9IGFwcD17
YXBwfSBmaWVsZHM9e2ZpZWxkc30gaXNBZG1pbj17aXNBZG1pbn0gLz5cbiAgICAgICAgICApKX1cbiAgICAgICAgPC9kaXY+
XG4gICAgICApfVxuICAgIDwvZGl2PlxuICApO1xufVxuXG5mdW5jdGlvbiBCb2FyZFRpbGUoe1xuICBhcHAsXG4gIGZpZWxk
cyxcbiAgaXNBZG1pbixcbn06IHtcbiAgYXBwOiBTcG90bGlnaHRCb2FyZEFwcDtcbiAgZmllbGRzOiBzdHJpbmdbXTtcbiAg
aXNBZG1pbjogYm9vbGVhbjtcbn0pIHtcbiAgY29uc3QgbWlzc2luZyA9IG5ldyBTZXQoYXBwLm1pc3NpbmcpO1xuICBjb25z
dCBpbmNvbXBsZXRlID0gbWlzc2luZy5zaXplID4gMDtcbiAgY29uc3QgdG9uZSA9IGluY29tcGxldGUgPyBcIi0tY29sb3It
bmVnYXRpdmVcIiA6IFwiLS1jb2xvci1wb3NpdGl2ZVwiO1xuICAvLyBBZG1pbnMgZWRpdCBpbiBBcHAgTWFzdGVyOyBldmVy
eW9uZSBlbHNlIHByb3Bvc2VzIHRoZSBjaGFuZ2UgdGhyb3VnaCBBcHAgQ2hhbmdlcyAtXG4gIC8vIHRoZSBzYW1lIHR3byBk
b29ycyB0aGVzZSByZWNvcmRzIGFscmVhZHkgaGF2ZS5cbiAgY29uc3QgZWRpdEhyZWYgPSBpc0FkbWluXG4gICAgPyBgL2Fw
cC1tYXN0ZXI/c2VhcmNoPSR7ZW5jb2RlVVJJQ29tcG9uZW50KGFwcC5hcHBfbmFtZSA/PyBhcHAuY2Fub25pY2FsX2tleSl9
YFxuICAgIDogXCIvYXBwLWNoYW5nZXNcIjtcblxuICByZXR1cm4gKFxuICAgIDxMaW5rXG4gICAgICBocmVmPXtlZGl0SHJl
Zn1cbiAgICAgIGNsYXNzTmFtZT1cImJsb2NrIHJvdW5kZWQtbGcgYm9yZGVyIHAtNCB0cmFuc2l0aW9uLXNoYWRvdyBob3Zl
cjpzaGFkb3ctbWRcIlxuICAgICAgc3R5bGU9e3tcbiAgICAgICAgYm9yZGVyQ29sb3I6IGBjb2xvci1taXgoaW4gc3JnYiwg
dmFyKCR7dG9uZX0pIDM1JSwgdHJhbnNwYXJlbnQpYCxcbiAgICAgICAgYmFja2dyb3VuZDogYGNvbG9yLW1peChpbiBzcmdi
LCB2YXIoJHt0b25lfSkgNSUsIHRyYW5zcGFyZW50KWAsXG4gICAgICB9fVxuICAgID5cbiAgICAgIDxkaXYgY2xhc3NOYW1l
PVwiZmxleCBpdGVtcy1zdGFydCBqdXN0aWZ5LWJldHdlZW4gZ2FwLTJcIj5cbiAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJt
aW4tdy0wXCI+XG4gICAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJ0cnVuY2F0ZSBmb250LW1lZGl1bVwiPnthcHAuYXBwX25h
bWUgPz8gYXBwLmNhbm9uaWNhbF9rZXl9PC9kaXY+XG4gICAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJ0cnVuY2F0ZSB0ZXh0
LXhzIHRleHQtbXV0ZWQtZm9yZWdyb3VuZFwiPnthcHAuY2Fub25pY2FsX2tleX08L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4g
ICAgICAgIHtpbmNvbXBsZXRlICYmIChcbiAgICAgICAgICA8c3BhblxuICAgICAgICAgICAgY2xhc3NOYW1lPVwic2hyaW5r
LTAgcm91bmRlZCBweC0xLjUgcHktMC41IHRleHQtWzEwcHhdIGZvbnQtc2VtaWJvbGQgdXBwZXJjYXNlIHRyYWNraW5nLXdp
ZGVyIHRleHQtW2NvbG9yOnZhcigtLWNvbG9yLW5lZ2F0aXZlKV1cIlxuICAgICAgICAgICAgc3R5bGU9e3sgYmFja2dyb3Vu
ZDogXCJjb2xvci1taXgoaW4gc3JnYiwgdmFyKC0tY29sb3ItbmVnYXRpdmUpIDEwJSwgdHJhbnNwYXJlbnQpXCIgfX1cbiAg
ICAgICAgICA+XG4gICAgICAgICAgICB7bWlzc2luZy5zaXplfSBtaXNzaW5nXG4gICAgICAgICAgPC9zcGFuPlxuICAgICAg
ICApfVxuICAgICAgPC9kaXY+XG5cbiAgICAgIDxkaXYgY2xhc3NOYW1lPVwibXQtMyBmbGV4IGZsZXgtd3JhcCBnYXAtMS41
XCI+XG4gICAgICAgIHtmaWVsZHMubWFwKChmaWVsZCkgPT4ge1xuICAgICAgICAgIGNvbnN0IGFic2VudCA9IG1pc3Npbmcu
aGFzKGZpZWxkKTtcbiAgICAgICAgICBjb25zdCB2YWx1ZSA9IGFwcC5maWVsZHNbZmllbGRdO1xuICAgICAgICAgIHJldHVy
biAoXG4gICAgICAgICAgICA8c3BhblxuICAgICAgICAgICAgICBrZXk9e2ZpZWxkfVxuICAgICAgICAgICAgICBjbGFzc05h
bWU9XCJyb3VuZGVkLWZ1bGwgYm9yZGVyIHB4LTIgcHktMC41IHRleHQtWzExcHhdXCJcbiAgICAgICAgICAgICAgc3R5bGU9
e3tcbiAgICAgICAgICAgICAgICBib3JkZXJDb2xvcjogYGNvbG9yLW1peChpbiBzcmdiLCB2YXIoJHthYnNlbnQgPyBcIi0t
Y29sb3ItbmVnYXRpdmVcIiA6IFwiLS1jb2xvci1wb3NpdGl2ZVwifSkgMzAlLCB0cmFuc3BhcmVudClgLFxuICAgICAgICAg
ICAgICAgIGJhY2tncm91bmQ6IGBjb2xvci1taXgoaW4gc3JnYiwgdmFyKCR7YWJzZW50ID8gXCItLWNvbG9yLW5lZ2F0aXZl
XCIgOiBcIi0tY29sb3ItcG9zaXRpdmVcIn0pIDclLCB0cmFuc3BhcmVudClgLFxuICAgICAgICAgICAgICB9fVxuICAgICAg
ICAgICAgPlxuICAgICAgICAgICAgICB7bGFiZWwoZmllbGQpfToge2Fic2VudCA/IFwiTWlzc2luZ1wiIDogU3RyaW5nKHZh
bHVlKX1cbiAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICApO1xuICAgICAgICB9KX1cbiAgICAgIDwvZGl2PlxuICAg
IDwvTGluaz5cbiAgKTtcbn1cblxuZnVuY3Rpb24gU3BvdGxpZ2h0TGlzdCh7XG4gIHRpdGxlLFxuICBzdWJ0aXRsZSxcbiAg
YXBwcyxcbn06IHtcbiAgdGl0bGU6IHN0cmluZztcbiAgc3VidGl0bGU6IHN0cmluZztcbiAgYXBwczogU3BvdGxpZ2h0QXBw
W107XG59KSB7XG4gIHJldHVybiAoXG4gICAgPENhcmQ+XG4gICAgICA8Q2FyZEhlYWRlcj5cbiAgICAgICAgPENhcmRUaXRs
ZT57dGl0bGV9PC9DYXJkVGl0bGU+XG4gICAgICAgIDxwIGNsYXNzTmFtZT1cInRleHQteHMgdGV4dC1tdXRlZC1mb3JlZ3Jv
dW5kXCI+e3N1YnRpdGxlfTwvcD5cbiAgICAgIDwvQ2FyZEhlYWRlcj5cbiAgICAgIDxDYXJkQ29udGVudCBjbGFzc05hbWU9
XCJzcGFjZS15LTNcIj5cbiAgICAgICAge2FwcHMubGVuZ3RoID09PSAwICYmIChcbiAgICAgICAgICA8cCBjbGFzc05hbWU9
XCJ0ZXh0LXNtIHRleHQtbXV0ZWQtZm9yZWdyb3VuZFwiPk5vdGhpbmcgdG8gc2hvdyBmb3IgdGhpcyB3aW5kb3cuPC9wPlxu
ICAgICAgICApfVxuICAgICAgICB7YXBwcy5tYXAoKGFwcCkgPT4gKFxuICAgICAgICAgIDxkaXYga2V5PXthcHAuY2Fub25p
Y2FsX2tleX0gY2xhc3NOYW1lPVwicm91bmRlZC1sZyBib3JkZXIgcC0zXCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzTmFt
ZT1cImZsZXggZmxleC13cmFwIGl0ZW1zLWJhc2VsaW5lIGp1c3RpZnktYmV0d2VlbiBnYXAtMlwiPlxuICAgICAgICAgICAg
ICA8TGlua1xuICAgICAgICAgICAgICAgIGhyZWY9e2AvYXBwcy8ke2VuY29kZVVSSUNvbXBvbmVudChhcHAuY2Fub25pY2Fs
X2tleSl9YH1cbiAgICAgICAgICAgICAgICBjbGFzc05hbWU9XCJmb250LW1lZGl1bSB0ZXh0LVtjb2xvcjp2YXIoLS1jb2xv
ci1hY2NlbnQpXSBob3Zlcjp1bmRlcmxpbmVcIlxuICAgICAgICAgICAgICA+XG4gICAgICAgICAgICAgICAge2FwcC5hcHBf
bmFtZSA/PyBhcHAuY2Fub25pY2FsX2tleX1cbiAgICAgICAgICAgICAgPC9MaW5rPlxuICAgICAgICAgICAgICA8c3BhbiBj
bGFzc05hbWU9XCJ0ZXh0LXhzIHRleHQtbXV0ZWQtZm9yZWdyb3VuZFwiPnthcHAucGxhdGZvcm0gPz8gXCJcIn08L3NwYW4+
XG4gICAgICAgICAgICA8L2Rpdj5cblxuICAgICAgICAgICAgey8qIFRoZSBudW1iZXJzIGZpcnN0OiB0aGV5IGFyZSB3aHkg
dGhpcyBhcHAgaXMgd29ydGggc29tZW9uZSdzIG1vcm5pbmcsIGFuZFxuICAgICAgICAgICAgICAgIHRoZXkgYXJlIHdoYXQg
dGhlIHBlcnNvbiBkZWNpZGluZyB3aG8gb3ducyBpdCBuZWVkcyB0byBzZWUuICovfVxuICAgICAgICAgICAgPGRpdiBjbGFz
c05hbWU9XCJtdC0yIGdyaWQgZ3JpZC1jb2xzLTMgZ2FwLTIgdGV4dC1zbVwiPlxuICAgICAgICAgICAgICA8RmlndXJlIGxh
YmVsPVwiUmV2ZW51ZVwiIHZhbHVlPXtmb3JtYXRUYWJsZVVTRChhcHAucmV2ZW51ZV91c2QpfSAvPlxuICAgICAgICAgICAg
ICA8RmlndXJlIGxhYmVsPVwiSW5zdGFsbHNcIiB2YWx1ZT17Zm9ybWF0TnVtYmVyKGFwcC5pbnN0YWxscyl9IC8+XG4gICAg
ICAgICAgICAgIDxGaWd1cmUgbGFiZWw9XCJVQSBjb3N0XCIgdmFsdWU9e2Zvcm1hdFRhYmxlVVNEKGFwcC51YV9zcGVuZF91
c2QpfSAvPlxuICAgICAgICAgICAgPC9kaXY+XG5cbiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPVwibXQtMiBmbGV4IGZs
ZXgtd3JhcCBpdGVtcy1jZW50ZXIgZ2FwLTFcIj5cbiAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPVwidGV4dC14cyB0
ZXh0LW11dGVkLWZvcmVncm91bmRcIj5NaXNzaW5nOjwvc3Bhbj5cbiAgICAgICAgICAgICAge2FwcC5taXNzaW5nLm1hcCgo
ZmllbGQpID0+IChcbiAgICAgICAgICAgICAgICA8QmFkZ2Uga2V5PXtmaWVsZH0gdmFyaWFudD1cIm91dGxpbmVcIiBjbGFz
c05hbWU9XCJmb250LW5vcm1hbFwiPlxuICAgICAgICAgICAgICAgICAge2xhYmVsKGZpZWxkKX1cbiAgICAgICAgICAgICAg
ICA8L0JhZGdlPlxuICAgICAgICAgICAgICApKX1cbiAgICAgICAgICAgIDwvZGl2PlxuXG4gICAgICAgICAgICA8TGlua1xu
ICAgICAgICAgICAgICBocmVmPXtgL2FwcC1tYXN0ZXI/c2VhcmNoPSR7ZW5jb2RlVVJJQ29tcG9uZW50KGFwcC5hcHBfbmFt
ZSA/PyBhcHAuY2Fub25pY2FsX2tleSl9YH1cbiAgICAgICAgICAgICAgY2xhc3NOYW1lPVwibXQtMiBpbmxpbmUtYmxvY2sg
dGV4dC14cyB0ZXh0LVtjb2xvcjp2YXIoLS1jb2xvci1hY2NlbnQpXSBob3Zlcjp1bmRlcmxpbmVcIlxuICAgICAgICAgICAg
PlxuICAgICAgICAgICAgICBGaWxsIHRoZXNlIGluIFx1MjE5MlxuICAgICAgICAgICAgPC9MaW5rPlxuICAgICAgICAgIDwv
ZGl2PlxuICAgICAgICApKX1cbiAgICAgIDwvQ2FyZENvbnRlbnQ+XG4gICAgPC9DYXJkPlxuICApO1xufVxuXG5mdW5jdGlv
biBGaWd1cmUoeyBsYWJlbDogbmFtZSwgdmFsdWUgfTogeyBsYWJlbDogc3RyaW5nOyB2YWx1ZTogc3RyaW5nIH0pIHtcbiAg
cmV0dXJuIChcbiAgICA8ZGl2PlxuICAgICAgPGRpdiBjbGFzc05hbWU9XCJ0ZXh0LVsxMXB4XSB1cHBlcmNhc2UgdHJhY2tp
bmctd2lkZXIgdGV4dC1tdXRlZC1mb3JlZ3JvdW5kXCI+e25hbWV9PC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzTmFtZT1cInRh
YnVsYXItbnVtc1wiPnt2YWx1ZX08L2Rpdj5cbiAgICA8L2Rpdj5cbiAgKTtcbn1cbiJ9LCAiZWRpdHMiOiBbeyJwYXRoIjog
ImJhY2tlbmQvYXBwL3NlcnZpY2VzL3Nwb3RsaWdodF9zZXJ2aWNlLnB5IiwgImFuY2hvciI6ICIgICAgICAgIFwid2luZG93
c1wiOiB7XG4gICAgICAgICAgICBcImRheVwiOiB7XCJmcm9tXCI6IGRheV9zdGFydC5pc29mb3JtYXQoKSwgXCJ0b1wiOiB0
b2RheS5pc29mb3JtYXQoKX0sXG4gICAgICAgICAgICBcIndlZWtcIjoge1wiZnJvbVwiOiB3ZWVrX3N0YXJ0Lmlzb2Zvcm1h
dCgpLCBcInRvXCI6IHRvZGF5Lmlzb2Zvcm1hdCgpfSxcbiAgICAgICAgfSxcbiAgICB9IiwgInJlcGxhY2VtZW50IjogIiAg
ICAgICAgXCJ3aW5kb3dzXCI6IHtcbiAgICAgICAgICAgIFwiZGF5XCI6IHtcImZyb21cIjogZGF5X3N0YXJ0Lmlzb2Zvcm1h
dCgpLCBcInRvXCI6IHRvZGF5Lmlzb2Zvcm1hdCgpfSxcbiAgICAgICAgICAgIFwid2Vla1wiOiB7XCJmcm9tXCI6IHdlZWtf
c3RhcnQuaXNvZm9ybWF0KCksIFwidG9cIjogdG9kYXkuaXNvZm9ybWF0KCl9LFxuICAgICAgICB9LFxuICAgIH1cblxuXG5h
c3luYyBkZWYgYm9hcmQoc2Vzc2lvbjogQXN5bmNTZXNzaW9uLCBjb250ZXh0OiBVc2VyQ29udGV4dCkgLT4gZGljdFtzdHIs
IEFueV06XG4gICAgXCJcIlwiRXZlcnkgc2NvcGVkIGFwcCB3aXRoIGl0cyBjdXJhdGVkIGZpZWxkcyBhbmQgd2hhdCBpcyBt
aXNzaW5nIC0gdGhlIHdhbGwgdmlldy5cblxuICAgIFRoZSBzaG9ydGxpc3QgYW5zd2VycyBcIndoYXQgc2hvdWxkIEkgZml4
IHRoaXMgbW9ybmluZ1wiOyB0aGlzIGFuc3dlcnMgXCJob3cgYmFkIGlzIGl0XG4gICAgb3ZlcmFsbFwiLCBhbmQgaXQgbGlz
dHMgQ09NUExFVEUgYXBwcyB0b28gLSBhIGZpbGxlZC1pbiByZWNvcmQgdHVybnMgZ3JlZW4gcmF0aGVyIHRoYW5cbiAgICBk
aXNhcHBlYXJpbmcsIHNvIFwiZG9uZVwiIHN0YXlzIHZpc2libGUgaW5zdGVhZCBvZiBpbmRpc3Rpbmd1aXNoYWJsZSBmcm9t
IFwiaW52aXNpYmxlXCIuXG5cbiAgICBPcmRlcmVkIGJ5IG5hbWUsIG5vdCByZXZlbnVlOiBhIHdhbGwgaXMgZm9yIGZpbmRp
bmcgYSBzcGVjaWZpYyBhcHAsIGFuZCBhbHBoYWJldGljYWxcbiAgICBpcyB0aGUgb25lIG9yZGVyIGEgcGVyc29uIGNhbiBw
cmVkaWN0LlxuICAgIFwiXCJcIlxuICAgIG1hc3RlciA9IEFQUF9NQVNURVJfVEFCTEUuY1xuICAgIHNjb3BlID0gYnVpbGRf
c2NvcGVfZmlsdGVyKGNvbnRleHQuc2NvcGVzLCBjb2x1bW5zPV9tYXN0ZXJfc2NvcGVfY29sdW1ucygpKVxuICAgIHN0YXRl
bWVudCA9IChcbiAgICAgICAgc2VsZWN0KFxuICAgICAgICAgICAgbWFzdGVyLmNhbm9uaWNhbF9rZXksXG4gICAgICAgICAg
ICBtYXN0ZXIuYXBwX25hbWUsXG4gICAgICAgICAgICBtYXN0ZXIucGxhdGZvcm0sXG4gICAgICAgICAgICAqW21hc3Rlcltu
YW1lXS5sYWJlbChuYW1lKSBmb3IgbmFtZSBpbiBSRVFVSVJFRF9GSUVMRFNdLFxuICAgICAgICApXG4gICAgICAgIC53aGVy
ZShzY29wZSlcbiAgICAgICAgLm9yZGVyX2J5KFxuICAgICAgICAgICAgZnVuYy5sb3dlcihmdW5jLmNvYWxlc2NlKG1hc3Rl
ci5hcHBfbmFtZSwgbWFzdGVyLmNhbm9uaWNhbF9rZXkpKSxcbiAgICAgICAgICAgIG1hc3Rlci5jYW5vbmljYWxfa2V5LFxu
ICAgICAgICApXG4gICAgKVxuICAgIHJvd3MgPSAoYXdhaXQgc2Vzc2lvbi5leGVjdXRlKHN0YXRlbWVudCkpLm1hcHBpbmdz
KCkuYWxsKClcblxuICAgIGFwcHMgPSBbXVxuICAgIGZvciByb3cgaW4gcm93czpcbiAgICAgICAgbWlzc2luZyA9IFtcbiAg
ICAgICAgICAgIG5hbWVcbiAgICAgICAgICAgIGZvciBuYW1lIGluIFJFUVVJUkVEX0ZJRUxEU1xuICAgICAgICAgICAgaWYg
cm93LmdldChuYW1lKSBpcyBOb25lIG9yIHN0cihyb3cuZ2V0KG5hbWUpKS5zdHJpcCgpID09IFwiXCJcbiAgICAgICAgXVxu
ICAgICAgICBhcHBzLmFwcGVuZChcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICBcImNhbm9uaWNhbF9rZXlcIjog
cm93W1wiY2Fub25pY2FsX2tleVwiXSxcbiAgICAgICAgICAgICAgICBcImFwcF9uYW1lXCI6IHJvd1tcImFwcF9uYW1lXCJd
LFxuICAgICAgICAgICAgICAgIFwicGxhdGZvcm1cIjogcm93W1wicGxhdGZvcm1cIl0sXG4gICAgICAgICAgICAgICAgXCJm
aWVsZHNcIjoge25hbWU6IHJvdy5nZXQobmFtZSkgZm9yIG5hbWUgaW4gUkVRVUlSRURfRklFTERTfSxcbiAgICAgICAgICAg
ICAgICBcIm1pc3NpbmdcIjogbWlzc2luZyxcbiAgICAgICAgICAgIH1cbiAgICAgICAgKVxuXG4gICAgaW5jb21wbGV0ZSA9
IHN1bSgxIGZvciBhcHAgaW4gYXBwcyBpZiBhcHBbXCJtaXNzaW5nXCJdKVxuICAgIHJldHVybiB7XG4gICAgICAgIFwicmVx
dWlyZWRfZmllbGRzXCI6IGxpc3QoUkVRVUlSRURfRklFTERTKSxcbiAgICAgICAgXCJ0b3RhbFwiOiBsZW4oYXBwcyksXG4g
ICAgICAgIFwiaW5jb21wbGV0ZVwiOiBpbmNvbXBsZXRlLFxuICAgICAgICBcImNvbXBsZXRlXCI6IGxlbihhcHBzKSAtIGlu
Y29tcGxldGUsXG4gICAgICAgIFwiYXBwc1wiOiBhcHBzLFxuICAgIH0iLCAibWFya2VyIjogImFzeW5jIGRlZiBib2FyZChz
ZXNzaW9uOiBBc3luY1Nlc3Npb24sIGNvbnRleHQ6IFVzZXJDb250ZXh0KSJ9LCB7InBhdGgiOiAiYmFja2VuZC9hcHAvYXBp
L3YxL3Nwb3RsaWdodC5weSIsICJhbmNob3IiOiAiICAgIHJldHVybiBhd2FpdCBzcG90bGlnaHRfc2VydmljZS5idWlsZChc
biAgICAgICAgZGIsIGNvbnRleHQsIFF1ZXJ5QnVpbGRlcihjb250ZXh0KSwgZGF0ZS50b2RheSgpLCBsaW1pdD1saW1pdFxu
ICAgICkiLCAicmVwbGFjZW1lbnQiOiAiICAgIHJldHVybiBhd2FpdCBzcG90bGlnaHRfc2VydmljZS5idWlsZChcbiAgICAg
ICAgZGIsIGNvbnRleHQsIFF1ZXJ5QnVpbGRlcihjb250ZXh0KSwgZGF0ZS50b2RheSgpLCBsaW1pdD1saW1pdFxuICAgIClc
blxuXG5Acm91dGVyLmdldChcIi9ib2FyZFwiKVxuYXN5bmMgZGVmIHNwb3RsaWdodF9ib2FyZChjb250ZXh0OiBDdXJyZW50
VXNlciwgZGI6IERiU2Vzc2lvbikgLT4gZGljdFtzdHIsIEFueV06XG4gICAgXCJcIlwiRXZlcnkgc2NvcGVkIGFwcCwgc2hh
ZGVkIGJ5IGNvbXBsZXRlbmVzcyAtIHRoZSB3YWxsIGJlaGluZCB0aGUgc2hvcnRsaXN0LlxuXG4gICAgU2NvcGVkIGV4YWN0
bHkgbGlrZSB0aGUgc2hvcnRsaXN0LCBmb3IgdGhlIHNhbWUgcmVhc29uOiB3aXRoIG5vIHJvdyBzY29wZSB0aGlzXG4gICAg
cmV0dXJucyBOT1RISU5HLCBiZWNhdXNlIGJlaW5nIHNob3duIGFuIGFwcCBpcyBiZWluZyB0b2xkIGl0IGV4aXN0cy5cbiAg
ICBcIlwiXCJcbiAgICByZXR1cm4gYXdhaXQgc3BvdGxpZ2h0X3NlcnZpY2UuYm9hcmQoZGIsIGNvbnRleHQpIiwgIm1hcmtl
ciI6ICJAcm91dGVyLmdldChcIi9ib2FyZFwiKSJ9LCB7InBhdGgiOiAiZnJvbnRlbmQvbGliL3R5cGVzLnRzIiwgImFuY2hv
ciI6ICJleHBvcnQgaW50ZXJmYWNlIFNwb3RsaWdodCB7XG4gIHJlcXVpcmVkX2ZpZWxkczogc3RyaW5nW107XG4gIGluY29t
cGxldGVfY291bnQ6IG51bWJlcjtcbiAgb2ZfdGhlX2RheTogU3BvdGxpZ2h0QXBwW107XG4gIG9mX3RoZV93ZWVrOiBTcG90
bGlnaHRBcHBbXTtcbiAgd2luZG93czoge1xuICAgIGRheTogeyBmcm9tOiBzdHJpbmc7IHRvOiBzdHJpbmcgfTtcbiAgICB3
ZWVrOiB7IGZyb206IHN0cmluZzsgdG86IHN0cmluZyB9O1xuICB9O1xufSIsICJyZXBsYWNlbWVudCI6ICJleHBvcnQgaW50
ZXJmYWNlIFNwb3RsaWdodCB7XG4gIHJlcXVpcmVkX2ZpZWxkczogc3RyaW5nW107XG4gIGluY29tcGxldGVfY291bnQ6IG51
bWJlcjtcbiAgb2ZfdGhlX2RheTogU3BvdGxpZ2h0QXBwW107XG4gIG9mX3RoZV93ZWVrOiBTcG90bGlnaHRBcHBbXTtcbiAg
d2luZG93czoge1xuICAgIGRheTogeyBmcm9tOiBzdHJpbmc7IHRvOiBzdHJpbmcgfTtcbiAgICB3ZWVrOiB7IGZyb206IHN0
cmluZzsgdG86IHN0cmluZyB9O1xuICB9O1xufVxuXG4vKiogT25lIHRpbGUgb24gdGhlIFNwb3RsaWdodCBib2FyZDogdGhl
IGFwcCwgaXRzIGN1cmF0ZWQgZmllbGRzLCBhbmQgd2hhdCBpcyBtaXNzaW5nLiAqL1xuZXhwb3J0IGludGVyZmFjZSBTcG90
bGlnaHRCb2FyZEFwcCB7XG4gIGNhbm9uaWNhbF9rZXk6IHN0cmluZztcbiAgYXBwX25hbWU6IHN0cmluZyB8IG51bGw7XG4g
IHBsYXRmb3JtOiBzdHJpbmcgfCBudWxsO1xuICBmaWVsZHM6IFJlY29yZDxzdHJpbmcsIHN0cmluZyB8IG51bWJlciB8IG51
bGw+O1xuICBtaXNzaW5nOiBzdHJpbmdbXTtcbn1cblxuZXhwb3J0IGludGVyZmFjZSBTcG90bGlnaHRCb2FyZCB7XG4gIHJl
cXVpcmVkX2ZpZWxkczogc3RyaW5nW107XG4gIHRvdGFsOiBudW1iZXI7XG4gIGluY29tcGxldGU6IG51bWJlcjtcbiAgY29t
cGxldGU6IG51bWJlcjtcbiAgYXBwczogU3BvdGxpZ2h0Qm9hcmRBcHBbXTtcbn0iLCAibWFya2VyIjogImV4cG9ydCBpbnRl
cmZhY2UgU3BvdGxpZ2h0Qm9hcmRBcHAgeyJ9LCB7InBhdGgiOiAiZnJvbnRlbmQvbGliL2FwaS1ob29rcy50cyIsICJhbmNo
b3IiOiAiICBCcmllZmluZyxcbiAgU3BvdGxpZ2h0LCIsICJyZXBsYWNlbWVudCI6ICIgIEJyaWVmaW5nLFxuICBTcG90bGln
aHQsXG4gIFNwb3RsaWdodEJvYXJkLCIsICJtYXJrZXIiOiAiICBTcG90bGlnaHRCb2FyZCwifSwgeyJwYXRoIjogImZyb250
ZW5kL2xpYi9hcGktaG9va3MudHMiLCAiYW5jaG9yIjogImV4cG9ydCBmdW5jdGlvbiB1c2VTcG90bGlnaHQoKSB7XG4gIGNv
bnN0IHsgdXNlciB9ID0gdXNlQXV0aCgpO1xuICByZXR1cm4gdXNlUXVlcnkoe1xuICAgIHF1ZXJ5S2V5OiBbXCJzcG90bGln
aHRcIl0sXG4gICAgcXVlcnlGbjogKCkgPT4gYXBpRmV0Y2g8U3BvdGxpZ2h0PihcIi9hcGkvdjEvc3BvdGxpZ2h0XCIpLFxu
ICAgIGVuYWJsZWQ6IEJvb2xlYW4odXNlciksXG4gICAgLy8gU2hvcnQ6IHRoZSBwYW5lbCdzIHdob2xlIGpvYiBpcyB0byBl
bXB0eSBhcyBwZW9wbGUgZmlsbCBmaWVsZHMgaW4sIGFuZCBzaG93aW5nIGFcbiAgICAvLyBzdGFsZSBjb3B5IG9mIGl0c2Vs
ZiBpcyB0aGUgb25lIGZhaWx1cmUgdGhhdCBtYWtlcyBpdCB1bnRydXN0d29ydGh5LlxuICAgIHN0YWxlVGltZTogMzAgKiAx
MDAwLFxuICB9KTtcbn0iLCAicmVwbGFjZW1lbnQiOiAiZXhwb3J0IGZ1bmN0aW9uIHVzZVNwb3RsaWdodCgpIHtcbiAgY29u
c3QgeyB1c2VyIH0gPSB1c2VBdXRoKCk7XG4gIHJldHVybiB1c2VRdWVyeSh7XG4gICAgcXVlcnlLZXk6IFtcInNwb3RsaWdo
dFwiXSxcbiAgICBxdWVyeUZuOiAoKSA9PiBhcGlGZXRjaDxTcG90bGlnaHQ+KFwiL2FwaS92MS9zcG90bGlnaHRcIiksXG4g
ICAgZW5hYmxlZDogQm9vbGVhbih1c2VyKSxcbiAgICAvLyBTaG9ydDogdGhlIHBhbmVsJ3Mgd2hvbGUgam9iIGlzIHRvIGVt
cHR5IGFzIHBlb3BsZSBmaWxsIGZpZWxkcyBpbiwgYW5kIHNob3dpbmcgYVxuICAgIC8vIHN0YWxlIGNvcHkgb2YgaXRzZWxm
IGlzIHRoZSBvbmUgZmFpbHVyZSB0aGF0IG1ha2VzIGl0IHVudHJ1c3R3b3J0aHkuXG4gICAgc3RhbGVUaW1lOiAzMCAqIDEw
MDAsXG4gIH0pO1xufVxuXG4vKiogVGhlIHdhbGwgYmVoaW5kIHRoZSBzaG9ydGxpc3Q6IEVWRVJZIHNjb3BlZCBhcHAsIHNo
YWRlZCBieSBjb21wbGV0ZW5lc3MuICovXG5leHBvcnQgZnVuY3Rpb24gdXNlU3BvdGxpZ2h0Qm9hcmQoKSB7XG4gIGNvbnN0
IHsgdXNlciB9ID0gdXNlQXV0aCgpO1xuICByZXR1cm4gdXNlUXVlcnkoe1xuICAgIHF1ZXJ5S2V5OiBbXCJzcG90bGlnaHQt
Ym9hcmRcIl0sXG4gICAgcXVlcnlGbjogKCkgPT4gYXBpRmV0Y2g8U3BvdGxpZ2h0Qm9hcmQ+KFwiL2FwaS92MS9zcG90bGln
aHQvYm9hcmRcIiksXG4gICAgZW5hYmxlZDogQm9vbGVhbih1c2VyKSxcbiAgICBzdGFsZVRpbWU6IDMwICogMTAwMCxcbiAg
fSk7XG59IiwgIm1hcmtlciI6ICJleHBvcnQgZnVuY3Rpb24gdXNlU3BvdGxpZ2h0Qm9hcmQoKSB7In0sIHsicGF0aCI6ICJi
YWNrZW5kL3Rlc3RzL3Rlc3Rfc3BvdGxpZ2h0LnB5IiwgImFuY2hvciI6ICIgICAgYXNzZXJ0IHJlc3VsdFtcImluY29tcGxl
dGVfY291bnRcIl0gPT0gMTJcbiAgICBhc3NlcnQgbGVuKHJlc3VsdFtcIm9mX3RoZV9kYXlcIl0pID09IHNwb3RsaWdodF9z
ZXJ2aWNlLlRPUF9OXG4gICAgYXNzZXJ0IHJlc3VsdFtcIm9mX3RoZV9kYXlcIl1bMF1bXCJjYW5vbmljYWxfa2V5XCJdID09
IFwiYXBwLTExXCIiLCAicmVwbGFjZW1lbnQiOiAiICAgIGFzc2VydCByZXN1bHRbXCJpbmNvbXBsZXRlX2NvdW50XCJdID09
IDEyXG4gICAgYXNzZXJ0IGxlbihyZXN1bHRbXCJvZl90aGVfZGF5XCJdKSA9PSBzcG90bGlnaHRfc2VydmljZS5UT1BfTlxu
ICAgIGFzc2VydCByZXN1bHRbXCJvZl90aGVfZGF5XCJdWzBdW1wiY2Fub25pY2FsX2tleVwiXSA9PSBcImFwcC0xMVwiXG5c
blxuYXN5bmMgZGVmIHRlc3RfdGhlX2JvYXJkX2xpc3RzX2NvbXBsZXRlX2FwcHNfdG9vKGFwcF9tYXN0ZXJfc2Vzc2lvbjog
QW55KSAtPiBOb25lOlxuICAgICMgVGhlIHdhbGwgaXMgdGhlIHJlY29yZCwgbm90IHRoZSBhbGFybTogYSBmaWxsZWQtaW4g
YXBwIHR1cm5zIGdyZWVuIHJhdGhlciB0aGFuXG4gICAgIyBkaXNhcHBlYXJpbmcsIHNvIFwiZG9uZVwiIHN0YXlzIHZpc2li
bGUgaW5zdGVhZCBvZiBpbmRpc3Rpbmd1aXNoYWJsZSBmcm9tIFwiaW52aXNpYmxlXCIuXG4gICAgYXdhaXQgX2FwcChhcHBf
bWFzdGVyX3Nlc3Npb24sIFwiZG9uZVwiKVxuICAgIGF3YWl0IF9hcHAoYXBwX21hc3Rlcl9zZXNzaW9uLCBcImdhcFwiLCBw
b2Rfb3duZXI9Tm9uZSlcbiAgICBhd2FpdCBhcHBfbWFzdGVyX3Nlc3Npb24uY29tbWl0KClcblxuICAgIHJlc3VsdCA9IGF3
YWl0IHNwb3RsaWdodF9zZXJ2aWNlLmJvYXJkKGFwcF9tYXN0ZXJfc2Vzc2lvbiwgX2NvbnRleHQoWyhcImFsbFwiLCBOb25l
KV0pKVxuXG4gICAgYXNzZXJ0IHJlc3VsdFtcInRvdGFsXCJdID09IDJcbiAgICBhc3NlcnQgcmVzdWx0W1wiaW5jb21wbGV0
ZVwiXSA9PSAxIGFuZCByZXN1bHRbXCJjb21wbGV0ZVwiXSA9PSAxXG4gICAgYnlfa2V5ID0ge2FwcFtcImNhbm9uaWNhbF9r
ZXlcIl06IGFwcCBmb3IgYXBwIGluIHJlc3VsdFtcImFwcHNcIl19XG4gICAgYXNzZXJ0IGJ5X2tleVtcImRvbmVcIl1bXCJt
aXNzaW5nXCJdID09IFtdXG4gICAgYXNzZXJ0IGJ5X2tleVtcImdhcFwiXVtcIm1pc3NpbmdcIl0gPT0gW1wicG9kX293bmVy
XCJdXG4gICAgYXNzZXJ0IGJ5X2tleVtcImdhcFwiXVtcImZpZWxkc1wiXVtcInB1Ymxpc2hlclwiXSA9PSBcIlB1YkFcIlxu
XG5cbmFzeW5jIGRlZiB0ZXN0X3RoZV9ib2FyZF9pc19zY29wZWRfbGlrZV90aGVfc2hvcnRsaXN0KGFwcF9tYXN0ZXJfc2Vz
c2lvbjogQW55KSAtPiBOb25lOlxuICAgIGF3YWl0IF9hcHAoYXBwX21hc3Rlcl9zZXNzaW9uLCBcIm1pbmVcIiwgcG9kX293
bmVyPU5vbmUpXG4gICAgYXdhaXQgX2FwcChhcHBfbWFzdGVyX3Nlc3Npb24sIFwidGhlaXJzXCIsIGhvdT1cIkgyXCIsIHBv
ZD0yLCBwb2Rfb3duZXI9Tm9uZSlcbiAgICBhd2FpdCBhcHBfbWFzdGVyX3Nlc3Npb24uY29tbWl0KClcblxuICAgIHJlc3Vs
dCA9IGF3YWl0IHNwb3RsaWdodF9zZXJ2aWNlLmJvYXJkKGFwcF9tYXN0ZXJfc2Vzc2lvbiwgX2NvbnRleHQoWyhcImhvdVwi
LCBcIkgxXCIpXSkpXG4gICAgYXNzZXJ0IFthcHBbXCJjYW5vbmljYWxfa2V5XCJdIGZvciBhcHAgaW4gcmVzdWx0W1wiYXBw
c1wiXV0gPT0gW1wibWluZVwiXVxuXG4gICAgbm90aGluZyA9IGF3YWl0IHNwb3RsaWdodF9zZXJ2aWNlLmJvYXJkKGFwcF9t
YXN0ZXJfc2Vzc2lvbiwgX2NvbnRleHQoW10pKVxuICAgIGFzc2VydCBub3RoaW5nW1widG90YWxcIl0gPT0gMCBhbmQgbm90
aGluZ1tcImFwcHNcIl0gPT0gW10iLCAibWFya2VyIjogImFzeW5jIGRlZiB0ZXN0X3RoZV9ib2FyZF9saXN0c19jb21wbGV0
ZV9hcHBzX3RvbyJ9XX0=
"""



def resolve(text, anchor, replacement, marker):
    """Match against a file whose punctuation may have been normalised (em-dash -> hyphen).
    When the flattened form is the one that matches, flatten the replacement and marker
    too, or the patch reintroduces the very character the file was cleaned of."""
    if anchor in text:
        return anchor, replacement, marker
    flat = anchor.replace("\u2014", "-")
    if flat != anchor and flat in text:
        return flat, replacement.replace("\u2014", "-"), marker.replace("\u2014", "-")
    return anchor, replacement, marker


def locate(lines, anchor):
    """Line index where the longest present run of the anchor's own lines begins."""
    wanted = anchor.splitlines()
    joined = "\n".join(lines)
    for take in range(len(wanted), 0, -1):
        for start in (0, len(wanted) - take):
            probe = "\n".join(wanted[start:start + take])
            if not probe.strip():
                continue
            index = joined.find(probe)
            if index != -1:
                return joined.count("\n", 0, index) - start
    for offset, line in sorted(enumerate(wanted), key=lambda p: len(p[1].strip()), reverse=True):
        if len(line.strip()) < 12:
            break
        index = joined.find(line)
        if index != -1:
            return joined.count("\n", 0, index) - offset
    return None


def main():
    if not Path("frontend/app").is_dir() or not Path("backend/app").is_dir():
        print("ABORTED: run this from the repository root")
        return 1
    data = json.loads(base64.b64decode(PAYLOAD.strip()).decode())
    problems, failures, planned, skipped = [], [], {}, []

    for rel, content in data.get("new_files", {}).items():
        path = Path(rel)
        if path.exists() and path.read_text() == content:
            skipped.append(f"{rel}: already present and identical")
            continue
        planned[rel] = content

    for index, item in enumerate(data["edits"], start=1):
        rel = item["path"]
        path = Path(rel)
        if not path.exists():
            problems.append(f"  [{index}] {rel}: file not found")
            continue
        text = planned.get(rel, path.read_text())
        anchor, replacement, marker = resolve(text, item["anchor"], item["replacement"], item["marker"])
        if marker in text:
            skipped.append(f"{rel} [{index}]: already applied")
            continue
        found = text.count(anchor)
        if found != 1:
            head = anchor.splitlines()[0][:76]
            problems.append(f"  [{index}] {rel}: expected exactly 1 match, found {found}\n"
                            f"        anchor starts: {head!r}")
            failures.append((rel, anchor))
            continue
        planned[rel] = text.replace(anchor, replacement, 1)

    if problems:
        print("ABORTED - NOTHING was written. Every problem, so one round-trip fixes all:")
        print()
        for problem in problems:
            print(problem)
        shown = {}
        for rel, anchor in failures:
            lines = Path(rel).read_text().splitlines()
            hit = locate(lines, anchor)
            if hit is None:
                lo, hi = 0, min(len(lines), 120)
                note = "nothing from this anchor is on disk - head of file"
            else:
                lo, hi = max(0, hit - 30), min(len(lines), hit + 30)
                note = f"nearest partial match at line {hit + 1}"
            if any(lo >= a and hi <= b for a, b in shown.get(rel, [])):
                continue
            shown.setdefault(rel, []).append((lo, hi))
            print()
            print(f"----- {rel} lines {lo + 1}-{hi} of {len(lines)} ({note}) -----")
            for number, line in enumerate(lines[lo:hi], start=lo + 1):
                print(f"{number:6d}\t{line}")
        print()
        print("The regions above are what is actually on disk; I re-anchor from them.")
        return 1

    for rel, content in sorted(planned.items()):
        Path(rel).parent.mkdir(parents=True, exist_ok=True)
        Path(rel).write_text(content)
        print(f"wrote {rel}")
    for note in skipped:
        print(f"skip  {note}")
    if not planned:
        print("nothing to do - already applied")
    print()
    print(FOOTER)
    return 0


if __name__ == "__main__":
    sys.exit(main())
